# Generated by Django 5.2.17 on 2026-08-15 12:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('source', models.CharField(default='django', max_length=32)),
                ('db_ok', models.BooleanField(default=True)),
                ('cache_ok', models.BooleanField(default=True)),
                ('storage_ok', models.BooleanField(default=True)),
                ('ml_ok', models.BooleanField(blank=True, null=True)),
                ('overpass_ok', models.BooleanField(blank=True, null=True)),
                ('media_storage_ok', models.BooleanField(default=True)),
                ('db_latency_ms', models.FloatField(blank=True, null=True)),
                ('api_p95_ms', models.FloatField(blank=True, null=True)),
                ('disk_used_pct', models.FloatField(blank=True, null=True)),
                ('memory_used_pct', models.FloatField(blank=True, null=True)),
                ('cpu_pct', models.FloatField(blank=True, null=True)),
                ('error_rate_5min', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('actor_role', models.CharField(blank=True, max_length=32, null=True)),
                ('category', models.CharField(choices=[('auth', 'Authentication'), ('data', 'Data change'), ('admin', 'Admin action'), ('security', 'Security'), ('payment', 'Payment'), ('media', 'Media/Image'), ('ml', 'ML / AI'), ('system', 'System'), ('frontend', 'Frontend'), ('other', 'Other')], db_index=True, default='other', max_length=16)),
                ('severity', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], db_index=True, default='info', max_length=10)),
                ('source', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('celery', 'Worker/Celery'), ('cron', 'Scheduled task'), ('external', 'External webhook')], db_index=True, default='backend', max_length=16)),
                ('action', models.CharField(db_index=True, max_length=120)),
                ('message', models.TextField(blank=True)),
                ('object_type', models.CharField(blank=True, db_index=True, max_length=120)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('endpoint', models.CharField(blank=True, max_length=255, null=True)),
                ('method', models.CharField(blank=True, max_length=10, null=True)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit log entry',
                'verbose_name_plural': 'Audit log entries',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='audit_audit_timesta_901180_idx'), models.Index(fields=['category', 'severity'], name='audit_audit_categor_a45df2_idx'), models.Index(fields=['object_type', 'object_id'], name='audit_audit_object__1f9df3_idx')],
            },
        ),
        migrations.CreateModel(
            name='ErrorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('occurrences', models.PositiveIntegerField(default=1)),
                ('resolved', models.BooleanField(db_index=True, default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('celery', 'Worker/Celery'), ('cron', 'Scheduled task'), ('external', 'External webhook')], db_index=True, default='backend', max_length=16)),
                ('severity', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], db_index=True, default='error', max_length=10)),
                ('error_type', models.CharField(db_index=True, max_length=120)),
                ('error_message', models.TextField(blank=True)),
                ('fingerprint', models.CharField(db_index=True, max_length=120)),
                ('endpoint', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('method', models.CharField(blank=True, max_length=10, null=True)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referer', models.URLField(blank=True, null=True)),
                ('traceback', models.TextField(blank=True)),
                ('component', models.CharField(blank=True, max_length=160, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_errors', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Error event',
                'verbose_name_plural': 'Error events',
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['-last_seen'], name='audit_error_last_se_f12b6a_idx'), models.Index(fields=['source', 'resolved', 'severity'], name='audit_error_source_725b5b_idx')],
            },
        ),
    ]
