import { useState } from "react"
import { Link } from "react-router-dom"
import { AnimatePresence, motion } from "framer-motion"
import { FiAlertCircle, FiArrowRight, FiBookOpen, FiCheckCircle, FiCompass, FiHelpCircle, FiInfo, FiLock, FiMapPin, FiMessageSquare, FiSearch, FiSettings, FiUserCheck, FiChevronDown } from "react-icons/fi"
import PageHeader from "../components/common/PageHeader"
import EmptyState from "../components/common/EmptyState"
import Breadcrumbs from "../components/common/Breadcrumbs"
import CMSPageIntro from "../components/cms/CMSPageIntro"

const travellerTopics = [
  { id: "discover", title: "Discover with context", icon: <FiCompass className="text-[var(--ny-green)] text-xl" />, content: "Destination pages bring together recorded places, location details, images and practical notes. The source and availability of each field are shown when available.", highlights: ["Browse by destination, district or category.", "Compare places before choosing a route.", "Use the catalogue when a field is not yet recorded."] },
  { id: "honesty", title: "How we handle missing information", icon: <FiMapPin className="text-[var(--ny-green)] text-xl" />, content: "Nepal Yatra does not fill gaps with guessed coordinates, prices, opening hours or emergency details. An unavailable field is a deliberate state, not a failure.", highlights: ["Unverified coordinates are not placed on a map.", "Unrecorded costs and hours are not estimated for display.", "Travellers can report a correction or add evidence."] },
  { id: "assistant", title: "Using the travel assistant", icon: <FiMessageSquare className="text-[var(--ny-green)] text-xl" />, content: "The assistant can help you find catalogue records and understand the information available on the site. It should not be treated as a source of unverified emergency or operational details.", highlights: ["Ask for a place, district or category.", "Review the linked record before making plans.", "Use the emergency directory for time-sensitive needs."] },
  { id: "report", title: "Report a correction", icon: <FiAlertCircle className="text-[var(--ny-warning)] text-xl" />, content: "If a record looks inaccurate or a detail has changed, send a message with the place name and any evidence you have. The review team can assess the update before it is published.", highlights: ["Describe the field that needs attention.", "Attach a photo or document when safe and relevant.", "Avoid sharing private personal information."] },
]

const standardsTopics = [
  { id: "records", title: "Keep records useful", icon: <FiBookOpen className="text-[var(--ny-green)] text-xl" />, content: "Content should describe a real place or service and make its location, ownership and source context clear wherever possible.", highlights: ["Use a specific place name.", "Keep district and province fields distinct.", "Prefer a source link or evidence note for corrections."] },
  { id: "coordinates", title: "Coordinates need context", icon: <FiMapPin className="text-[var(--ny-green)] text-xl" />, content: "A coordinate is useful only when its source and intended meaning are clear. Do not use a district centre as a substitute for an unknown point.", highlights: ["Leave coordinates blank when they are unknown.", "Explain approximate or inaccessible locations.", "Do not publish a pin that could send someone to the wrong place."] },
  { id: "costs", title: "Costs and schedules change", icon: <FiSettings className="text-[var(--ny-warning)] text-xl" />, content: "Prices, permits, hours and transport details can vary by season, provider and location. The interface should show the recorded value and its date or mark it unavailable.", highlights: ["Do not invent a price to make a card look complete.", "Record the currency and unit explicitly.", "Link to an official source when one is available."] },
  { id: "privacy", title: "Protect people and privacy", icon: <FiLock className="text-[var(--ny-green)] text-xl" />, content: "Public content should avoid exposing private addresses, live trip links or personal information. Safety and account features should use the minimum data needed for their purpose.", highlights: ["Do not publish another traveller's personal details.", "Treat shared trip links as credentials.", "Remove sensitive evidence when it is no longer needed."] },
]

const faqs = [
  { q: "Why does a destination say that a map location is unavailable?", a: "Precise coordinates may not be recorded or verified. Nepal Yatra leaves the map location unavailable rather than placing an uncertain pin at a district centre." },
  { q: "Why are prices or opening hours unavailable?", a: "Those details can change and may differ by provider or season. If the record does not contain a reliable value, the page does not substitute a guess." },
  { q: "Can I use the assistant for an emergency?", a: "Use the Emergency page and the verified directory records available there. The assistant is a discovery and planning tool, not an emergency dispatch service." },
  { q: "How do I report an incorrect record?", a: "Use the Contact page or the destination feedback action. Include the place name, the field that needs attention and evidence when it is safe to share it." },
  { q: "Can I add a place or service?", a: "Yes. Use the submission form available to signed-in travellers. A submission is a request for review, not a guarantee that it will be published." },
]

export default function HowItWorks() {
  const [activeRole, setActiveRole] = useState("traveller")
  const [searchQuery, setSearchQuery] = useState("")
  const [expandedFaq, setExpandedFaq] = useState(null)
  const topics = activeRole === "traveller" ? travellerTopics : standardsTopics
  const filteredTopics = topics.filter((topic) => `${topic.title} ${topic.content} ${topic.highlights.join(" ")}`.toLowerCase().includes(searchQuery.toLowerCase()))

  return (
    <div className="ny-page container-app space-y-8 py-6 sm:py-8">
      <Breadcrumbs items={[{ label: "Home", to: "/" }, { label: "How it works", to: "/how-it-works" }]} />
      <CMSPageIntro pageKey="how-it-works" />
      <PageHeader title="How Nepal Yatra works" subtitle="A practical guide to discovering places, planning a route and understanding what our records can—and cannot—tell you." icon={FiBookOpen} />

      <div className="flex flex-col gap-4 border-y border-[var(--ny-border)] py-4 sm:flex-row sm:items-center sm:justify-between">
        <div className="flex flex-wrap gap-2" role="tablist" aria-label="Guide type">
          <button type="button" role="tab" aria-selected={activeRole === "traveller"} onClick={() => setActiveRole("traveller")} className={`ny-btn ${activeRole === "traveller" ? "ny-btn-primary" : "ny-btn-secondary"}`}><FiUserCheck size={16} aria-hidden="true" />For travellers</button>
          <button type="button" role="tab" aria-selected={activeRole === "standards"} onClick={() => setActiveRole("standards")} className={`ny-btn ${activeRole === "standards" ? "ny-btn-primary" : "ny-btn-secondary"}`}><FiSettings size={16} aria-hidden="true" />Content standards</button>
        </div>
        <p className="max-w-xl text-sm text-[var(--ny-text-secondary)]">Clear records are more useful than confident guesses. If a detail is missing, the interface says so.</p>
      </div>

      <div className="grid gap-4 md:grid-cols-[minmax(0,1fr)_minmax(260px,0.42fr)] md:items-center">
        <div className="relative"><FiSearch size={17} className="pointer-events-none absolute left-3.5 top-1/2 -translate-y-1/2 text-[var(--ny-text-muted)]" aria-hidden="true" /><label htmlFor="guide-search" className="sr-only">Search this guide</label><input id="guide-search" className="input-field pl-11" value={searchQuery} onChange={(event) => setSearchQuery(event.target.value)} placeholder={activeRole === "traveller" ? "Search the traveller guide" : "Search content standards"} /></div>
        <div className="flex items-start gap-3 rounded-[var(--ny-radius-md)] border border-[var(--ny-border)] bg-[var(--ny-soft-green)] p-4 text-sm text-[var(--ny-text-secondary)]"><FiInfo size={18} className="mt-0.5 shrink-0 text-[var(--ny-green)]" aria-hidden="true" /><span>{activeRole === "traveller" ? "Start with a place, then follow the links to its recorded details." : "These principles help contributors keep travel information accurate and safe."}</span></div>
      </div>

      {filteredTopics.length > 0 ? <div className="grid gap-5 md:grid-cols-2">{filteredTopics.map((topic) => <motion.article key={topic.id} layout initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} className="ny-card flex h-full flex-col p-6"><div className="flex items-start justify-between gap-4"><span className="grid h-11 w-11 place-items-center rounded-[var(--ny-radius-md)] bg-[var(--ny-soft-green)]">{topic.icon}</span></div><h2 className="mt-5 text-xl font-bold">{topic.title}</h2><p className="mt-2 text-sm leading-6 text-[var(--ny-text-secondary)]">{topic.content}</p><ul className="mt-5 space-y-3 border-t border-[var(--ny-border)] pt-4">{topic.highlights.map((highlight) => <li key={highlight} className="flex gap-2 text-sm text-[var(--ny-text-secondary)]"><FiCheckCircle size={16} className="mt-0.5 shrink-0 text-[var(--ny-green)]" aria-hidden="true" />{highlight}</li>)}</ul></motion.article>)}</div> : <EmptyState title="No matching guidance" subtitle="Try a different search term or switch between traveller guidance and content standards." action={<button type="button" className="ny-btn ny-btn-secondary" onClick={() => setSearchQuery("")}>Clear search</button>} />}

      <section className="ny-panel overflow-hidden p-0"><div className="border-b border-[var(--ny-border)] p-6 sm:p-8"><p className="ny-kicker">What you may see</p><h2 className="mt-3">Honest data states</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-[var(--ny-text-secondary)]">A missing field is shown as unavailable. It is never replaced with a sample value just to make a page look complete.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-[var(--ny-soft-green)] text-xs uppercase tracking-wide text-[var(--ny-green)]"><tr><th className="px-5 py-3">Field or feature</th><th className="px-5 py-3">When it is not recorded</th><th className="px-5 py-3">What you see</th><th className="px-5 py-3">What you can do</th></tr></thead><tbody className="divide-y divide-[var(--ny-border)]"><tr><td className="px-5 py-4 font-semibold">Destination coordinates</td><td className="px-5 py-4 text-[var(--ny-text-secondary)]">No reliable point</td><td className="px-5 py-4"><span className="rounded-full bg-[var(--ny-soft-green)] px-2.5 py-1 text-xs font-semibold text-[var(--ny-green)]">Map location unavailable</span></td><td className="px-5 py-4"><Link to="/contact" className="font-semibold text-[var(--ny-green)] hover:underline">Report a correction</Link></td></tr><tr><td className="px-5 py-4 font-semibold">Cost or schedule</td><td className="px-5 py-4 text-[var(--ny-text-secondary)]">No current value</td><td className="px-5 py-4"><span className="rounded-full bg-[var(--ny-soft-gold)] px-2.5 py-1 text-xs font-semibold text-[var(--ny-warning)]">Information unavailable</span></td><td className="px-5 py-4">Check the linked provider or contact the operator.</td></tr><tr><td className="px-5 py-4 font-semibold">Emergency detail</td><td className="px-5 py-4 text-[var(--ny-text-secondary)]">No verified record</td><td className="px-5 py-4"><span className="rounded-full bg-[var(--ny-soft-red)] px-2.5 py-1 text-xs font-semibold text-[var(--ny-danger)]">Not listed</span></td><td className="px-5 py-4"><Link to="/emergency" className="font-semibold text-[var(--ny-green)] hover:underline">Open emergency page</Link></td></tr></tbody></table></div></section>

      <section className="ny-reading"><div className="mb-6 flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-[var(--ny-radius-md)] bg-[var(--ny-soft-green)] text-[var(--ny-green)]"><FiHelpCircle size={21} aria-hidden="true" /></span><div><h2>Frequently asked questions</h2><p className="text-sm text-[var(--ny-text-secondary)]">Short answers about records, corrections and planning.</p></div></div><div className="space-y-3">{faqs.map((faq, index) => { const open = expandedFaq === index; return <div key={faq.q} className="overflow-hidden rounded-[var(--ny-radius-md)] border border-[var(--ny-border)] bg-white"><button type="button" aria-expanded={open} onClick={() => setExpandedFaq(open ? null : index)} className="flex min-h-14 w-full items-center justify-between gap-4 px-4 py-4 text-left text-sm font-semibold text-[var(--ny-text)] hover:bg-[var(--ny-soft-green)]"><span>{faq.q}</span><FiChevronDown size={18} className={`shrink-0 text-[var(--ny-green)] transition-transform ${open ? "rotate-180" : ""}`} aria-hidden="true" /></button><AnimatePresence initial={false}>{open && <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: "auto", opacity: 1 }} exit={{ height: 0, opacity: 0 }} className="overflow-hidden"><p className="border-t border-[var(--ny-border)] px-4 py-4 text-sm leading-6 text-[var(--ny-text-secondary)]">{faq.a}</p></motion.div>}</AnimatePresence></div> })}</div></section>

      <div className="grid gap-5 sm:grid-cols-2"><section className="rounded-[var(--ny-radius-xl)] bg-[var(--ny-green-dark)] p-6 text-white sm:p-8"><p className="text-xs font-semibold uppercase tracking-wider text-[#BDEBD9]">Ready to explore?</p><h2 className="mt-3 !text-2xl !text-white">Start with a place that inspires you.</h2><p className="mt-2 text-sm leading-6 text-[#C7D9D2]">Browse the catalogue, compare practical details and build a route at your own pace.</p><Link to="/destinations" className="ny-btn ny-btn-accent mt-6">Explore destinations <FiArrowRight size={16} aria-hidden="true" /></Link></section><section className="ny-panel p-6 sm:p-8"><p className="ny-kicker">Need a human response?</p><h2 className="mt-3">Send a question or correction.</h2><p className="mt-2 text-sm leading-6 text-[var(--ny-text-secondary)]">Include the place name and the detail that needs attention so the review can be useful.</p><Link to="/contact" className="ny-btn ny-btn-secondary mt-6">Contact the team <FiArrowRight size={16} aria-hidden="true" /></Link></section></div>
    </div>
  )
}
