import { Link } from "react-router-dom"
import { FiArrowRight, FiCheckCircle, FiCompass, FiInfo, FiShield } from "react-icons/fi"
import Breadcrumbs from "../components/common/Breadcrumbs"
import PageHeader from "../components/common/PageHeader"
import EmptyState from "../components/common/EmptyState"
import CMSPageIntro from "../components/cms/CMSPageIntro"

export default function ThankYou() {
  let hasReceipt
  try { hasReceipt = typeof window !== "undefined" && Boolean(window.sessionStorage.getItem("nepal_yatra_submission_receipt")) } catch { hasReceipt = false }

  if (!hasReceipt) {
    return <div className="ny-page container-app mx-auto max-w-3xl space-y-6 py-8 sm:py-12"><Breadcrumbs items={[{ label: "Submission status", to: "/thank-you" }]} /><PageHeader title="Submission status" subtitle="Check whether a recent place or service submission has a receipt in this browser." icon={FiInfo} /><EmptyState icon={FiInfo} title="No submission receipt found" subtitle="This page does not have a receipt for a submission in this browser. If you just submitted a place or service, return to the form and check its confirmation message." action={<Link to="/contact" className="ny-btn ny-btn-primary">Contact the review team <FiArrowRight size={15} aria-hidden="true" /></Link>} secondaryAction={<Link to="/destinations" className="ny-btn ny-btn-secondary">Browse destinations</Link>} /></div>
  }

  return <div className="ny-page container-app mx-auto max-w-3xl space-y-6 py-8 sm:py-12"><Breadcrumbs items={[{ label: "Submission confirmed", to: "/thank-you" }]} /><div className="ny-card p-7 text-center sm:p-12"><span className="mx-auto grid h-20 w-20 place-items-center rounded-full bg-[var(--ny-soft-green)] text-[var(--ny-green)]"><FiCheckCircle size={42} aria-hidden="true" /></span><div className="mx-auto mt-6 max-w-2xl"><span className="ny-kicker">Submission received</span><CMSPageIntro pageKey="thank-you" /><PageHeader title="Thank you for contributing" subtitle="Your submission has been received and will be reviewed before it appears publicly." icon={FiCheckCircle} /><p className="mt-3 text-sm leading-6 text-[var(--ny-text-secondary)]">Review timing depends on the type of submission and the information provided. A submission is a request, not a guarantee that it will be published.</p></div><div className="mx-auto mt-6 flex max-w-lg items-start gap-3 rounded-[var(--ny-radius-md)] border border-[var(--ny-border)] bg-[var(--ny-soft-green)] p-4 text-left text-sm text-[var(--ny-text-secondary)]"><span className="mt-1 h-2 w-2 shrink-0 rounded-full bg-[var(--ny-green)]" aria-hidden="true" /><span>Keep any supporting files safe to share and avoid including private personal information.</span></div><div className="mt-8 grid gap-4 text-left sm:grid-cols-2"><article className="ny-panel p-5"><h2 className="flex items-center gap-2 text-base font-bold"><FiCompass className="text-[var(--ny-green)]" aria-hidden="true" />Explore destinations</h2><p className="mt-2 text-sm leading-6 text-[var(--ny-text-secondary)]">Browse recorded places across Nepal. Missing fields remain marked as unavailable.</p><Link to="/destinations" className="ny-btn ny-btn-link mt-3 px-0">Browse places <FiArrowRight size={15} aria-hidden="true" /></Link></article><article className="ny-panel p-5"><h2 className="flex items-center gap-2 text-base font-bold"><FiShield className="text-[var(--ny-danger)]" aria-hidden="true" />Safety information</h2><p className="mt-2 text-sm leading-6 text-[var(--ny-text-secondary)]">Open the emergency page to search directory records available for a destination or location.</p><Link to="/emergency" className="ny-btn ny-btn-link mt-3 px-0 text-[var(--ny-danger)]">Emergency page <FiArrowRight size={15} aria-hidden="true" /></Link></article></div><div className="mt-8 border-t border-[var(--ny-border)] pt-6"><Link to="/" className="ny-btn ny-btn-primary">Back to homepage <FiArrowRight size={16} aria-hidden="true" /></Link></div></div></div>
}
