# Generated by Django 6.0.7 on 2026-07-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='city_english',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='city_nepali',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
