# Generated by Django 6.0.7 on 2026-07-26 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0002_auto_20260724_0830'),
        ('tourist', '0002_destination_city_english_destination_city_nepali'),
        ('tourist', '0005_destination_district_destination_external_id_and_more'),
    ]

    operations = [
    ]
