# Generated by Django 6.0.7 on 2026-07-31 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0006_merge_20260726_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='hotels/covers/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='external_image_url',
            field=models.URLField(blank=True, help_text='Used instead of cover_image for externally-hosted photos (Unsplash/Wikimedia/etc.).'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='facilities',
            field=models.JSONField(blank=True, default=list, help_text='e.g. ["wifi", "breakfast", "parking", "pool", "ac"]'),
        ),
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('email', 'Email/Password'), ('google', 'Google'), ('github', 'GitHub')], default='email', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='managed_district',
            field=models.CharField(blank=True, help_text='For District Manager role: which district this user can manage. Blank = no district restriction.', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='provider_uid',
            field=models.CharField(blank=True, help_text='The account ID from Google/GitHub, used to re-link on subsequent OAuth logins.', max_length=255),
        ),
        migrations.AlterField(
            model_name='destination',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='approved', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('tourist', 'Tourist'), ('guide', 'Local Guide'), ('admin', 'Admin'), ('super_admin', 'Super Admin'), ('tourism_admin', 'Tourism Admin'), ('content_moderator', 'Content Moderator'), ('district_manager', 'District Manager'), ('hotel_manager', 'Hotel Manager'), ('staff', 'Staff'), ('tourist_police', 'Tourist Police'), ('police', 'Police'), ('hospital_staff', 'Hospital Staff'), ('rescue_team', 'Rescue Team'), ('emergency_operator', 'Emergency Operator')], default='tourist', max_length=20),
        ),
        migrations.CreateModel(
            name='DestinationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived'), ('edited', 'Edited')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('actor', models.ForeignKey(blank=True, help_text='Who performed this action (null for system-generated entries).', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to='tourist.destination')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
