# Generated by Django 5.0.6 on 2026-08-09 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0008_sharedtrip_locationping_trustedcontact_sosalert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='altitude',
            field=models.CharField(blank=True, help_text='Altitude in meters (e.g. 1,400m / 5,364m)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='best_time_to_visit',
            field=models.CharField(blank=True, help_text='e.g. Sep-Nov (Autumn) & Mar-May (Spring)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='history',
            field=models.TextField(blank=True, help_text='Historical, religious, or cultural background', null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='nearest_hospital_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='nearest_hotel_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='nearest_police_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
        migrations.CreateModel(
            name='TravelExpenseFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_name', models.CharField(max_length=200)),
                ('num_people', models.PositiveIntegerField(default=1)),
                ('num_days', models.PositiveIntegerField(default=1)),
                ('travel_mode', models.CharField(default='Tourist Bus', max_length=100)),
                ('accommodation_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('travel_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('entry_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('food_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('extra_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('route_details', models.TextField(blank=True, help_text='Practical route or transit details taken')),
                ('is_employee_verified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_feedbacks', to='tourist.destination')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelRiskFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_name', models.CharField(max_length=200)),
                ('became_sick', models.BooleanField(default=False)),
                ('sickness_type', models.CharField(blank=True, help_text='e.g. Altitude Sickness (AMS), Food Poisoning, Dehydration, Cold/Hypothermia', max_length=100)),
                ('misleading_activities', models.BooleanField(default=False)),
                ('misleading_details', models.TextField(blank=True)),
                ('accident_occurred', models.BooleanField(default=False)),
                ('accident_details', models.TextField(blank=True)),
                ('hazard_witnessed', models.CharField(blank=True, default='None', help_text='e.g. Landslide, Avalanche, Flood, Heavy Snow, Rockfall, None', max_length=100)),
                ('transport_accessibility_rating', models.PositiveSmallIntegerField(default=4, help_text='1 (Hard to reach / 4WD only) to 5 (Direct highway / flight)')),
                ('people_helpfulness_rating', models.PositiveSmallIntegerField(default=5, help_text='1 (Unhelpful) to 5 (Extremely friendly & helpful)')),
                ('greeting_behavior_rating', models.PositiveSmallIntegerField(default=5, help_text='1 (Hostile) to 5 (Very warm & respectful)')),
                ('overall_safety_rating', models.FloatField(default=9.0, help_text='Safety score from 1.0 to 10.0')),
                ('comments', models.TextField(blank=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_feedbacks', to='tourist.destination')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
