# Generated by Django 5.0.6 on 2026-08-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0009_destination_altitude_destination_best_time_to_visit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='municipality',
            field=models.CharField(blank=True, help_text='Metropolitan, Sub-Metropolitan, Municipality, or Rural Municipality (Gaunpalika)', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='ward_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Local Ward Number (e.g. 1 to 35)', null=True),
        ),
    ]
