# Generated by Django 6.0.7 on 2026-08-29 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0014_remove_culturalactivity_destination_and_more'),
        ('tourist', '0015_budget_date_default_fix'),
    ]

    operations = [
    ]
