"""Stop presenting generated postcards as photographs of a place.

What these rows are
-------------------
5,996 rows carry ``source_platform='postcard'`` and an external URL of the form
``/api/v1/postcard/hotel/<name>/<district>/id-<n>``. They are not photographs.
They are generated by an endpoint, they name no photographer, and 5,907
destinations have one as their only image.

The claim they make
-------------------
Every one of them is stored as ``verification_status='approved'`` with
``is_verified=True``, and six are flagged ``is_cover=True`` -- so they are the
picture of the place. Each also declares
``copyright_status='verified_reusable'``, which is a licence judgement about a
photograph by somebody who took one, applied to an image nobody took. Not one of
the 5,996 carries an attribution, because there is no author to attribute.

The published release happens to be unaffected: the scored media gate needs a
``destination_match_score`` and ``authenticity_score`` of at least 0.85, and
these rows have none. The running application is affected, and that is where a
traveller sees a generated postcard captioned as a hotel.

What this does
--------------
Marks every generated postcard as not a photograph: unverified, not approved,
never a cover, and no longer claiming reusable copyright. The rows are kept, so
nothing is lost and the decision is visible in the admin rather than hidden in a
deletion. ``--purge`` removes them instead, for a database that has finished
with them.

Nothing here touches a real photograph, however it was sourced. The selection is
on the postcard marker alone.

Usage
-----
    python manage.py quarantine_generated_postcards
    python manage.py quarantine_generated_postcards --apply
    python manage.py quarantine_generated_postcards --apply --purge
"""
from django.core.management.base import BaseCommand
from django.db import transaction

from tourist.models import DestinationImage

POSTCARD = "postcard"
#: The false claim: a licence judgement about somebody else's photograph.
FALSE_COPYRIGHT_CLAIM = "verified_reusable"


def postcards():
    return DestinationImage.objects.filter(
        source_platform__iexact=POSTCARD)


class Command(BaseCommand):
    help = "Mark generated postcards as not being photographs of a place."

    def add_arguments(self, parser):
        parser.add_argument("--apply", action="store_true",
                            help="Make the change. Without this nothing is written.")
        parser.add_argument("--purge", action="store_true",
                            help="Delete the rows instead of marking them.")
        parser.add_argument("--status", default=DestinationImage.ImageStatus.REJECTED,
                            help="Status to set when marking (default: rejected).")

    def handle(self, *args, **options):
        rows = postcards()
        total = rows.count()
        if not total:
            self.stdout.write(self.style.SUCCESS(
                "no generated postcards found"))
            return

        as_cover = rows.filter(is_cover=True).count()
        claiming = rows.filter(copyright_status=FALSE_COPYRIGHT_CLAIM).count()
        approved = rows.filter(
            verification_status=DestinationImage.ImageStatus.APPROVED).count()

        # A destination left with nothing at all once the postcards go is worth
        # saying out loud, so it is counted properly: destinations that have
        # images, and where every one of those images is a postcard.
        from django.db.models import Count, Q
        by_destination = DestinationImage.objects.values("destination_id").annotate(
            total=Count("id"),
            postcards=Count("id", filter=Q(source_platform__iexact=POSTCARD)),
        )
        sole_image = sum(1 for g in by_destination if g["total"] == g["postcards"])
        covered = sum(1 for g in by_destination if g["postcards"] > 0)

        self.stdout.write(f"generated postcards: {total}")
        self.stdout.write(f"  marked approved as a photograph : {approved}")
        self.stdout.write(f"  used as a destination cover     : {as_cover}")
        self.stdout.write(f"  claiming reusable copyright     : {claiming}")
        self.stdout.write(f"  destinations holding a postcard  : {covered}")
        self.stdout.write(f"  where it is the only image       : {sole_image}")
        if sole_image:
            self.stdout.write(self.style.WARNING(
                f"  those {sole_image} destinations will be left with no picture, which "
                f"is the honest state until fetch_destination_photos supplies a real one"))

        if options["purge"]:
            if not options["apply"]:
                self.stdout.write(self.style.WARNING(
                    "DRY RUN - pass --apply to delete them"))
                return
            with transaction.atomic():
                deleted, _ = postcards().delete()
            self.stdout.write(self.style.SUCCESS(f"deleted {deleted} postcard rows"))
            return

        if not options["apply"]:
            self.stdout.write(self.style.WARNING(
                "DRY RUN - pass --apply to mark them as not being photographs"))
            return

        with transaction.atomic():
            changed = rows.update(
                is_verified=False,
                is_cover=False,
                verification_status=options["status"],
            )
            # Only the false claim is corrected; rows that never made it are
            # left alone rather than having a value invented for them.
            rows.filter(copyright_status=FALSE_COPYRIGHT_CLAIM).update(
                copyright_status="generated_not_a_photograph")

        self.stdout.write(self.style.SUCCESS(
            f"marked {changed} postcards as not photographs "
            f"(status={options['status']}, verified=False, cover=False)"))
        self.stdout.write(
            "run `manage.py fetch_destination_photos --apply` to give those "
            "destinations a real, attributed photograph instead")
