/**
 * Real location icon assets used across the site (map pins, place chips,
 * nearby-service cards, pickers).
 *
 * Source: Twemoji — Mozilla's professional emoji artwork, licensed CC-BY
 * 4.0 (see docs/TWEMOJI_LICENSE.txt and the footer credit line). Each file
 * in public/icons/locations/ is a 72x72 PNG named after its place-type key;
 * public/icons/pins/ holds the pre-generated teardrop map pins with the
 * same icons embedded (generated by scripts/generate-location-pins.mjs —
 * they must be separate files because Leaflet loads pin SVGs through an
 * <img>, whose document context forbids external resource loads).
 */

const ICONS_BASE = "/icons/locations"
const PINS_BASE = "/icons/pins"

// Place-type keys that have a real icon asset (mirrors placeTypeIcons.js).
export const LOCATION_ICON_KEYS = [
  "waterfall", "lake", "hot_springs", "temple_hindu", "stupa", "monastery",
  "church", "heritage", "museum", "mountain", "viewpoint", "trekking",
  "hills", "cave", "park", "wildlife", "forest", "river", "water_sports",
  "camping", "food", "tea_coffee", "orchard", "hotel", "village", "festival",
  "market", "shopping", "snow", "sunset", "rain_water", "walking", "family",
  "celebration", "hospital", "pharmacy", "police", "ambulance",
  "pin", "attraction", "compass",
  "money",
]

export const LOCATION_ICON_URL = (key) => `${ICONS_BASE}/${key}.png`
export const LOCATION_PIN_URL = (key) => `${PINS_BASE}/pin-${key}.svg`
