/**
 * Registry for the site's real UI icon set (public/icons/ui/).
 *
 * These are original duotone vector assets generated by
 * `node scripts/generate-ui-icons.mjs` — consistent style, no third-party
 * license required. They cover every surface the owner asked for real
 * icons on: sidebar, directions (turn-by-turn maneuvers), distance,
 * route and navigation.
 */

export const UI_ICON = (name) => `/icons/ui/${name}.svg`

/**
 * Backend maneuver keys → turn icon file.
 * Sources: steps[].turn (structured), steps[].maneuver (graph fallback),
 * or the instruction text (legacy/OSRM steps) — see maneuverFromStep().
 */
export const MANEUVER_ICON = {
  start: "turn-start",
  depart: "turn-start",
  straight: "turn-straight",
  continue: "turn-straight",
  left: "turn-left",
  "turn-left": "turn-left",
  "turn-slight-left": "turn-left",
  right: "turn-right",
  "turn-right": "turn-right",
  "turn-slight-right": "turn-right",
  sharp_left: "turn-sharp-left",
  "turn-sharp-left": "turn-sharp-left",
  sharp_right: "turn-sharp-right",
  "turn-sharp-right": "turn-sharp-right",
  uturn: "turn-uturn",
  arrive: "turn-arrive",
}

export const MANEUVER_LABEL = {
  "turn-start": "Depart",
  "turn-straight": "Continue straight",
  "turn-left": "Turn left",
  "turn-right": "Turn right",
  "turn-sharp-left": "Sharp left",
  "turn-sharp-right": "Sharp right",
  "turn-uturn": "U-turn",
  "turn-arrive": "Arrive",
}

/**
 * Resolve a step to its maneuver icon, trying in order:
 *  1. step.turn        — structured key (build_maneuvers / fallback provider)
 *  2. step.maneuver    — provider-style key ("turn-left", "continue", …)
 *  3. instruction text — legacy cached routes / OSRM steps
 */
export function maneuverFromStep(step = {}) {
  for (const key of [step.turn, step.maneuver]) {
    if (key && MANEUVER_ICON[key]) return MANEUVER_ICON[key]
  }
  const t = (step.instruction || "").toLowerCase()
  if (!t) return "turn-straight"
  if (/u-?turn|turn around|double back/.test(t)) return "turn-uturn"
  if (/arrive/.test(t)) return "turn-arrive"
  if (/sharp left/.test(t)) return "turn-sharp-left"
  if (/sharp right/.test(t)) return "turn-sharp-right"
  if (/(slight )?left/.test(t) && /turn|bear/.test(t)) return "turn-left"
  if (/(slight )?right/.test(t) && /turn|bear/.test(t)) return "turn-right"
  return "turn-straight"
}

/** Real turn-by-turn maneuver icon (left/right/straight/sharp/U-turn/arrive). */
export function TurnIcon({ step = {}, size = 28, className = "" }) {
  const name = maneuverFromStep(step)
  return (
    <img
      src={UI_ICON(name)}
      alt={MANEUVER_LABEL[name]}
      width={size}
      height={size}
      className={className}
      draggable={false}
    />
  )
}
