#!/bin/bash
# Setup Render environment variables
# Usage: source scripts/setup_render_env.sh

echo "=========================================="
echo "  Render Environment Setup"
echo "=========================================="

# Required variables
export DEBUG=False
export ALLOWED_HOSTS="*"
export DATABASE_SSL_REQUIRE=true

# Optional variables (set these in Render dashboard)
# export DATABASE_URL="postgresql://user:pass@host:5432/dbname"
# export SECRET_KEY="your-secret-key"
# export PUBLIC_SITE_URL="https://your-app.onrender.com"
# export VITE_SITE_URL="https://your-app.onrender.com"
# export CSRF_TRUSTED_ORIGINS="https://your-app.onrender.com"
# export CORS_ALLOWED_ORIGINS="https://your-app.onrender.com"
# export IMAGE_BASE_URL="https://your-app.onrender.com"
# export ML_SERVICE_URL="http://localhost:8001"

echo "Environment variables set:"
echo "  DEBUG=$DEBUG"
echo "  ALLOWED_HOSTS=$ALLOWED_HOSTS"
echo "  DATABASE_SSL_REQUIRE=$DATABASE_SSL_REQUIRE"
echo ""
echo "Make sure to set these in your Render dashboard:"
echo "  - DATABASE_URL (from your PostgreSQL database)"
echo "  - SECRET_KEY (auto-generated by Render)"
echo "  - PUBLIC_SITE_URL"
echo "  - VITE_SITE_URL"
echo "  - CSRF_TRUSTED_ORIGINS"
echo "  - CORS_ALLOWED_ORIGINS"
echo "  - IMAGE_BASE_URL"
echo ""
