import { useState } from "react"
import { Link, NavLink, Outlet } from "react-router-dom"
import { FiActivity, FiChevronDown, FiChevronRight, FiDatabase, FiHome, FiImage, FiLogOut, FiMenu, FiShield, FiUsers } from "react-icons/fi"
import useAuth from "../../hooks/useAuth"
import AdminGlobalSearch from "./AdminGlobalSearch"

const groups=[{label:"Control",items:[["/admin","Overview",FiHome],["/admin/diagnostics","Audit & Diagnostics",FiActivity]]},{label:"Management",items:[["/admin","Database & Content",FiDatabase],["/admin/hotel-assignments","Hotels & Assignments",FiImage],["/admin/tasks","Staff Tasks",FiUsers]]}]
export default function AdminLayout(){
 const[open,setOpen]=useState(false);const[expanded,setExpanded]=useState({Control:true,Management:true});const{user,logout}=useAuth()
 const closeMobile=()=>{if(typeof window!=="undefined"&&window.innerWidth<1024)setOpen(false)}
 return <div className="min-h-screen bg-slate-950 text-slate-100"><a href="#admin-main" className="admin-skip-link">Skip to admin content</a><header className="fixed inset-x-0 top-0 z-50 flex h-16 items-center gap-3 border-b border-slate-800 bg-slate-950 px-3 sm:px-5"><button onClick={()=>setOpen(value=>!value)} className="admin-icon-button" aria-label={open?"Close admin navigation":"Open admin navigation"} aria-expanded={open} aria-controls="admin-navigation"><FiMenu/></button><div className="hidden whitespace-nowrap font-black md:block"><span className="text-amber-400">Digital Nepal</span> Admin Control Center</div><AdminGlobalSearch/><div className="ml-auto flex items-center gap-2 text-xs"><span className="hidden text-slate-400 sm:inline">{user?.email}</span><Link to="/" className="min-h-10 rounded-lg bg-emerald-700 px-3 py-2">User Dashboard</Link><button onClick={logout} className="admin-icon-button !bg-rose-800" aria-label="Log out"><FiLogOut/></button></div></header><aside id="admin-navigation" aria-label="Admin navigation" className={`fixed bottom-0 top-16 z-40 w-72 max-w-[88vw] overflow-y-auto border-r border-slate-800 bg-slate-950 transition-transform ${open?"translate-x-0":"-translate-x-full"} lg:translate-x-0`}><nav className="p-4"><div className="mb-5 rounded-xl bg-slate-900 p-3"><FiShield className="inline text-amber-400"/> <b>Administrator</b><p className="mt-1 text-xs text-slate-500">Management workspace</p></div>{groups.map(group=><section key={group.label} className="mb-4"><button onClick={()=>setExpanded(value=>({...value,[group.label]:!value[group.label]}))} className="flex min-h-10 w-full items-center justify-between py-2 text-xs font-black uppercase tracking-widest text-slate-500" aria-expanded={expanded[group.label]}>{group.label}{expanded[group.label]?<FiChevronDown/>:<FiChevronRight/>}</button>{expanded[group.label]&&group.items.map(([to,label,Icon],index)=><NavLink end={to==="/admin"&&index===0} key={`${to}-${label}`} to={to} onClick={closeMobile} className={({isActive})=>`mb-1 flex min-h-11 items-center gap-3 rounded-xl px-3 py-2.5 text-sm ${isActive?"bg-amber-400 font-black text-slate-950":"text-slate-300 hover:bg-slate-800"}`}><Icon aria-hidden="true"/>{label}</NavLink>)}</section>)}</nav></aside>{open&&<button onClick={()=>setOpen(false)} className="fixed inset-0 top-16 z-30 bg-black/60 lg:hidden" aria-label="Close admin navigation overlay"/>}<main id="admin-main" tabIndex="-1" className="min-h-screen pt-16 lg:pl-72"><div className="p-3 sm:p-6"><Outlet/></div></main></div>
}
