import { useState } from "react"
import { Link, NavLink, Outlet } from "react-router-dom"
import { FiActivity, FiChevronDown, FiChevronRight, FiDatabase, FiHome, FiImage, FiLogOut, FiMenu, FiSettings, FiShield, FiUsers, FiX } from "react-icons/fi"
import useAuth from "../../hooks/useAuth"

const groups = [
  {label:"Control",items:[[/admin$/,"/admin","Overview",FiHome],[/diagnostics/,"/admin/diagnostics","Audit & Diagnostics",FiActivity]]},
  {label:"Management",items:[[/admin$/,"/admin","Database & Content",FiDatabase],[/hotel-assignments/,"/admin/hotel-assignments","Hotels & Assignments",FiImage],[/tasks/,"/admin/tasks","Staff Tasks",FiUsers]]},
]
export default function AdminLayout(){const[open,setOpen]=useState(true),[expanded,setExpanded]=useState({Control:true,Management:true});const{user,logout}=useAuth();return <div className="min-h-screen bg-slate-950 text-slate-100"><header className="fixed inset-x-0 top-0 z-50 h-16 bg-slate-950 border-b border-slate-800 flex items-center px-3 sm:px-5 gap-3"><button onClick={()=>setOpen(!open)} className="p-2 rounded-lg bg-slate-800"><FiMenu/></button><div className="font-black whitespace-nowrap"><span className="text-amber-400">Digital Nepal</span> Admin Control Center</div><div className="ml-auto flex items-center gap-2 text-xs"><span className="hidden sm:inline text-slate-400">{user?.email}</span><Link to="/" className="px-3 py-2 rounded-lg bg-emerald-700">View User Dashboard</Link><button onClick={logout} className="p-2 rounded-lg bg-rose-800" title="Logout"><FiLogOut/></button></div></header><aside className={`fixed top-16 bottom-0 z-40 w-72 max-w-[88vw] bg-slate-950 border-r border-slate-800 transition-transform ${open?'translate-x-0':'-translate-x-full'} lg:translate-x-0 overflow-y-auto`}><div className="p-4"><div className="p-3 rounded-xl bg-slate-900 mb-5"><FiShield className="inline text-amber-400"/> <b>Administrator</b><p className="text-xs text-slate-500 mt-1">Management workspace</p></div>{groups.map(group=><div key={group.label} className="mb-4"><button onClick={()=>setExpanded({...expanded,[group.label]:!expanded[group.label]})} className="w-full flex justify-between text-xs uppercase tracking-widest text-slate-500 font-black py-2">{group.label}{expanded[group.label]?<FiChevronDown/>:<FiChevronRight/>}</button>{expanded[group.label]&&group.items.map(([,to,label,Icon])=><NavLink end key={`${to}-${label}`} to={to} onClick={()=>innerWidth<1024&&setOpen(false)} className={({isActive})=>`flex items-center gap-3 px-3 py-2.5 rounded-xl text-sm mb-1 ${isActive?'bg-amber-400 text-slate-950 font-black':'text-slate-300 hover:bg-slate-800'}`}><Icon/>{label}</NavLink>)}</div>)}</div></aside>{open&&<button onClick={()=>setOpen(false)} className="fixed inset-0 top-16 bg-black/60 z-30 lg:hidden" aria-label="Close admin navigation"/>}<main className="pt-16 lg:pl-72 min-h-screen"><div className="p-3 sm:p-6"><Outlet/></div></main></div>}
