import { useEffect, useState } from "react"
import { FiDatabase, FiExternalLink, FiImage, FiSave, FiSearch, FiUpload, FiX } from "react-icons/fi"
import adminApi from "../../api/adminApi"
import useToast from "../../hooks/useToast"

const GROUPS = [
  ["Core", [["destinations","Destinations"],["destination_features","Destination Features"],["destination_images","Destination Images"],["destination_translations","Translations"],["categories","Categories"],["languages","Languages"]]],
  ["Hotels & Bookings", [["hotels","Hotels"],["bookings","Bookings"],["hotel_reviews","Hotel Reviews"]]],
  ["Users", [["reviews","Destination Reviews"],["ratings","Ratings"],["favorites","Favorites"],["visit_history","Visit History"],["family_links","Family Links"],["email_tokens","Email Tokens"]]],
  ["Safety & Services", [["alerts","Alerts"],["current_hazards","Current Hazards"],["emergency_contacts","Emergency Contacts"],["osm_services","OSM Essential Services"],["osm_places","OSM Tourism Places"]]],
  ["Finance & Feedback", [["budgets","Budgets"],["feedback","User Feedback"],["feedback_evidence","Feedback Evidence"]]],
  ["Audit", [["audit_logs","Audit Log Entries"],["error_events","Error Events"]]],
]

export default function DataExplorerPanel() {
  const { showToast } = useToast()
  const [resource,setResource]=useState("destinations"), [query,setQuery]=useState(""), [data,setData]=useState({results:[],count:0}), [loading,setLoading]=useState(false)
  const [detail,setDetail]=useState(null), [edit,setEdit]=useState({}), [upload,setUpload]=useState(null)
  const load=()=>{setLoading(true);adminApi.exploreData({resource,q:query}).then(({data})=>setData(data)).catch(()=>setData({results:[],count:0})).finally(()=>setLoading(false))}
  useEffect(()=>{load();setDetail(null)},[resource]) // eslint-disable-line react-hooks/exhaustive-deps
  const openDestination=async(id)=>{if(resource!=="destinations")return;try{const{data}=await adminApi.getAdminDestination(id);setDetail(data);setEdit({name:data.name||"",short_description:data.short_description||"",description:data.description||"",city:data.city||"",district:data.district||"",province:data.province||"",latitude:data.latitude??"",longitude:data.longitude??""})}catch{showToast("Could not load destination details","error")}}
  const save=async()=>{try{await adminApi.updateAdminDestination(detail.id,edit);showToast("Database and dataset/data.json updated","success");await openDestination(detail.id);load()}catch(e){showToast(e.response?.data?.detail||"Update failed","error")}}
  const uploadImage=async()=>{if(!upload||!detail)return;const form=new FormData();form.append("image",upload);form.append("caption",`${detail.name} admin upload`);form.append("is_cover","true");try{await adminApi.addAdminDestinationImage(detail.id,form);showToast("Image uploaded and set as cover","success");setUpload(null);openDestination(detail.id)}catch(e){showToast(e.response?.data?.detail||"Upload failed","error")}}
  return <div className="grid lg:grid-cols-[270px_1fr] gap-5">
    <aside className="rounded-2xl bg-slate-950 border border-slate-700 p-4 max-h-[75vh] overflow-y-auto">{GROUPS.map(([group,items])=><div key={group} className="mb-4"><h3 className="text-[10px] uppercase tracking-widest text-slate-500 font-black mb-2">{group}</h3>{items.map(([id,label])=><button key={id} onClick={()=>setResource(id)} className={`block w-full text-left px-3 py-2 rounded-lg text-xs mb-1 ${resource===id?'bg-amber-400 text-slate-950 font-black':'text-slate-300 hover:bg-slate-800'}`}>{label}</button>)}</div>)}</aside>
    <section className="rounded-2xl bg-slate-950 border border-slate-700 p-5 overflow-hidden"><div className="flex flex-wrap gap-2 justify-between mb-4"><div><h2 className="text-xl text-white font-black flex items-center gap-2"><FiDatabase/>Database Explorer</h2><p className="text-xs text-slate-400">{data.count} records · click destinations for details</p></div><div className="flex"><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()} className="rounded-l-xl bg-slate-800 border border-slate-600 px-3 text-sm text-white" placeholder="Search records…"/><button onClick={load} className="rounded-r-xl bg-amber-400 px-4"><FiSearch/></button></div></div>
      <a href="/django-admin/" target="_blank" rel="noreferrer" className="text-xs text-amber-300 inline-flex items-center gap-1 mb-3">Open full add/edit/delete administration <FiExternalLink/></a>
      <div className="overflow-auto max-h-[45vh]"><table className="min-w-full text-xs"><thead className="sticky top-0 bg-slate-900"><tr>{data.columns?.map(c=><th key={c} className="text-left text-slate-400 px-3 py-2 whitespace-nowrap">{c}</th>)}</tr></thead><tbody>{loading?<tr><td className="text-slate-400 p-5">Loading…</td></tr>:data.results.map((row,i)=><tr onClick={()=>openDestination(row.id)} key={row.id||i} className={`border-t border-slate-800 ${resource==='destinations'?'cursor-pointer hover:bg-slate-800':''}`}>{data.columns?.map(c=><td key={c} className="text-slate-300 px-3 py-2 max-w-72 truncate">{row[c]===null?'—':String(row[c]??'')}</td>)}</tr>)}</tbody></table></div>
      {detail&&<div className="mt-5 rounded-2xl bg-slate-900 border border-amber-500/30 p-5"><div className="flex justify-between"><h3 className="text-white text-lg font-black">Edit {detail.name}</h3><button onClick={()=>setDetail(null)} className="text-slate-400"><FiX/></button></div><div className="grid md:grid-cols-2 gap-3 mt-4">{["name","city","district","province","latitude","longitude","short_description"].map(key=><label key={key} className="text-[10px] uppercase text-slate-400 font-bold">{key.replace('_',' ')}<input value={edit[key]??""} onChange={e=>setEdit({...edit,[key]:e.target.value})} className="input-field mt-1"/></label>)}<label className="md:col-span-2 text-[10px] uppercase text-slate-400 font-bold">Description<textarea rows="4" value={edit.description??""} onChange={e=>setEdit({...edit,description:e.target.value})} className="input-field mt-1"/></label></div><div className="flex flex-wrap gap-3 mt-4"><button onClick={save} className="bg-emerald-600 text-white rounded-xl px-4 py-2 text-xs font-black"><FiSave className="inline"/> Save DB + JSON</button><input type="file" accept="image/*" onChange={e=>setUpload(e.target.files?.[0]||null)} className="text-xs text-slate-300"/><button disabled={!upload} onClick={uploadImage} className="bg-blue-600 disabled:opacity-40 text-white rounded-xl px-4 py-2 text-xs font-black"><FiUpload className="inline"/> Upload cover</button></div><div className="grid grid-cols-2 md:grid-cols-5 gap-2 mt-4">{detail.gallery?.map(image=><div key={image.id} className="rounded-lg overflow-hidden bg-slate-800"><img src={image.url} alt={image.caption} className="h-24 w-full object-cover"/><p className="text-[9px] text-slate-300 p-1 truncate">{image.caption||`Image #${image.id}`}</p></div>)}</div></div>}
    </section>
  </div>
}
