import { useEffect, useState } from "react"
import { FiEdit3, FiImage, FiRefreshCw, FiSearch, FiUpload } from "react-icons/fi"
import adminApi from "../../api/adminApi"
import HotelMedia from "../cards/HotelMedia"
import useToast from "../../hooks/useToast"

export default function HotelBookingPanel(){
  const{showToast}=useToast();const[tab,setTab]=useState("hotels");const[rows,setRows]=useState([]);const[q,setQ]=useState("");const[loading,setLoading]=useState(false);const[page,setPage]=useState(1);const[pages,setPages]=useState(1);const[count,setCount]=useState(0)
  const load=async(targetPage=page)=>{setLoading(true);try{const response=tab==="hotels"?await adminApi.getHotels({search:q,page:targetPage,page_size:24}):await adminApi.getBookings({search:q,page:targetPage,page_size:24});const payload=response.data;setRows(payload.results||payload||[]);setCount(payload.count??(payload.results||payload||[]).length);setPages(payload.total_pages||(payload.count?Math.max(1,Math.ceil(payload.count/24)):1));setPage(targetPage)}catch(error){showToast(error.response?.data?.detail||"Could not load records","error")}finally{setLoading(false)}}
  useEffect(()=>{setPage(1);load(1)},[tab])
  const status=async(row,value)=>{try{await adminApi.updateBooking(row.id,{status:value});showToast("Booking updated","success");load()}catch(error){showToast(error.response?.data?.detail||"Update failed","error")}}
  const externalImage=async row=>{const value=window.prompt("Verified hotel image URL (HTTPS). Leave blank to use the labelled destination-area fallback.",row.external_image_url||"");if(value===null)return;try{await adminApi.updateHotel(row.id,{external_image_url:value.trim()});showToast("Hotel image updated","success");load()}catch(error){showToast(error.response?.data?.external_image_url?.[0]||"Image URL was rejected","error")}}
  const uploadImage=async(row,file)=>{if(!file)return;const body=new FormData();body.append("cover_image",file);try{await adminApi.uploadHotelImage(row.id,body);showToast("Hotel cover uploaded","success");load()}catch(error){showToast(error.response?.data?.cover_image?.[0]||"Hotel image upload failed","error")}}
  return <div className="rounded-2xl border border-emerald-200 bg-white p-5 text-slate-900"><div className="mb-4 flex flex-wrap gap-2">{["hotels","bookings"].map(item=><button key={item} onClick={()=>setTab(item)} className={`rounded-xl px-4 py-2 capitalize ${tab===item?"bg-emerald-700 text-white font-black":"bg-emerald-50 text-emerald-900"}`}>{item}</button>)}<label className="relative ml-auto"><FiSearch className="absolute left-3 top-3 text-slate-500"/><input value={q} onChange={e=>setQ(e.target.value)} className="input-field pl-9" placeholder="Search all records…"/></label><button onClick={()=>load(1)} className="rounded-xl bg-emerald-700 px-4 text-white"><FiRefreshCw className={loading?"animate-spin":""}/></button></div><p className="mb-3 text-xs text-slate-500">{count.toLocaleString()} {tab} · page {page} of {pages}. Hotel-specific uploads are shown first; destination context is clearly labelled.</p><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{rows.map(row=><article key={row.id} className="overflow-hidden rounded-xl border border-emerald-100 bg-emerald-50 text-xs text-slate-600">{tab==="hotels"&&<HotelMedia hotel={row} className="h-40 w-full"/>}<div className="flex justify-between gap-3 p-3"><div><b className="text-emerald-950">{row.name||row.hotel_name||`Booking #${row.id}`}</b><p>{row.destination_name||row.address||row.user_email}</p>{tab==="hotels"&&!row.image_is_hotel_specific&&<p className="mt-1 text-amber-700"><FiImage className="inline"/> Destination-area context</p>}</div>{tab==="bookings"?<select value={row.status} onChange={e=>status(row,e.target.value)} className="input-field w-32"><option>pending</option><option>confirmed</option><option>cancelled</option><option>completed</option></select>:<div className="flex gap-1"><label className="cursor-pointer self-start rounded-lg bg-emerald-700 p-2 text-white" title="Upload hotel cover"><FiUpload/><input type="file" accept="image/jpeg,image/png,image/webp" className="hidden" onChange={e=>uploadImage(row,e.target.files?.[0])}/></label><button onClick={()=>externalImage(row)} className="self-start rounded-lg bg-sky-700 p-2 text-white" title="Set external image"><FiEdit3/></button></div>}</div></article>)}</div>{!loading&&!rows.length&&<p className="py-10 text-center text-slate-500">No records found.</p>}<div className="mt-4 flex justify-between rounded-xl border border-emerald-100 p-3"><button disabled={page<=1||loading} onClick={()=>load(page-1)}>Previous</button><span>Page {page} / {pages}</span><button disabled={page>=pages||loading} onClick={()=>load(page+1)}>Next</button></div></div>
}
