import { useEffect, useState } from "react"
import { FiEdit3, FiImage, FiRefreshCw, FiSearch } from "react-icons/fi"
import adminApi from "../../api/adminApi"
import HotelMedia from "../cards/HotelMedia"
import useToast from "../../hooks/useToast"

export default function HotelBookingPanel(){
  const{showToast}=useToast();const[tab,setTab]=useState("hotels");const[rows,setRows]=useState([]);const[q,setQ]=useState("");const[loading,setLoading]=useState(false)
  const load=async()=>{setLoading(true);try{const response=tab==="hotels"?await adminApi.getHotels({search:q}):await adminApi.getBookings({search:q});setRows(response.data.results||response.data||[])}catch(error){showToast(error.response?.data?.detail||"Could not load records","error")}finally{setLoading(false)}}
  useEffect(()=>{load()},[tab])
  const status=async(row,value)=>{try{await adminApi.updateBooking(row.id,{status:value});showToast("Booking updated","success");load()}catch(error){showToast(error.response?.data?.detail||"Update failed","error")}}
  const image=async row=>{const value=window.prompt("Verified hotel image URL (HTTPS). Leave blank to remove the hotel-specific image and use the labelled destination-area fallback.",row.external_image_url||"");if(value===null)return;try{await adminApi.updateHotel(row.id,{external_image_url:value.trim()});showToast("Hotel image updated","success");load()}catch(error){showToast(error.response?.data?.external_image_url?.[0]||"Image URL was rejected","error")}}
  return <div className="rounded-2xl bg-slate-950 border border-slate-700 p-5 text-slate-100"><div className="flex flex-wrap gap-2 mb-4">{["hotels","bookings"].map(item=><button key={item} onClick={()=>setTab(item)} className={`px-4 py-2 rounded-xl capitalize ${tab===item?"bg-amber-400 text-black font-black":"bg-slate-800"}`}>{item}</button>)}<label className="relative ml-auto"><FiSearch className="absolute left-3 top-3 text-slate-500"/><input value={q} onChange={e=>setQ(e.target.value)} className="input-field pl-9" placeholder="Search…"/></label><button onClick={load} className="bg-emerald-700 px-4 rounded-xl"><FiRefreshCw className={loading?"animate-spin":""}/></button></div><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-3">{rows.map(row=><article key={row.id} className="bg-slate-900 rounded-xl overflow-hidden text-xs text-slate-300">{tab==="hotels"&&<HotelMedia hotel={row} className="h-36 w-full"/>}<div className="p-3 flex justify-between gap-3"><div><b className="text-white">{row.name||row.hotel_name||`Booking #${row.id}`}</b><p>{row.destination_name||row.address||row.user_email}</p>{tab==="hotels"&&!row.image_is_hotel_specific&&<p className="text-amber-300 mt-1"><FiImage className="inline"/> Context image shown until hotel media is added</p>}</div>{tab==="bookings"?<select value={row.status} onChange={e=>status(row,e.target.value)} className="input-field w-32"><option>pending</option><option>confirmed</option><option>cancelled</option><option>completed</option></select>:<button onClick={()=>image(row)} className="self-start p-2 bg-sky-700 rounded-lg" title="Edit hotel image"><FiEdit3/></button>}</div></article>)}</div>{!loading&&!rows.length&&<p className="text-center text-slate-500 py-10">No records found.</p>}</div>
}
