import { useEffect, useState } from "react"
import { Link } from "react-router-dom"
import { FiCheck, FiDatabase, FiMapPin, FiPlus, FiRefreshCw, FiX } from "react-icons/fi"
import adminApi from "../../api/adminApi"
import useToast from "../../hooks/useToast"
import SafetyAdvisoryAdminPanel from "./SafetyAdvisoryAdminPanel"

export default function InfrastructureModerationPanel() {
  const { showToast } = useToast()
  const [items, setItems] = useState([])
  const [loading, setLoading] = useState(true)
  const [pipeline, setPipeline] = useState(false)
  const load = () => { setLoading(true); adminApi.getInfrastructureSubmissions({ status: "pending" }).then(({data}) => setItems(data)).catch(() => setItems([])).finally(() => setLoading(false)) }
  useEffect(load, []) // eslint-disable-line react-hooks/exhaustive-deps
  const action = async (id, type) => { try { await adminApi.reviewInfrastructureSubmission(id, { action: type }); showToast(type === "approve" ? "Approved, published to database, and synchronized to CSV." : "Submission rejected.", "success"); load() } catch (e) { showToast(e.response?.data?.detail || "Review failed", "error") } }
  const runPipeline = async (train) => { setPipeline(true); try { const {data}=await adminApi.runMLDataPipeline({ train, models:["budget","risk","recommendation"] }); showToast(train ? "ML pipeline finished. Review individual model results." : `CSV export complete: ${data.exported.budget} budget, ${data.exported.risk} risk rows.`, "success") } catch(e) { showToast(e.response?.data?.detail || "Pipeline failed", "error") } finally {setPipeline(false)} }
  return <div className="space-y-5">
    <div className="rounded-2xl border border-emerald-500/20 bg-slate-900/70 p-5 flex flex-wrap justify-between gap-3"><div><h2 className="font-black text-white text-xl">Community Infrastructure Approval</h2><p className="text-xs text-slate-400">Approve hotels, hospitals, police, banks, fire, ambulance and destinations. Approval publishes DB records, media, route details and CSV rows.</p></div><div className="flex gap-2"><Link to="/submit-service" className="rounded-xl bg-emerald-700 text-white px-4 py-2 text-xs font-black"><FiPlus className="inline" /> Add verified service</Link><button disabled={pipeline} onClick={()=>runPipeline(false)} className="rounded-xl bg-blue-700 text-white px-4 py-2 text-xs font-black"><FiDatabase className="inline" /> Export verified ML data</button><button disabled={pipeline} onClick={()=>runPipeline(true)} className="rounded-xl bg-amber-400 text-slate-950 px-4 py-2 text-xs font-black"><FiRefreshCw className={`inline ${pipeline?'animate-spin':''}`} /> Train approved data</button></div></div>
    <SafetyAdvisoryAdminPanel />
    {loading ? <p className="text-slate-400">Loading submissions…</p> : items.length ? <div className="grid lg:grid-cols-2 gap-4">{items.map(item => <article key={item.id} className="rounded-2xl bg-slate-900 border border-slate-700 p-5 space-y-3"><div className="flex justify-between"><span className="rounded-full bg-emerald-900 text-emerald-200 px-3 py-1 text-xs font-black uppercase">{item.place_type}</span><span className="text-xs text-slate-400">#{item.id}</span></div><div><h3 className="font-black text-white">{item.name}</h3><p className="text-xs text-slate-400"><FiMapPin className="inline" /> {item.municipality}, Ward {item.ward_number || "?"}, {item.district}, {item.province}</p></div><p className="text-sm text-slate-300">{item.description}</p><div className="grid grid-cols-2 text-xs text-slate-400"><span>GPS: {item.latitude}, {item.longitude}</span><span>Phone: {item.phone || "not provided"}</span><span>Route: {item.transport_mode || "—"}</span><span>Time: {item.travel_time_minutes ? `${item.travel_time_minutes} min` : "—"}</span></div>{item.image_url && <img src={item.image_url} alt={item.name} className="h-40 w-full object-cover rounded-xl" />}<div className="flex gap-2"><button onClick={()=>action(item.id,"approve")} className="flex-1 rounded-xl bg-emerald-600 text-white py-2 text-xs font-black"><FiCheck className="inline" /> Approve & publish</button><button onClick={()=>action(item.id,"reject")} className="rounded-xl bg-rose-700 text-white px-4 py-2 text-xs font-black"><FiX className="inline" /> Reject</button></div></article>)}</div> : <p className="rounded-2xl border border-slate-700 p-8 text-center text-slate-400">No pending infrastructure submissions.</p>}
  </div>
}
