# Generated by Django 6.0.7 on 2026-07-24 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('tourist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='admintask',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admintask',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admintask',
            name='related_hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_tasks', to='tourist.hotel'),
        ),
        migrations.AddField(
            model_name='hotelassignment',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_hotels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hotelassignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_assignments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hotelassignment',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='tourist.hotel'),
        ),
        migrations.AlterUniqueTogether(
            name='hotelassignment',
            unique_together={('hotel', 'admin')},
        ),
    ]
