"""Add famous places for all 77 districts (from the 77-district tourism list)
as real destinations with category + coordinates. Skips existing names/slugs."""
import os

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "Tourism.settings")

import django  # noqa: E402

django.setup()

from tourist.models import Destination, Category  # noqa: E402

cats = {c.slug: c for c in Category.objects.all()}

# (name, category_slug, district, province, city, lat, lon, short)
PLACES = [
    # ---------- Koshi ----------
    ("Olangchung Gola", "villages", "Taplejung", "Koshi", "Olangchung Gola", 27.62, 87.82, "High Himalayan trading village near the Tibet border in Taplejung."),
    ("Ghunsa Village", "villages", "Taplejung", "Koshi", "Ghunsa", 27.65, 87.87, "Sherpa village on the Kanchenjunga trekking route."),
    ("Sandakpur", "viewpoints", "Ilam", "Koshi", "Sandakpur", 26.99, 87.98, "Viewpoint on the Ilam ridge with sunrise over Kanchenjunga."),
    ("Fikkal Bazaar", "cities", "Ilam", "Koshi", "Fikkal", 26.75, 87.90, "Tea-country bazaar town of Ilam district."),
    ("Mai Pokhari Lake", "lakes", "Ilam", "Koshi", "Mai Pokhari", 26.98, 87.78, "Sacred lake and wetland in Ilam, a Ramsar site."),
    ("Kakarbhitta", "cities", "Jhapa", "Koshi", "Kakarbhitta", 26.66, 88.15, "Eastern border town of Nepal on the India trade route."),
    ("Arjundhara Temple", "temples", "Jhapa", "Koshi", "Arjundhara", 26.68, 87.99, "Temple of Arjun of the Mahabharata in Jhapa."),
    ("Jalthal Forest", "forests", "Jhapa", "Koshi", "Jalthal", 26.63, 87.93, "Remnant tropical forest near Birtamod, Jhapa."),
    ("Kichakbadh", "pilgrimage", "Jhapa", "Koshi", "Kichakbadh", 26.53, 87.83, "Mythological site of Bhima and Kichaka near Bhadrapur."),
    ("Betana Wetland", "lakes", "Morang", "Koshi", "Betana", 26.53, 87.33, "Wetland reserve with boating in Belbari, Morang."),
    ("Dantakali Temple", "temples", "Sunsari", "Koshi", "Dharan", 26.81, 87.29, "Shakti temple in the forests above Dharan."),
    ("Pindeshwor Temple", "temples", "Sunsari", "Koshi", "Dharan", 26.79, 87.29, "Cave temple of Shiva at the foot of Bijayapur hill, Dharan."),
    ("Rajarani Lake", "lakes", "Dhankuta", "Koshi", "Rajarani", 27.05, 87.36, "Highland lake on the Dhankuta ridge."),
    ("Pakhribas", "villages", "Dhankuta", "Koshi", "Pakhribas", 27.04, 87.28, "Hill town known for organic farming and cheese."),
    ("Basantapur Bazaar", "cities", "Terhathum", "Koshi", "Basantapur", 27.16, 87.48, "Historic hill bazaar of Terhathum district."),
    ("Gupha Pokhari", "lakes", "Terhathum", "Koshi", "Gupha Pokhari", 27.10, 87.52, "Sacred lake in the Tinjure area of Terhathum."),
    ("Num", "villages", "Sankhuwasabha", "Koshi", "Num", 27.56, 87.29, "Gateway village to the Makalu Base Camp trek."),
    ("Tumlingtar", "cities", "Sankhuwasabha", "Koshi", "Tumlingtar", 27.31, 87.19, "Airport town and trek gateway of Sankhuwasabha."),
    ("Barun Valley", "valleys", "Sankhuwasabha", "Koshi", "Barun", 27.82, 87.10, "Pristine glacial valley inside Makalu Barun National Park."),
    ("Taksar", "villages", "Bhojpur", "Koshi", "Taksar", 27.17, 87.05, "Historic village of Bhojpur district."),
    ("Salpasilichho", "villages", "Bhojpur", "Koshi", "Salpasilichho", 27.43, 87.01, "Highland village of Bhojpur with Himalayan views."),
    ("Gokyo Lakes", "lakes", "Solukhumbu", "Koshi", "Gokyo", 27.95, 86.70, "UNESCO-listed turquoise glacial lakes above Namche."),
    ("Okhaldhunga Bazaar", "cities", "Okhaldhunga", "Koshi", "Okhaldhunga", 27.31, 86.50, "Historic town on the old Kathmandu-Everest trail."),
    ("Barahapokhari", "lakes", "Khotang", "Koshi", "Barahapokhari", 27.05, 86.83, "Twelve sacred ponds of Khotang district."),
    ("Udayapurgadhi", "heritage", "Udayapur", "Koshi", "Udayapurgadhi", 26.92, 86.58, "Historic fort of the Sen dynasty in Udayapur."),
    ("Rautamai", "temples", "Udayapur", "Koshi", "Rautamai", 26.99, 86.49, "Hilltop temple of goddess Rautamai in Udayapur."),
    ("Hanumannagar", "pilgrimage", "Saptari", "Madhesh", "Hanumannagar", 26.62, 86.75, "Shakti temple town of Hanuman on the Koshi river."),
    ("Kankalini Temple", "temples", "Saptari", "Madhesh", "Kankalini", 26.65, 86.60, "Famous goddess temple in Rajbiraj, Saptari."),
    ("Salhesh Phulbari", "pilgrimage", "Siraha", "Madhesh", "Salhesh", 26.72, 86.32, "Sacred Salhesh garden and tomb in Siraha."),
    ("Ram Mandir Janakpur", "temples", "Dhanusha", "Madhesh", "Janakpur", 26.73, 85.93, "Temple of Lord Ram in the holy city of Janakpur."),
    ("Gangasagar Dham", "pilgrimage", "Dhanusha", "Madhesh", "Janakpur", 26.73, 85.93, "Sacred pond and temple in Janakpur."),
    ("Matihani", "pilgrimage", "Mahottari", "Madhesh", "Matihani", 26.84, 85.80, "Mithila art village and pilgrimage site of Mahottari."),
    ("Hariwan", "cities", "Sarlahi", "Madhesh", "Hariwan", 27.00, 85.56, "Town of Sarlahi on the Bagmati river."),
    ("Maulapur", "cities", "Rautahat", "Madhesh", "Maulapur", 26.94, 85.29, "Town of Rautahat district."),
    ("Nijgadh", "cities", "Bara", "Madhesh", "Nijgadh", 27.20, 85.12, "Town of Bara known for the proposed international airport."),
    ("Birgunj Ghantaghar", "heritage", "Parsa", "Madhesh", "Birgunj", 27.00, 84.87, "Clock tower landmark of Birgunj city."),
    ("Shankaracharya Gate", "heritage", "Parsa", "Madhesh", "Birgunj", 27.00, 84.86, "Historic entrance gate of Birgunj."),
    # ---------- Bagmati ----------
    ("Jiri", "villages", "Dolakha", "Bagmati", "Jiri", 27.66, 86.23, "Gateway town of the classic Everest trek in Dolakha."),
    ("Tsho Rolpa Lake", "lakes", "Dolakha", "Bagmati", "Tsho Rolpa", 27.93, 86.40, "Glacial lake in the Rolwaling valley of Dolakha."),
    ("Melamchi Bazaar", "cities", "Sindhupalchok", "Bagmati", "Melamchi", 27.83, 85.56, "Town of Sindhupalchok on the Melamchi river."),
    ("Helambu", "trekking", "Sindhupalchok", "Bagmati", "Helambu", 28.00, 85.55, "Sherpa highlands and trekking region north of Kathmandu."),
    ("Langtang Village", "villages", "Rasuwa", "Bagmati", "Langtang", 28.20, 85.62, "Tamang village in the Langtang valley."),
    ("Syabrubesi", "villages", "Rasuwa", "Bagmati", "Syabrubesi", 28.16, 85.14, "Trailhead town for the Langtang trek."),
    ("Ruby Valley", "valleys", "Dhading", "Bagmati", "Ruby Valley", 28.23, 85.05, "Valley of Dhading rich in rubies and garnets."),
    ("Dhading Besi", "cities", "Dhading", "Bagmati", "Dhading Besi", 27.87, 84.92, "District headquarters of Dhading."),
    ("Salyantar", "valleys", "Dhading", "Bagmati", "Salyantar", 27.94, 84.86, "High valley and village of Dhading."),
    ("Nuwakot Durbar", "heritage", "Nuwakot", "Bagmati", "Nuwakot", 27.92, 85.17, "Seven-storey Rana-era palace fort of Nuwakot."),
    ("Devighat", "pilgrimage", "Nuwakot", "Bagmati", "Devighat", 27.80, 85.13, "Sacred river confluence of Trishuli and Tadi in Nuwakot."),
    ("Kakani", "viewpoints", "Nuwakot", "Bagmati", "Kakani", 27.80, 85.25, "Hill station with Himalayan views above Kathmandu."),
    ("Tupche", "villages", "Nuwakot", "Bagmati", "Tupche", 27.93, 85.10, "Village on the Trishuli river in Nuwakot."),
    ("Indreshwar Mahadev Temple", "temples", "Kavrepalanchok", "Bagmati", "Panauti", 27.58, 85.52, "Ancient three-roofed Shiva temple of Panauti."),
    ("Sanga", "heritage", "Kavrepalanchok", "Bagmati", "Sanga", 27.63, 85.45, "Village with the giant Shiva statue at Sanga."),
    ("Tham Danda", "viewpoints", "Ramechhap", "Bagmati", "Tham Danda", 27.44, 86.18, "Viewpoint ridge of Ramechhap."),
    ("Sailung", "viewpoints", "Ramechhap", "Bagmati", "Sailung", 27.54, 86.13, "Hill station of Ramechhap with snowy Himalayan views."),
    ("Kamalamai Temple", "temples", "Sindhuli", "Bagmati", "Kamalamai", 27.26, 85.91, "Temple town of Sindhuli."),
    ("Hariharpurgadhi", "heritage", "Sindhuli", "Bagmati", "Hariharpurgadhi", 27.21, 85.83, "Historic fort of Sindhuli district."),
    ("Marin Valley", "valleys", "Sindhuli", "Bagmati", "Marin", 27.20, 85.85, "Scenic valley of the Marin Khola in Sindhuli."),
    ("Chitlang", "villages", "Makwanpur", "Bagmati", "Chitlang", 27.55, 85.20, "Historic Newar village of Makwanpur with goat cheese farms."),
    ("Kulekhani", "lakes", "Makwanpur", "Bagmati", "Kulekhani", 27.58, 85.16, "Reservoir lake of the Kulekhani hydropower project."),
    ("Bishazari Tal", "lakes", "Chitwan", "Bagmati", "Bishazari", 27.62, 84.43, "Twenty-lake wetland inside Chitwan National Park."),
    ("Narayani River", "rivers", "Chitwan", "Bagmati", "Narayani", 27.55, 84.35, "Major river of Chitwan, home to gharial crocodiles."),
    # ---------- Gandaki ----------
    ("Ligligkot", "heritage", "Gorkha", "Gandaki", "Liglig", 28.02, 84.63, "Historic fort hill of Gorkha."),
    ("Ghale Gaun", "villages", "Lamjung", "Gandaki", "Ghale Gaun", 28.27, 84.36, "Model eco-village of the Ghale community in Lamjung."),
    ("Khudi", "villages", "Lamjung", "Gandaki", "Khudi", 28.30, 84.35, "Village and hydropower town of Lamjung."),
    ("Chhimkeshwori Temple", "temples", "Tanahun", "Gandaki", "Damauli", 27.98, 84.25, "Temple of goddess Chhimkeshwori in Tanahun."),
    ("Manang Village", "villages", "Manang", "Gandaki", "Manang", 28.67, 84.02, "Traditional Manangi village on the Annapurna circuit."),
    ("Gangapurna Lake", "lakes", "Manang", "Gandaki", "Gangapurna", 28.66, 84.02, "Glacial lake below Gangapurna peak."),
    ("Ice Lake", "lakes", "Manang", "Gandaki", "Ice Lake", 28.62, 83.99, "High alpine lake above Manang village."),
    ("Thorong La Pass", "trekking", "Manang", "Gandaki", "Thorong La", 28.78, 83.93, "5,416 m pass on the Annapurna circuit."),
    ("Rupse Waterfall", "waterfalls", "Myagdi", "Gandaki", "Rupse", 28.43, 83.55, "Tall waterfall near Tatopani in Myagdi."),
    ("Dhaulagiri Base Camp", "trekking", "Myagdi", "Gandaki", "Dhaulagiri", 28.63, 83.49, "Base camp of the seventh-highest mountain."),
    ("Kushma Bazaar", "cities", "Parbat", "Gandaki", "Kushma", 28.22, 83.68, "Town of Parbat famous for the suspension bridge."),
    ("Kushma Suspension Bridge", "heritage", "Parbat", "Gandaki", "Kushma", 28.22, 83.68, "One of the world's highest pedestrian suspension bridges."),
    ("Modibeni", "pilgrimage", "Parbat", "Gandaki", "Modibeni", 28.30, 83.66, "Temple at the confluence of Modikhola in Parbat."),
    ("Panchakot", "viewpoints", "Baglung", "Gandaki", "Panchakot", 28.27, 83.58, "Five-fort hill with panoramic Himalayan views, Baglung."),
    ("Dhorpatan", "valleys", "Baglung", "Gandaki", "Dhorpatan", 28.47, 83.08, "High valley and hunting reserve of Baglung."),
    ("Gaja Daha", "lakes", "Baglung", "Gandaki", "Gaja Daha", 28.17, 83.42, "Sacred lake of Baglung district."),
    ("Phedikhola", "villages", "Syangja", "Gandaki", "Phedikhola", 28.01, 83.65, "Rural municipality of Syangja with mountain views."),
    ("Sirubari", "villages", "Syangja", "Gandaki", "Sirubari", 28.05, 83.73, "Model Gurung village tourism destination of Syangja."),
    ("Galyang", "cities", "Syangja", "Gandaki", "Galyang", 27.93, 83.72, "Hill town of Syangja on the Siddhartha highway."),
    ("Devchuli", "cities", "Nawalpur", "Gandaki", "Devchuli", 27.72, 84.05, "Town of Nawalpur district."),
    ("Maulakalika Temple", "temples", "Nawalpur", "Gandaki", "Maulakalika", 27.70, 84.05, "Goddess temple on a hill above the Narayani river."),
    ("Amaltari", "villages", "Nawalpur", "Gandaki", "Amaltari", 27.58, 84.17, "Tharu homestay village of Nawalpur near Chitwan."),
    # ---------- Lumbini ----------
    ("Ashoka Pillar Lumbini", "heritage", "Rupandehi", "Lumbini", "Lumbini", 27.469, 83.276, "The emperor Ashoka's pillar marking Buddha's birthplace."),
    ("Lumbini Monastic Zone", "buddhist-sites", "Rupandehi", "Lumbini", "Lumbini", 27.47, 83.27, "International monasteries of the Lumbini sacred garden."),
    ("Kapilvastu Museum", "museums", "Kapilvastu", "Lumbini", "Kapilvastu", 27.54, 83.05, "Museum of the ancient Shakya capital."),
    ("Kudan", "pilgrimage", "Kapilvastu", "Lumbini", "Kudan", 27.48, 83.12, "Buddhist site where Buddha first met his father."),
    ("Niglihawa", "pilgrimage", "Kapilvastu", "Lumbini", "Niglihawa", 27.44, 83.13, "Ancient Buddhist site with an Ashoka pillar."),
    ("Sagarhawa", "pilgrimage", "Kapilvastu", "Lumbini", "Sagarhawa", 27.52, 83.10, "Forest of the Shakya massacre site."),
    ("Tansen Durbar", "heritage", "Palpa", "Lumbini", "Tansen", 27.867, 83.55, "Rana palace overlooking Tansen bazaar."),
    ("Srinagar Hill", "viewpoints", "Palpa", "Lumbini", "Srinagar", 27.87, 83.53, "Viewpoint hill above Tansen with Dhaulagiri views."),
    ("Ridi Bazaar", "pilgrimage", "Gulmi", "Lumbini", "Ridi", 27.85, 83.42, "Sacred confluence town of the Ridi Kunda."),
    ("Dhurkot", "villages", "Gulmi", "Lumbini", "Dhurkot", 28.11, 83.30, "Hill village of Gulmi district."),
    ("Supa Deurali Temple", "temples", "Arghakhanchi", "Lumbini", "Supa Deurali", 27.99, 83.09, "Famous hilltop goddess temple of Arghakhanchi."),
    ("Arghakot", "heritage", "Arghakhanchi", "Lumbini", "Arghakot", 27.93, 83.18, "Historic fort of Arghakhanchi."),
    ("Jhimruk Valley", "valleys", "Pyuthan", "Lumbini", "Jhimruk", 28.14, 82.90, "Scenic valley of Pyuthan district."),
    ("Jaljala", "viewpoints", "Rolpa", "Lumbini", "Jaljala", 28.38, 82.52, "Highland plateau of Rolpa with panoramic views."),
    ("Thawang", "villages", "Rolpa", "Lumbini", "Thawang", 28.28, 82.62, "Historic village of Rolpa."),
    ("Runtigadhi", "heritage", "Rolpa", "Lumbini", "Runtigadhi", 28.30, 82.55, "Historic fort of Rolpa."),
    ("Putha Himal", "mountains", "Rukum East", "Lumbini", "Putha", 28.73, 82.80, "7,246 m peak of the Dhaulagiri range in Rukum."),
    ("Sisne Himal", "mountains", "Rukum East", "Lumbini", "Sisne", 28.67, 82.65, "Peak of western Rukum."),
    ("Kamal Daha", "lakes", "Rukum East", "Lumbini", "Kamal Daha", 28.60, 82.55, "Sacred lake of Rukum."),
    ("Jakhera Lake", "lakes", "Dang", "Lumbini", "Jakhera", 28.10, 82.38, "Wetland lake near Ghorahi, Dang."),
    ("Rani Talau", "lakes", "Banke", "Lumbini", "Rani Talau", 28.08, 81.61, "Lake near Nepalgunj in Banke."),
    ("Thakurdwara", "villages", "Bardiya", "Lumbini", "Thakurdwara", 28.29, 81.39, "Gateway town of Bardiya National Park."),
    ("Babai Valley", "valleys", "Bardiya", "Lumbini", "Babai", 28.40, 81.50, "River valley inside Bardiya National Park."),
    ("Ramgram Stupa", "buddhist-sites", "Nawalparasi West", "Lumbini", "Ramgram", 27.49, 83.66, "One of the eight great stupas, containing Buddha's relics."),
    ("Balmiki Ashram", "pilgrimage", "Nawalparasi West", "Lumbini", "Balmiki", 27.45, 83.68, "Hermitage of sage Valmiki on the Narayani river."),
    # ---------- Karnali ----------
    ("Syarpu Lake", "lakes", "Rukum West", "Karnali", "Syarpu", 28.78, 82.67, "Major tourism lake of Bafikot, Rukum West."),
    ("Chaurjahari", "cities", "Rukum West", "Karnali", "Chaurjahari", 28.58, 82.55, "Town of Rukum West district."),
    ("Kupinde Lake", "lakes", "Salyan", "Karnali", "Kupinde", 28.34, 82.16, "Famous lake of Bangad Kupinde, Salyan."),
    ("Khairabang Temple", "temples", "Salyan", "Karnali", "Khairabang", 28.42, 82.24, "Temple of Khairabang in Salyan."),
    ("Chhayachhetra", "pilgrimage", "Salyan", "Karnali", "Chhayachhetra", 28.31, 82.10, "Sacred site of Salyan district."),
    ("Kachuwa Daha", "lakes", "Salyan", "Karnali", "Kachuwa", 28.36, 82.06, "Lake of Salyan district."),
    ("Shey Gompa", "buddhist-sites", "Dolpa", "Karnali", "Shey", 29.60, 82.84, "Sacred Crystal Monastery of Dolpa."),
    ("Limi Valley", "valleys", "Humla", "Karnali", "Limi", 30.10, 81.60, "Remote Tibetan valley of Humla."),
    ("Hilsa", "cities", "Humla", "Karnali", "Hilsa", 30.02, 81.45, "Border bazaar of Humla on the road to Mount Kailash."),
    ("Raling Gompa", "buddhist-sites", "Humla", "Karnali", "Raling", 29.98, 81.68, "Monastery near Simikot, Humla."),
    ("Nyinba Valley", "valleys", "Humla", "Karnali", "Nyinba", 30.05, 81.58, "Valley of the Nyinba people of Humla."),
    ("Jumla Tatopani", "hot-springs", "Jumla", "Karnali", "Tatopani", 29.25, 82.15, "Hot spring near Jumla bazaar."),
    ("Patmara", "villages", "Jumla", "Karnali", "Patmara", 29.30, 82.12, "Apple-growing village of Jumla."),
    ("Raskot", "cities", "Kalikot", "Karnali", "Raskot", 29.20, 81.60, "Town of Kalikot district."),
    ("Pachal Jharana", "waterfalls", "Kalikot", "Karnali", "Pachal", 29.15, 81.65, "Waterfall of Kalikot district."),
    ("Mahawai", "temples", "Kalikot", "Karnali", "Mahawai", 29.10, 81.72, "Temple site of Kalikot."),
    ("Talcha", "cities", "Mugu", "Karnali", "Talcha", 29.53, 82.15, "Airport town of Mugu near Rara."),
    ("Chhayanath Dham", "temples", "Mugu", "Karnali", "Chhayanath", 29.42, 82.20, "Temple of Chhayanath in Mugu."),
    ("Murma Top", "viewpoints", "Mugu", "Karnali", "Murma", 29.60, 82.10, "Viewpoint hill of Mugu district."),
    ("Bulbule Lake", "lakes", "Surkhet", "Karnali", "Bulbule", 28.52, 81.72, "Spring-fed lake of Birendranagar, Surkhet."),
    ("Pancha Koshi", "pilgrimage", "Dailekh", "Karnali", "Pancha Koshi", 28.85, 81.68, "Five sacred springs and temple complex of Dailekh."),
    ("Dullu", "cities", "Dailekh", "Karnali", "Dullu", 28.84, 81.70, "Historic capital town of the Khas kingdom in Dailekh."),
    ("Bhairabi Temple Dailekh", "temples", "Dailekh", "Karnali", "Dailekh", 28.86, 81.71, "Temple of goddess Bhairabi in Dailekh."),
    ("Naumule", "cities", "Dailekh", "Karnali", "Naumule", 28.75, 81.74, "Town of Dailekh district."),
    ("Jajarkot Khalanga", "cities", "Jajarkot", "Karnali", "Khalanga", 28.77, 82.18, "District headquarters of Jajarkot."),
    # ---------- Sudurpashchim ----------
    ("Triveni Bajura", "pilgrimage", "Bajura", "Sudurpashchim", "Triveni", 29.55, 81.35, "Sacred confluence in Bajura district."),
    ("Budhinanda", "cities", "Bajura", "Sudurpashchim", "Budhinanda", 29.48, 81.55, "Rural municipality of Bajura."),
    ("Kolti", "villages", "Bajura", "Sudurpashchim", "Kolti", 29.45, 81.55, "Village of Bajura district."),
    ("Chainpur Bajhang", "cities", "Bajhang", "Sudurpashchim", "Chainpur", 29.55, 81.20, "District headquarters of Bajhang."),
    ("Bithadchir", "temples", "Bajhang", "Sudurpashchim", "Bithadchir", 29.62, 81.10, "Temple site of Bajhang."),
    ("Deval", "temples", "Bajhang", "Sudurpashchim", "Deval", 29.57, 81.25, "Temple of goddess Deval in Bajhang."),
    ("Malikarjun Temple", "temples", "Darchula", "Sudurpashchim", "Malikarjun", 29.18, 80.60, "Sacred temple of lord Shiva in Darchula."),
    ("Darchula Khalanga", "cities", "Darchula", "Sudurpashchim", "Khalanga", 29.12, 80.55, "District headquarters of Darchula."),
    ("Lipulekh Pass", "trekking", "Darchula", "Sudurpashchim", "Lipulekh", 30.23, 81.03, "High Himalayan pass to Tibet via Darchula."),
    ("Mahakali River", "rivers", "Darchula", "Sudurpashchim", "Mahakali", 29.12, 80.55, "Border river of Darchula and India."),
    ("Melauli Bhagawati Temple", "temples", "Baitadi", "Sudurpashchim", "Melauli", 29.49, 80.44, "Goddess temple of Baitadi."),
    ("Niglasaini Temple", "temples", "Baitadi", "Sudurpashchim", "Niglasaini", 29.53, 80.52, "Temple of goddess Niglasaini in Baitadi."),
    ("Patal Bhumeshwar Cave", "caves", "Baitadi", "Sudurpashchim", "Patal", 29.51, 80.46, "Sacred cave temple of Baitadi."),
    ("Jagannath Temple Baitadi", "temples", "Baitadi", "Sudurpashchim", "Jagannath", 29.50, 80.48, "Temple of Jagannath in Baitadi."),
    ("Amargadhi Fort", "heritage", "Dadeldhura", "Sudurpashchim", "Amargadhi", 29.28, 80.60, "Historic fort above Dadeldhura bazaar."),
    ("Ugratara Temple", "temples", "Dadeldhura", "Sudurpashchim", "Ugratara", 29.30, 80.58, "Temple of goddess Ugratara in Dadeldhura."),
    ("Ajayameru Kot", "heritage", "Dadeldhura", "Sudurpashchim", "Ajayameru", 29.32, 80.55, "Ancient fort hill of Dadeldhura."),
    ("Aalital Lake", "lakes", "Dadeldhura", "Sudurpashchim", "Aalital", 29.33, 80.63, "Natural lake of Dadeldhura."),
    ("Badikedar", "temples", "Doti", "Sudurpashchim", "Badikedar", 29.25, 80.95, "Sacred temple hill of Doti."),
    ("Jorayal", "valleys", "Doti", "Sudurpashchim", "Jorayal", 29.05, 81.10, "Valley of Doti district."),
    ("Ramaroshan", "lakes", "Achham", "Sudurpashchim", "Ramaroshan", 29.22, 81.16, "Cluster of nine sacred lakes in Achham."),
    ("Panchadeval", "heritage", "Achham", "Sudurpashchim", "Panchadeval", 29.28, 81.30, "Five ancient temples of Achham."),
    ("Ghodaghodi Lake", "lakes", "Kailali", "Sudurpashchim", "Ghodaghodi", 28.68, 80.95, "Ramsar wetland lake of Kailali."),
    ("Tikapur Park", "parks-gardens", "Kailali", "Sudurpashchim", "Tikapur", 28.51, 81.14, "Riverside park of Tikapur, Kailali."),
    ("Godawari Dham Kailali", "temples", "Kailali", "Sudurpashchim", "Godawari", 28.90, 80.58, "Temple complex of Godawari in Kailali."),
    ("Siddhanath Temple", "temples", "Kanchanpur", "Sudurpashchim", "Siddhanath", 28.98, 80.17, "Temple of Mahendranagar, Kanchanpur."),
    ("Gaddachauki", "cities", "Kanchanpur", "Sudurpashchim", "Gaddachauki", 28.99, 80.19, "Border town of Kanchanpur with India."),
]

created = 0
skipped = 0
for name, cslug, dist, prov, city, lat, lon, short in PLACES:
    slug = name.lower().replace(" ", "-").replace("(", "").replace(")", "").replace(",", "").replace("'", "").replace("&", "and")
    if Destination.objects.filter(slug=slug).exists():
        skipped += 1
        continue
    cat = cats.get(cslug) or cats.get("attraction")
    Destination.objects.create(
        name=name, slug=slug, category=cat, district=dist, province=prov,
        city=city, city_english=city, latitude=lat, longitude=lon,
        short_description=short, description=short, country="Nepal",
        status="approved", is_active=True, source="77-district-round", views_count=0,
    )
    created += 1

print(f"created: {created} | skipped (already exist): {skipped}")
