"""Round 16: Add Bagmati Province famous named places from the ward-by-ward
district data (Kathmandu, Lalitpur, Bhaktapur, Kavrepalanchok, Sindhupalchok,
Dolakha, Ramechhap, Sindhuli) as real destinations with categories +
coordinates. Skips existing (name + district alias), disambiguates slug
collisions across districts, and fixes missing provinces on matched rows.
"""
import os

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "Tourism.settings")

import django  # noqa: E402

django.setup()

from tourist.models import Destination, Category  # noqa: E402

cats = {c.slug: c for c in Category.objects.all()}

DISTRICT_ALIASES = {
    "Kathmandu": {"Kathmandu", "काठमाडौं", "काठमाडौं जिल्ला", "Kathmandu District"},
    "Lalitpur": {"Lalitpur", "ललितपुर", "ललितपुर जिल्ला", "Lalitpur District"},
    "Bhaktapur": {"Bhaktapur", "भक्तपुर", "भक्तपुर जिल्ला", "Bhaktapur District"},
    "Kavrepalanchok": {"Kavrepalanchok", "Kavre", "काभ्रेपलाञ्चोक", "काभ्रेपलाञ्चोक जिल्ला", "Kavrepalanchok District"},
    "Sindhupalchok": {"Sindhupalchok", "Sindhupalchowk", "सिन्धुपाल्चोक", "सिन्धुपाल्चोक जिल्ला", "Sindhupalchok District"},
    "Dolakha": {"Dolakha", "दोलखा", "दोलखा जिल्ला", "Dolakha District"},
    "Ramechhap": {"Ramechhap", "रामेछाप", "रामेछाप जिल्ला", "Ramechhap District"},
    "Sindhuli": {"Sindhuli", "सिन्धुली", "सिन्धुली जिल्ला", "Sindhuli District"},
    "Rasuwa": {"Rasuwa", "रसुवा", "रसुवा जिल्ला", "Rasuwa District"},
}

# (name, category_slug, district, city, lat, lon, short_description)
PLACES = [
    # ================= KATHMANDU DISTRICT =================
    ("Kapan Monastery", "buddhist-sites", "Kathmandu", "Budhanilkantha", 27.748, 85.384, "Major Tibetan Buddhist monastery of Kapan, home to the Karmapa tradition's monastic college."),
    ("Sundarijal", "villages", "Kathmandu", "Gokarneshwor", 27.764, 85.423, "Hillside settlement at the entrance to Shivapuri Nagarjun National Park, start of the Sundarijal-Panch Pokhari trek."),
    ("Sundarijal Waterfall", "waterfalls", "Kathmandu", "Gokarneshwor", 27.767, 85.421, "Scenic waterfall beside the historic Sundarijal hydroelectric plant at the Shivapuri foothills."),
    ("Bagdwar", "natural-wonders", "Kathmandu", "Budhanilkantha", 27.799, 85.410, "Mountain spring considered the source of the Bagmati River, a sacred pilgrimage and hiking site in Shivapuri."),
    ("Dhap Pokhari", "lakes", "Kathmandu", "Gokarneshwor", 27.772, 85.402, "Sacred pond near the Bagdwar trail in the Shivapuri foothills."),
    ("Uttargaya Temple", "temples", "Kathmandu", "Gokarneshwor", 27.742, 85.386, "Historic Shiva temple of Gokarneshwor municipality."),
    ("Chamunda Devi Temple Gokarneshwor", "temples", "Kathmandu", "Gokarneshwor", 27.738, 85.392, "Goddess temple of Gokarneshwor municipality."),
    ("Mahankal Temple Suntakhan", "temples", "Kathmandu", "Gokarneshwor", 27.728, 85.395, "Ancient Mahankal temple of Suntakhan, Gokarneshwor."),
    ("Gokarna Safari Park", "parks-gardens", "Kathmandu", "Gokarneshwor", 27.707, 85.399, "Safari and recreation park at Yagyadol, Gokarneshwor."),
    ("BP Museum Sundarijal", "museums", "Kathmandu", "Gokarneshwor", 27.762, 85.419, "Museum at Sundarijal dedicated to statesman B.P. Koirala."),
    ("Gokarna Forest", "forests", "Kathmandu", "Gokarneshwor", 27.706, 85.395, "Historic forest landscape of Gokarna beside the Bagmati river."),
    ("Kageshwori Temple", "temples", "Kathmandu", "Kageshwori-Manohara", 27.722, 85.415, "Namesake goddess temple of Kageshwori Manohara municipality."),
    ("Vishnudwar", "natural-wonders", "Kathmandu", "Budhanilkantha", 27.792, 85.372, "Sacred water source near the Shivapuri foothills, a pilgrimage and hiking site."),
    ("Nagi Gumba", "buddhist-sites", "Kathmandu", "Budhanilkantha", 27.796, 85.376, "Nunnery monastery in the Shivapuri forest above Budhanilkantha."),
    ("Naulin Bhadrakali", "temples", "Kathmandu", "Budhanilkantha", 27.719, 85.358, "Bhadrakali shrine of Budhanilkantha listed by the municipality."),
    ("Khadka Bhadrakali", "temples", "Kathmandu", "Budhanilkantha", 27.729, 85.362, "Bhadrakali temple of Budhanilkantha."),
    ("Tarebhir Budhanilkantha", "viewpoints", "Kathmandu", "Budhanilkantha", 27.787, 85.352, "Hill viewpoint of Budhanilkantha overlooking the Kathmandu Valley."),
    ("ISKCON Temple Budhanilkantha", "temples", "Kathmandu", "Budhanilkantha", 27.783, 85.363, "ISKCON Krishna temple of Budhanilkantha."),
    ("Tokha Chandeshwari Temple", "temples", "Kathmandu", "Tokha", 27.762, 85.339, "Historic Chandeshwari temple of Tokha, a Newar heritage landmark."),
    ("Tokha Old Town", "villages", "Kathmandu", "Tokha", 27.760, 85.340, "Historic Newar settlement of Tokha with traditional houses, bahals and stone spouts."),
    ("Sapana Tirtha", "pilgrimage", "Kathmandu", "Tokha", 27.754, 85.332, "Pilgrimage site of Tokha with temple and water features."),
    ("Ichangu Narayan", "temples", "Kathmandu", "Nagarjun", 27.718, 85.299, "Ancient Narayan temple on a hill west of Kathmandu, one of the valley's four Narayan shrines."),
    ("Halchowk Akash Bhairab", "temples", "Kathmandu", "Nagarjun", 27.728, 85.301, "Akash Bhairab shrine of Halchowk, Nagarjun."),
    ("Raniban", "forests", "Kathmandu", "Nagarjun", 27.724, 85.288, "Forest area of Nagarjun municipality, a hiking and recreation zone."),
    ("Nagarjun Jamacho", "viewpoints", "Kathmandu", "Nagarjun", 27.741, 85.279, "Hilltop viewpoint with a Buddhist stupa in Nagarjun Forest, a classic Kathmandu hike."),
    ("White Gumba", "buddhist-sites", "Kathmandu", "Nagarjun", 27.723, 85.286, "White-painted Buddhist monastery on the Nagarjun hillside above Balaju."),
    ("Badri Narayan Dham", "pilgrimage", "Kathmandu", "Nagarjun", 27.709, 85.281, "Religious site of Nagarjun municipality."),
    ("Ganeshman Singh Memorial Park", "parks-gardens", "Kathmandu", "Nagarjun", 27.708, 85.288, "Memorial park of Nagarjun named after revolutionary leader Ganeshman Singh."),
    ("Switzerland Park", "parks-gardens", "Kathmandu", "Nagarjun", 27.715, 85.277, "Recreation park of Nagarjun municipality."),
    ("Hasantar Gumba", "buddhist-sites", "Kathmandu", "Nagarjun", 27.703, 85.283, "Buddhist monastery of Nagarjun municipality."),
    ("Bhuvaneshwari Temple", "temples", "Kathmandu", "Nagarjun", 27.716, 85.284, "Goddess temple of Nagarjun municipality."),
    ("Panchakanya Temple Nagarjun", "temples", "Kathmandu", "Nagarjun", 27.729, 85.271, "Panchakanya temple of Nagarjun municipality."),
    ("Bhimsensthan Bhimdhunga", "pilgrimage", "Kathmandu", "Nagarjun", 27.721, 85.263, "Bhimsen shrine at Bhimdhunga, Nagarjun."),
    ("Kumari Ghar", "heritage", "Kathmandu", "Kathmandu", 27.704, 85.306, "Historic residence of the Living Goddess Kumari at Kathmandu Durbar Square."),
    ("Taleju Temple Kathmandu", "temples", "Kathmandu", "Kathmandu", 27.704, 85.307, "Malla-era temple of goddess Taleju inside the Hanuman Dhoka palace complex."),
    ("Rani Pokhari", "lakes", "Kathmandu", "Kathmandu", 27.705, 85.315, "Historic pond built by King Pratap Malla in 1670 at the centre of Kathmandu."),
    ("Dharahara", "heritage", "Kathmandu", "Kathmandu", 27.701, 85.311, "Rebuilt 9-storey Bhimsen Tower of Sundhara, Kathmandu's most famous landmark."),
    ("Singha Durbar", "heritage", "Kathmandu", "Kathmandu", 27.696, 85.326, "Historic neo-classical palace housing Nepal's federal secretariat."),
    ("Narayanhiti Palace Museum", "museums", "Kathmandu", "Kathmandu", 27.715, 85.320, "Museum of the former royal palace of Narayanhiti."),
    ("Thamel", "cities", "Kathmandu", "Kathmandu", 27.715, 85.310, "Kathmandu's famous tourist district of hotels, restaurants and shops."),
    ("Asan Bazaar", "shopping", "Kathmandu", "Kathmandu", 27.709, 85.313, "Historic crossroads market of old Kathmandu, famous for spices and daily bazaar."),
    ("Indra Chowk", "shopping", "Kathmandu", "Kathmandu", 27.708, 85.312, "Historic market square of old Kathmandu, hub of the Indra Jatra festival."),
    ("Freak Street", "heritage", "Kathmandu", "Kathmandu", 27.702, 85.308, "Historic street of Basantapur once famous with 1960s hippie travellers."),
    ("Kaiser Library", "museums", "Kathmandu", "Kathmandu", 27.715, 85.314, "Historic library of Kaiser Shumsher near Thamel."),
    ("Naxal Bhagwati", "temples", "Kathmandu", "Kathmandu", 27.713, 85.328, "Goddess temple of Naxal, central Kathmandu."),
    ("Balaju Water Garden", "parks-gardens", "Kathmandu", "Kathmandu", 27.742, 85.305, "Historic water garden of Balaju with its 22 stone dhara spouts."),
    ("Gyaneshwor Mahadev", "temples", "Kathmandu", "Kathmandu", 27.705, 85.332, "Mahadev temple of Gyaneshwor, central Kathmandu."),
    ("Koteshwor Mahadev", "temples", "Kathmandu", "Kathmandu", 27.672, 85.350, "Mahadev temple of Koteshwor, eastern Kathmandu gateway."),
    ("Chobhar Gorge", "natural-wonders", "Kathmandu", "Kirtipur", 27.655, 85.295, "Dramatic gorge where the Bagmati cuts through Chobhar hill, linked to the Manjushri legend."),
    ("Taudaha Lake", "lakes", "Kathmandu", "Kirtipur", 27.647, 85.287, "Wetland lake south of Kathmandu famous for birdwatching."),
    ("Manjushree Park and Cave", "caves", "Kathmandu", "Kirtipur", 27.658, 85.296, "Cave and park of Chobhar associated with the Bodhisattva Manjushri."),
    ("Adinath Temple Chobhar", "temples", "Kathmandu", "Kirtipur", 27.655, 85.295, "Historic temple of Chobhar hill above the gorge."),
    ("Jal Binayak Temple", "temples", "Kathmandu", "Kirtipur", 27.653, 85.295, "One of the four celebrated Binayak temples of the valley, beside the Bagmati at Chobhar."),
    ("Bagh Bhairav Temple", "temples", "Kathmandu", "Kirtipur", 27.678, 85.277, "Ancient tiger-form Bhairav temple at the heart of Kirtipur's historic town."),
    ("Uma Maheshwor Temple", "temples", "Kathmandu", "Kirtipur", 27.679, 85.275, "1655 Shiva-Parvati temple of Kirtipur with historic inscriptions and valley views."),
    ("Chilancho Stupa", "buddhist-sites", "Kathmandu", "Kirtipur", 27.677, 85.276, "Buddhist stupa of Kirtipur used as a viewpoint over the Kathmandu Valley."),
    ("Anandadi Lokeshwar", "buddhist-sites", "Kathmandu", "Kirtipur", 27.676, 85.277, "Buddhist shrine of Kirtipur listed by the municipality."),
    ("Kirtipur Historic City", "villages", "Kathmandu", "Kirtipur", 27.678, 85.277, "Ancient Newar hill town of Kirtipur with traditional brick streets and 265 listed monuments."),
    ("Panga", "villages", "Kathmandu", "Kirtipur", 27.661, 85.282, "Traditional Newar settlement of Kirtipur between Kirtipur and Chobhar."),
    ("Kaji Kalu Pandey Tomb", "heritage", "Kathmandu", "Chandragiri", 27.701, 85.241, "Memorial tomb of Kaji Kalu Pandey at Dahachok, Chandragiri."),
    ("Dahachok View Tower", "viewpoints", "Kathmandu", "Chandragiri", 27.699, 85.238, "View tower of Dahachok, Chandragiri with valley and mountain views."),
    ("Chandika Devi Temple", "temples", "Kathmandu", "Chandragiri", 27.694, 85.251, "Goddess temple of Chandragiri Ward 2."),
    ("Matatirtha Kunda", "lakes", "Kathmandu", "Chandragiri", 27.661, 85.257, "Sacred pond of Matatirtha, visited during Matatirtha Aunsi in memory of mothers."),
    ("Chandan Bharateshwar Temple", "temples", "Kathmandu", "Chandragiri", 27.663, 85.259, "Temple of the Matatirtha area, Chandragiri."),
    ("Triveni Dham Matatirtha", "pilgrimage", "Kathmandu", "Chandragiri", 27.658, 85.255, "Religious site of Chandragiri Ward 7."),
    ("Baikuntha Dham", "pilgrimage", "Kathmandu", "Chandragiri", 27.659, 85.251, "Pilgrimage site of Chandragiri Ward 8."),
    ("Machhenarayan Temple", "temples", "Kathmandu", "Chandragiri", 27.642, 85.270, "Narayan temple of Machhegaun, Chandragiri."),
    ("Balambu Kotghar", "heritage", "Kathmandu", "Chandragiri", 27.683, 85.253, "Historic fort-house of Balambu, Chandragiri."),
    ("Kankali View", "viewpoints", "Kathmandu", "Chandragiri", 27.684, 85.242, "Viewpoint of Purano Naikap, Chandragiri."),
    ("Vishnudevi Temple Tinthana", "temples", "Kathmandu", "Chandragiri", 27.679, 85.239, "Goddess temple of Tinthana, Chandragiri Ward 15."),
    ("Balkumari Temple Naikap", "temples", "Kathmandu", "Chandragiri", 27.688, 85.252, "Balkumari temple of Naya Naikap, Chandragiri Ward 14."),
    ("Sankhu Historic City", "villages", "Kathmandu", "Shankharapur", 27.725, 85.443, "Ancient Newar town of Sankhu planned in the shape of a conch shell, gateway to Bajrayogini."),
    ("Bajrayogini Temple Sankhu", "temples", "Kathmandu", "Shankharapur", 27.735, 85.446, "Ancient goddess temple above Sankhu, famous for the Bajrayogini Jatra."),
    ("Shalinadi", "rivers", "Kathmandu", "Shankharapur", 27.727, 85.442, "Sacred river and pilgrimage site of Sankhu associated with the Shalinadi Mela."),
    ("Manichud", "viewpoints", "Kathmandu", "Shankharapur", 27.742, 85.461, "Hill viewpoint above Sankhu on the Manichud hiking route."),
    ("Ghumarichowk", "villages", "Kathmandu", "Shankharapur", 27.718, 85.429, "Settlement of Shankharapur on the Bajrayogini-Manichud route."),
    ("Thulo Odar Cave", "caves", "Kathmandu", "Shankharapur", 27.722, 85.441, "Large cave of Nanglebhare, Shankharapur."),
    ("Hatti Dhunga", "natural-wonders", "Kathmandu", "Shankharapur", 27.721, 85.440, "Elephant-shaped rock of Nanglebhare, Shankharapur."),
    ("Sita Paila", "natural-wonders", "Kathmandu", "Shankharapur", 27.720, 85.442, "Legendary footprint rock of Sita at Nanglebhare, Shankharapur."),
    ("Dakshinkali Temple", "temples", "Kathmandu", "Dakshinkali", 27.593, 85.292, "Famous Kali temple south of Kathmandu, a major Shakti pilgrimage site."),
    ("Pharping", "villages", "Kathmandu", "Dakshinkali", 27.601, 85.287, "Historic Newar settlement of Dakshinkali with Buddhist caves and temples."),
    ("Sheshnarayan Temple", "temples", "Kathmandu", "Dakshinkali", 27.612, 85.283, "Narayan temple of the Pharping hills, one of the valley's four Narayan shrines."),
    ("Gopalyeshwor Temple", "temples", "Kathmandu", "Dakshinkali", 27.603, 85.290, "Shiva temple of Pharping."),
    ("Asura Cave", "caves", "Kathmandu", "Dakshinkali", 27.605, 85.291, "Meditation cave at Pharping where Padmasambhava is said to have practised."),
    ("Hyanglasi Gumba", "buddhist-sites", "Kathmandu", "Dakshinkali", 27.604, 85.285, "Buddhist monastery of Pharping."),
    ("Banasur Danda", "viewpoints", "Kathmandu", "Dakshinkali", 27.562, 85.303, "Highest point of Kathmandu District (about 2,278 m), a viewpoint in Dakshinkali."),
    ("Panjal Ganesh", "temples", "Kathmandu", "Dakshinkali", 27.577, 85.295, "Ganesh shrine of Dakshinkali."),
    ("Katuwal Daha", "lakes", "Kathmandu", "Dakshinkali", 27.568, 85.297, "Natural pond of Dakshinkali."),
    ("Jatipokhari", "lakes", "Kathmandu", "Dakshinkali", 27.570, 85.299, "Pond of Dakshinkali municipality."),
    ("Hattiban Danda", "viewpoints", "Kathmandu", "Dakshinkali", 27.581, 85.296, "Hill viewpoint of Dakshinkali."),
    ("Jhamkeshwari Temple", "temples", "Kathmandu", "Dakshinkali", 27.566, 85.290, "Temple of Dakshinkali Ward 9, subject of a municipal tourism study."),
    ("Setidevi Temple", "temples", "Kathmandu", "Dakshinkali", 27.582, 85.294, "Goddess temple of Dakshinkali."),
    ("Gorakhnath Temple Pharping", "temples", "Kathmandu", "Dakshinkali", 27.602, 85.288, "Gorakhnath temple of Pharping."),
    ("Chandra Jyoti Hydropower", "heritage", "Kathmandu", "Dakshinkali", 27.600, 85.284, "Site of Nepal's first hydropower plant (1911) at Pharping, now industrial-engineering heritage."),
    ("Sundarimai Temple", "temples", "Kathmandu", "Gokarneshwor", 27.766, 85.420, "Goddess temple of the Sundarijal tourism area."),
    ("Dadhichi Ashram", "spiritual-wellness", "Kathmandu", "Gokarneshwor", 27.765, 85.418, "Ashram at Sundarijal associated with sage Dadhichi."),
    # ================= LALITPUR DISTRICT =================
    ("Mul Chowk", "heritage", "Lalitpur", "Lalitpur", 27.672, 85.326, "Royal courtyard of Patan Durbar Square, one of the finest palace chowks of the valley."),
    ("Sundari Chowk", "heritage", "Lalitpur", "Lalitpur", 27.671, 85.326, "Ornamental palace courtyard of Patan famous for its sunken stone bath."),
    ("Kumbheshwor Pokhari", "lakes", "Lalitpur", "Lalitpur", 27.671, 85.322, "Sacred pond beside Kumbheshwar Temple, Patan."),
    ("Rato Machhindranath Temple", "temples", "Lalitpur", "Lalitpur", 27.673, 85.325, "Temple of Rato Machhindranath whose chariot festival is one of the valley's longest."),
    ("Harisiddhi", "villages", "Lalitpur", "Lalitpur", 27.638, 85.334, "Traditional Newar settlement of Lalitpur with the Harisiddhi temple."),
    ("Sunakothi", "villages", "Lalitpur", "Lalitpur", 27.650, 85.334, "Traditional Newar settlement of southern Lalitpur."),
    ("Karyabinayak Temple", "temples", "Lalitpur", "Lalitpur", 27.653, 85.319, "Ganesh temple of Karyabinayak, Lalitpur."),
    ("Pimbahal Pokhari", "lakes", "Lalitpur", "Lalitpur", 27.673, 85.323, "Historic pond of Pimbahal, Patan."),
    ("Rudrayani Temple", "temples", "Lalitpur", "Lalitpur", 27.645, 85.298, "Goddess temple of Khokana's heritage settlement."),
    ("Khokana", "villages", "Lalitpur", "Lalitpur", 27.644, 85.298, "Traditional Newar mustard-oil village of Lalitpur, internationally recognized for its cultural landscape."),
    ("Godawari Botanical Garden", "parks-gardens", "Lalitpur", "Godawari", 27.596, 85.363, "National Botanical Garden of Godawari at the foot of Phulchoki."),
    ("Godawari Kunda", "lakes", "Lalitpur", "Godawari", 27.595, 85.365, "Sacred spring pond of Godawari with its famous twelve-yearly mela."),
    ("Godawari Naudhara", "temples", "Lalitpur", "Godawari", 27.594, 85.362, "Nine-spout water shrine of Godawari."),
    ("Phulchoki", "viewpoints", "Lalitpur", "Godawari", 27.575, 85.395, "Highest peak of the Kathmandu Valley (2,762 m), a hiking and temple destination."),
    ("Bajrabarahi Temple", "temples", "Lalitpur", "Godawari", 27.635, 85.315, "Goddess temple of Chapagaun, one of the valley's famous Barahi shrines."),
    ("Chapagaun", "villages", "Lalitpur", "Godawari", 27.634, 85.312, "Historic Newar settlement of southern Lalitpur around Bajrabarahi."),
    ("Vishankhunarayan", "temples", "Lalitpur", "Godawari", 27.608, 85.339, "One of the four Narayan temples of the Kathmandu Valley, in the Godawari hills."),
    ("Saraswati Kund Lele", "lakes", "Lalitpur", "Godawari", 27.577, 85.348, "Sacred pond of Lele valley."),
    ("Santaneshwar Mahadev", "temples", "Lalitpur", "Godawari", 27.571, 85.342, "Shiva temple of Jharuwarashi, Godawari."),
    ("Tika Bhairav", "temples", "Lalitpur", "Godawari", 27.623, 85.328, "Bhairav site of Godawari near the old Rajkulo canal."),
    ("Shwet Barahi", "temples", "Lalitpur", "Godawari", 27.628, 85.321, "White Barahi temple of Godawari municipality."),
    ("Lele Mankamari", "temples", "Lalitpur", "Godawari", 27.573, 85.350, "Mankamana-related shrine of Lele, Godawari."),
    ("Lele Valley", "valleys", "Lalitpur", "Godawari", 27.580, 85.350, "Historical valley of southern Lalitpur with Lichhavi-era heritage."),
    ("Mahalaxmi Temple", "temples", "Lalitpur", "Mahalaxmi", 27.648, 85.348, "Major temple of Lubhu, one of the nine heavenly power centres of the valley."),
    ("Ashok Stupa Imadol", "buddhist-sites", "Lalitpur", "Mahalaxmi", 27.660, 85.343, "Ancient stupa of Imadol associated with Emperor Ashoka's legend."),
    ("Lakuri Bhanjyang", "viewpoints", "Lalitpur", "Mahalaxmi", 27.593, 85.385, "Hill pass of Mahalaxmi with panoramic valley views."),
    ("Shringirishi Cave", "caves", "Lalitpur", "Mahalaxmi", 27.600, 85.380, "Cave of the Lamatar hills linked to the Shringi Rishi tradition."),
    ("Kamadhenu Cave", "caves", "Lalitpur", "Mahalaxmi", 27.602, 85.382, "Cave of Mahalaxmi municipality's hill zone."),
    ("Siddhipur", "villages", "Lalitpur", "Mahalaxmi", 27.653, 85.338, "Traditional Newar settlement of Mahalaxmi with typical courtyards."),
    ("Lubhu", "villages", "Lalitpur", "Mahalaxmi", 27.648, 85.348, "Historic Newar settlement of Mahalaxmi famous for its heritage."),
    ("Imadol", "villages", "Lalitpur", "Mahalaxmi", 27.660, 85.343, "Traditional settlement area of Mahalaxmi municipality."),
    ("Konjyosom Statue", "heritage", "Lalitpur", "Konjyosom", 27.558, 85.383, "Statue at Chaughare, namesake of Konjyosom Rural Municipality."),
    ("Shanku Village", "villages", "Lalitpur", "Konjyosom", 27.548, 85.376, "Village of Konjyosom with Buddhist chortens and mountain views."),
    ("Pathibhara Temple Nallu", "temples", "Lalitpur", "Konjyosom", 27.549, 85.393, "Goddess temple of Nallu, Konjyosom."),
    ("Gupteshwar Cave Nallu", "caves", "Lalitpur", "Konjyosom", 27.548, 85.392, "Gupteshwar Mahadev cave of Nallu with a Baisakh Purnima fair."),
    ("Kanchhikot Temple", "temples", "Lalitpur", "Konjyosom", 27.552, 85.402, "Tamang goddess temple of Bhardeu with a Magh 1 fair."),
    ("Malta Phant", "natural-wonders", "Lalitpur", "Bagmati RM", 27.522, 85.359, "Malta field and landscape of Bagmati Rural Municipality."),
    ("Bhattedanda", "viewpoints", "Lalitpur", "Bagmati RM", 27.502, 85.363, "Hill area of Bagmati Rural Municipality with the famous radar-area viewpoint."),
    ("Siddheshwor Mahadev Bhattedanda", "temples", "Lalitpur", "Bagmati RM", 27.504, 85.361, "Shiva temple of Bhattedanda."),
    ("Majhkhanda Buddha Vihar", "buddhist-sites", "Lalitpur", "Bagmati RM", 27.518, 85.344, "Buddhist monastery of Ikudol."),
    ("Ghyampe Daha", "lakes", "Lalitpur", "Bagmati RM", 27.532, 85.331, "Pond of Ashrang, a tourism-potential site of Bagmati Rural Municipality."),
    ("Chamero Cave", "caves", "Lalitpur", "Bagmati RM", 27.528, 85.321, "Bat cave of Gimdi, an adventure-tourism site of Bagmati Rural Municipality."),
    ("Kaleshwor Mahadev", "temples", "Lalitpur", "Mahankal", 27.502, 85.383, "Temple on a peak above Gotikhel, a short trek from the village."),
    ("Vaitarani Dham", "pilgrimage", "Lalitpur", "Mahankal", 27.513, 85.392, "Religious site of Thuladurlung."),
    ("Simba Waterfall", "waterfalls", "Lalitpur", "Mahankal", 27.515, 85.394, "Waterfall of Thuladurlung, Mahankal."),
    ("Gotikhel", "villages", "Lalitpur", "Mahankal", 27.508, 85.378, "Valley village and headquarters of Mahankal Rural Municipality with mountain views."),
    ("Baitadi Dham", "pilgrimage", "Lalitpur", "Mahankal", 27.510, 85.380, "Pilgrimage site near Gotikhel attracting valley visitors on Saturdays."),
    # ================= BHAKTAPUR DISTRICT =================
    ("55-Window Palace", "heritage", "Bhaktapur", "Bhaktapur", 27.672, 85.428, "The famous 55-window palace of Bhaktapur Durbar Square."),
    ("Golden Gate", "heritage", "Bhaktapur", "Bhaktapur", 27.672, 85.428, "Gilded entrance gate of the palace of 55 windows."),
    ("National Art Museum", "museums", "Bhaktapur", "Bhaktapur", 27.672, 85.428, "Museum of traditional Nepali art inside the Bhaktapur palace complex."),
    ("Bhairavnath Temple", "temples", "Bhaktapur", "Bhaktapur", 27.672, 85.427, "Three-storey Bhairav temple of Taumadhi Square."),
    ("Pottery Square", "heritage", "Bhaktapur", "Bhaktapur", 27.671, 85.430, "Living pottery workshop square of Bhaktapur where pots dry in the sun."),
    ("Dattatraya Temple", "temples", "Bhaktapur", "Bhaktapur", 27.673, 85.431, "15th-century temple in the wood-carving quarter of Bhaktapur."),
    ("Siddha Pokhari", "lakes", "Bhaktapur", "Bhaktapur", 27.676, 85.427, "Historic royal pond at the eastern entrance of Bhaktapur."),
    ("Changu Narayan Temple", "temples", "Bhaktapur", "Changunarayan", 27.716, 85.427, "UNESCO-listed 5th-century temple on a hill east of Bhaktapur, Nepal's oldest Hindu temple."),
    ("Nagarkot View Tower", "viewpoints", "Bhaktapur", "Changunarayan", 27.715, 85.523, "View tower of Nagarkot with sunrise and Himalayan panoramas."),
    ("Suryabinayak Temple", "temples", "Bhaktapur", "Suryabinayak", 27.647, 85.387, "Licchavi-era shikhara-style Ganesh temple on a forested hill."),
    ("Ranikot Gadhi", "heritage", "Bhaktapur", "Suryabinayak", 27.628, 85.414, "Historic hill fort of Gundu-Sipadol, a growing resort-viewpoint area."),
    ("Ghyampedanda", "viewpoints", "Bhaktapur", "Suryabinayak", 27.625, 85.415, "Hill viewpoint of Gundu-Sipadol with valley views and resorts."),
    ("Chapacho Pottery Centre", "shopping", "Bhaktapur", "Madhyapur Thimi", 27.679, 85.377, "Pottery centre of Thimi where traditional ceramics are made."),
    ("Nagadesh", "villages", "Bhaktapur", "Madhyapur Thimi", 27.683, 85.378, "Traditional Newar settlement of Madhyapur Thimi with the Nagadesh Buddha Bihar."),
    ("Bode", "villages", "Bhaktapur", "Madhyapur Thimi", 27.685, 85.376, "Heritage settlement of Thimi famous for the tongue-piercing Jatra."),
    ("Balkumari Temple Thimi", "temples", "Bhaktapur", "Madhyapur Thimi", 27.678, 85.378, "Major goddess temple of Thimi."),
    ("Telkot", "villages", "Bhaktapur", "Changunarayan", 27.701, 85.457, "Hill settlement on the Nagarkot-Changu route with forest and views."),
    ("Telkot Gadhi", "heritage", "Bhaktapur", "Changunarayan", 27.700, 85.458, "Historic hill fort of Telkot."),
    ("Kileshwor Mahadev", "temples", "Bhaktapur", "Changunarayan", 27.715, 85.426, "Shiva temple beside Changu Narayan."),
    ("Chhinnamasta Changu", "temples", "Bhaktapur", "Changunarayan", 27.716, 85.428, "Goddess temple in the Changu Narayan complex."),
    ("Sankha Daha", "lakes", "Bhaktapur", "Changunarayan", 27.698, 85.423, "Conch-shaped pond of Sangdaha, Changunarayan."),
    ("Muhan Pokhari", "lakes", "Bhaktapur", "Changunarayan", 27.705, 85.420, "Pond of Changunarayan with the Muhan Ganesh shrine."),
    ("Kapil Temple", "temples", "Bhaktapur", "Changunarayan", 27.699, 85.424, "Temple of the Sangdaha area, Changunarayan."),
    ("Duwakot", "villages", "Bhaktapur", "Changunarayan", 27.679, 85.431, "Traditional settlement of Changunarayan."),
    ("Chhaling", "villages", "Bhaktapur", "Changunarayan", 27.693, 85.450, "Village of Changunarayan on the Nagarkot road."),
    # ================= KAVREPALANCHOK DISTRICT =================
    ("Dhulikhel Old Town", "villages", "Kavrepalanchok", "Dhulikhel", 27.622, 85.548, "Historic Newar core of Dhulikhel, formerly known as Shrikhandapur."),
    ("Kali Temple Dhulikhel", "temples", "Kavrepalanchok", "Dhulikhel", 27.623, 85.549, "Goddess temple of Dhulikhel with the famous 1000-step climb above the town."),
    ("Thousand Steps Dhulikhel", "trekking", "Kavrepalanchok", "Dhulikhel", 27.626, 85.546, "Stone stairway from Dhulikhel to the Kali Temple ridge."),
    ("Bhagwati Temple Dhulikhel", "temples", "Kavrepalanchok", "Dhulikhel", 27.621, 85.549, "Main goddess temple of Dhulikhel old town."),
    ("Devisthan Dhulikhel", "temples", "Kavrepalanchok", "Dhulikhel", 27.612, 85.552, "Shrine of Dhulikhel Ward 5."),
    ("Kavrebhanjyang", "viewpoints", "Kavrepalanchok", "Dhulikhel", 27.597, 85.617, "Hill pass on the B.P. Highway with valley and mountain views."),
    ("Namobuddha Monastery", "buddhist-sites", "Kavrepalanchok", "Namobuddha", 27.583, 85.584, "Buddhist monastery and stupa of Namobuddha, site of the Buddha's self-sacrifice legend."),
    ("Thrangu Tashi Yangtse Monastery", "buddhist-sites", "Kavrepalanchok", "Namobuddha", 27.584, 85.586, "Large Tibetan monastery above the Namobuddha stupa."),
    ("Panauti Triveni Ghat", "heritage", "Kavrepalanchok", "Panauti", 27.583, 85.520, "Sacred confluence of the Punyamati and Roshi rivers at Panauti."),
    ("Unmatta Bhairav", "temples", "Kavrepalanchok", "Panauti", 27.585, 85.520, "Historic Bhairav shrine of Panauti."),
    ("Brahmayani Temple Panauti", "temples", "Kavrepalanchok", "Panauti", 27.585, 85.521, "Goddess temple of Panauti's heritage core."),
    ("Balthali Village", "villages", "Kavrepalanchok", "Panauti", 27.568, 85.522, "Rural village of Panauti with valley views and resorts."),
    ("Khopasi", "villages", "Kavrepalanchok", "Panauti", 27.574, 85.505, "Newar settlement of Panauti with the Rangnath temple."),
    ("Rangnath Temple", "temples", "Kavrepalanchok", "Panauti", 27.575, 85.506, "Historic temple of Khopasi."),
    ("Chandeshwori Temple Banepa", "temples", "Kavrepalanchok", "Banepa", 27.637, 85.525, "Goddess temple above Banepa famous for the Chandeshwori Jatra."),
    ("Nala Bhagawati", "temples", "Kavrepalanchok", "Banepa", 27.650, 85.523, "Goddess temple of historic Nala, Banepa."),
    ("Banepa Layaku", "heritage", "Kavrepalanchok", "Banepa", 27.632, 85.522, "Historic palace courtyard of Banepa's old town."),
    ("Nasiksthan", "temples", "Kavrepalanchok", "Banepa", 27.637, 85.514, "Historic religious site at Sanga, Banepa."),
    ("Sanga Bhajyang", "viewpoints", "Kavrepalanchok", "Banepa", 27.634, 85.507, "Historic gateway viewpoint at Sanga on the Arniko Highway."),
    ("Ashapuri Mahadev", "temples", "Kavrepalanchok", "Banepa", 27.634, 85.528, "Shiva temple of the Chandeshwori forest, Banepa."),
    ("Dhaneshwor Temple", "temples", "Kavrepalanchok", "Banepa", 27.630, 85.524, "Temple of Banepa Ward 7."),
    ("Sharada Devi Temple", "temples", "Kavrepalanchok", "Banepa", 27.631, 85.519, "Goddess temple of Banepa Ward 11."),
    ("Anaikot View Tower", "viewpoints", "Kavrepalanchok", "Panchkhal", 27.661, 85.618, "View tower of Anaikot, Panchkhal with Himalayan views."),
    ("Dugdheshwari Temple", "temples", "Kavrepalanchok", "Panchkhal", 27.605, 85.582, "Shiva temple of Panchkhal."),
    ("Suvarneshwari Temple", "temples", "Kavrepalanchok", "Panchkhal", 27.613, 85.590, "Temple of Panchkhal."),
    ("Kotdevi", "temples", "Kavrepalanchok", "Panchkhal", 27.618, 85.598, "Goddess site of Panchkhal."),
    ("Khasre Gurung", "villages", "Kavrepalanchok", "Mandandeupur", 27.683, 85.563, "Gurung village of Mandandeupur developed as a model homestay."),
    ("Buddhathumka", "temples", "Kavrepalanchok", "Mandandeupur", 27.672, 85.573, "Buddhist site of Mandandeupur."),
    ("Pipalbot Mahadev", "temples", "Kavrepalanchok", "Mandandeupur", 27.681, 85.582, "Mahadev temple at Jyamdi Mandan."),
    ("Gairichaur", "parks-gardens", "Kavrepalanchok", "Mandandeupur", 27.688, 85.552, "Picnic area of Mandandeupur."),
    ("Tham Danda Kavre", "viewpoints", "Kavrepalanchok", "Mandandeupur", 27.700, 85.555, "Hill viewpoint of Mandandeupur with 360-degree views."),
    ("Jitouri Pokhari", "lakes", "Kavrepalanchok", "Mandandeupur", 27.682, 85.578, "Pond and picnic site of Mandandeupur."),
    ("Kashyapeshwar Mahadev", "temples", "Kavrepalanchok", "Mandandeupur", 27.688, 85.562, "Shiva temple of Mandandeupur Ward 9."),
    ("Brahmayani Devi Mandandeupur", "temples", "Kavrepalanchok", "Mandandeupur", 27.687, 85.560, "Goddess temple of Mandandeupur."),
    ("Trinetreshwar Mahadev Gufa", "caves", "Kavrepalanchok", "Mandandeupur", 27.678, 85.575, "Cave shrine of Mandandeupur."),
    ("Bethanchok Narayan", "temples", "Kavrepalanchok", "Bethanchowk", 27.538, 85.603, "Hilltop Narayan temple of Bethanchowk with valley and mountain views."),
    ("Tarkhase Lake", "lakes", "Kavrepalanchok", "Roshi", 27.528, 85.612, "Highland lake of Roshi with mountain views."),
    ("Bhumichuli", "viewpoints", "Kavrepalanchok", "Roshi", 27.522, 85.611, "Hill and view-tower site of Roshi."),
    ("Mhabar Lake", "lakes", "Kavrepalanchok", "Mahabharat", 27.508, 85.635, "Lake at about 2,500 m after which Mahabharat Rural Municipality is named."),
    ("Chaityapani", "lakes", "Kavrepalanchok", "Mahabharat", 27.512, 85.628, "Water site of the Mahabharat range."),
    ("Tara Khase Pond", "lakes", "Kavrepalanchok", "Roshi", 27.514, 85.619, "Pond of Roshi linked to a meteorite legend."),
    ("Hattiahaal", "natural-wonders", "Kavrepalanchok", "Roshi", 27.531, 85.621, "Legendary natural feature of Roshi."),
    ("Dolalghat", "rivers", "Kavrepalanchok", "Bhumlu", 27.683, 85.723, "River confluence of the Sunkoshi and Indrawati, a gateway and recreation site."),
    ("Dullaleshwar Mahadev", "temples", "Kavrepalanchok", "Bhumlu", 27.684, 85.722, "Mahadev temple at the Sunkoshi-Indrawati confluence."),
    ("Bhimsen Sthan Mulkharaka", "temples", "Kavrepalanchok", "Bhumlu", 27.663, 85.702, "Bhimsen shrine of Bhumlu Ward 1."),
    ("Sangaswati", "temples", "Kavrepalanchok", "Bhumlu", 27.660, 85.695, "Religious site of Bhumlu."),
    ("Gaidedanda", "viewpoints", "Kavrepalanchok", "Bhumlu", 27.672, 85.712, "Hill viewpoint of Bhumlu."),
    ("Bhumlutar", "villages", "Kavrepalanchok", "Bhumlu", 27.662, 85.705, "Scenic settlement of Bhumlu Ward 8."),
    # ================= SINDHUPALCHOK DISTRICT =================
    ("Tatopani Hot Springs Sindhupalchok", "hot-springs", "Sindhupalchok", "Bhotekoshi", 27.901, 85.938, "Hot springs of the Bhote Koshi valley on the Arniko Highway."),
    ("Bhote Koshi River", "rivers", "Sindhupalchok", "Bhotekoshi", 27.880, 85.910, "Rushing river of the Arniko Highway corridor, famous for bungee and rafting."),
    ("Dugunagadhi Fort", "heritage", "Sindhupalchok", "Bhotekoshi", 27.917, 85.923, "Historic fort of the Bhote Koshi valley near the China border."),
    ("Panch Pokhari", "lakes", "Sindhupalchok", "Panchpokhari Thangpal", 28.071, 85.681, "Five sacred lakes at about 4,100 m, a major trekking and pilgrimage destination."),
    ("Ama Yangri", "mountains", "Sindhupalchok", "Helambu", 28.030, 85.552, "About 3,771 m peak of Helambu popular for accessible climbing."),
    ("Tarkeghyang", "villages", "Sindhupalchok", "Helambu", 28.003, 85.550, "Hyolmo village on the Helambu trekking route with its famous monastery."),
    ("Melamchi Ghyang", "villages", "Sindhupalchok", "Helambu", 27.989, 85.558, "Historic Hyolmo settlement with monastery on the Helambu circuit."),
    ("Sermathang", "villages", "Sindhupalchok", "Helambu", 27.988, 85.532, "Hyolmo village of the Helambu trek with mountain views."),
    ("Kutumsang", "villages", "Sindhupalchok", "Helambu", 28.041, 85.511, "Trekking settlement inside Langtang National Park on the Helambu route."),
    ("Tharepati", "villages", "Sindhupalchok", "Helambu", 27.992, 85.509, "Hill pass settlement of the Helambu and Gosainkunda trails."),
    ("Chisopani", "villages", "Sindhupalchok", "Helambu", 27.941, 85.489, "First-night village of the Helambu trek."),
    ("Nagitham Danda", "viewpoints", "Sindhupalchok", "Panchpokhari Thangpal", 27.901, 85.683, "Emerging viewpoint with garden, stupa and paragliding."),
    ("Sipa Pyughar Ghyang Gumba", "buddhist-sites", "Sindhupalchok", "Indrawati", 27.848, 85.623, "Heritage Buddhist gumba of Indrawati."),
    ("Raneshwar Mahadev", "temples", "Sindhupalchok", "Indrawati", 27.858, 85.605, "Shiva temple of Indrawati."),
    ("Bhimsen Temple Nawalpur", "temples", "Sindhupalchok", "Indrawati", 27.843, 85.601, "Bhimsen temple of Nawalpur, Indrawati."),
    ("Tripurasundari Mai Temple", "temples", "Sindhupalchok", "Tripurasundari", 27.747, 85.753, "Goddess temple of Piskar, Tripurasundari."),
    ("Mahabhir Waterfall", "waterfalls", "Sindhupalchok", "Tripurasundari", 27.762, 85.762, "Waterfall of Dhuskun, Tripurasundari."),
    ("Toklakhu Danda", "viewpoints", "Sindhupalchok", "Tripurasundari", 27.743, 85.761, "Hill viewpoint of Tauthali, Tripurasundari."),
    ("Latu Temple", "temples", "Sindhupalchok", "Tripurasundari", 27.737, 85.748, "Temple of Chokti, Tripurasundari."),
    ("Chautara", "cities", "Sindhupalchok", "Chautara Sangachokgadhi", 27.769, 85.704, "District headquarters town of Sindhupalchok."),
    ("Sangachokgadhi", "villages", "Sindhupalchok", "Chautara Sangachokgadhi", 27.788, 85.693, "Town of the Chautara Sangachokgadhi municipality."),
    ("Bhotechaur Tea Garden", "tea-coffee", "Sindhupalchok", "Indrawati", 27.803, 85.518, "Tea gardens of Bhotechaur, a growing agro-tourism area."),
    ("Gaurati Bhimeshwor", "temples", "Sindhupalchok", "Chautara Sangachokgadhi", 27.801, 85.716, "Religious site of the Chautara area."),
    ("Bahrabise", "cities", "Sindhupalchok", "Bahrabise", 27.793, 85.852, "Town on the Arniko Highway at the Bhote Koshi corridor."),
    ("Gosaikunda", "lakes", "Rasuwa", "Gosaikunda", 28.079, 85.435, "Sacred alpine lake at 4,380 m, a major pilgrimage and trekking destination."),
    # ================= DOLAKHA DISTRICT =================
    ("Beding", "villages", "Dolakha", "Gaurishankar", 27.902, 86.420, "Sherpa village of the Rolwaling valley on the Tsho Rolpa trek."),
    ("Na Village", "villages", "Dolakha", "Gaurishankar", 27.924, 86.405, "High Sherpa settlement of the Rolwaling valley."),
    ("Khare Rolwaling", "villages", "Dolakha", "Gaurishankar", 27.885, 86.398, "Gateway village of the Rolwaling valley."),
    ("Bigu Monastery", "buddhist-sites", "Dolakha", "Bigu", 27.852, 86.253, "Buddhist monastery of Bigu village."),
    ("Lamabagar", "villages", "Dolakha", "Gaurishankar", 27.826, 86.183, "Village on the Tamakoshi river near the Tibet border."),
    ("Kalinchowk Bhagawati", "temples", "Dolakha", "Kalinchowk", 27.768, 86.059, "Hilltop goddess temple at about 3,842 m, a major pilgrimage and snow destination."),
    ("Kuri Village", "villages", "Dolakha", "Kalinchowk", 27.778, 86.057, "Tourism village at the Kalinchowk cable car upper station."),
    ("Kalinchowk Cable Car", "adventure", "Dolakha", "Kalinchowk", 27.770, 86.058, "Cable car from Dhap to Kuri serving Kalinchowk Bhagawati."),
    ("Singati", "cities", "Dolakha", "Kalinchowk", 27.733, 86.062, "Market town of the Tamakoshi valley, Kalinchowk headquarters."),
    ("Lapilang", "villages", "Dolakha", "Kalinchowk", 27.712, 86.108, "Thami village of Kalinchowk."),
    ("Suspa Kshyamawati", "villages", "Dolakha", "Kalinchowk", 27.663, 86.118, "Thami cultural village of Kalinchowk."),
    ("Jiri Bazaar", "cities", "Dolakha", "Jiri", 27.634, 86.231, "Gateway town of the classic Jiri-Everest trek."),
    ("Jiri Valley", "valleys", "Dolakha", "Jiri", 27.632, 86.229, "Valley landscape of the Jiri-Everest trailhead."),
    ("Deurali Jiri", "viewpoints", "Dolakha", "Jiri", 27.651, 86.203, "Hill pass on the Jiri-Everest route."),
    ("Shailung Danda", "viewpoints", "Dolakha", "Shailung", 27.875, 86.162, "Highland hill of Shailung famous for panoramic Himalayan views."),
    ("Dolakha Old Town", "villages", "Dolakha", "Bhimeshwor", 27.657, 86.090, "Historic Newar core of the Dolakha bazaar."),
    ("Tripurasundari Temple Dolakha", "temples", "Dolakha", "Bhimeshwor", 27.658, 86.091, "Goddess temple of Dolakha bazaar."),
    # ================= RAMECHHAP DISTRICT =================
    ("Ramechhap Bazaar", "cities", "Ramechhap", "Ramechhap", 27.330, 86.070, "Historic bazaar town of Ramechhap."),
    ("Old Ramechhap Settlement", "villages", "Ramechhap", "Ramechhap", 27.331, 86.071, "Old settlement of Ramechhap with traditional architecture."),
    ("Doramba", "villages", "Ramechhap", "Doramba Shanghu", 27.372, 86.228, "Tamang village of Doramba."),
    ("Gupteshwor Mahadev Gufa", "caves", "Ramechhap", "Likhu Tamakoshi", 27.352, 86.103, "Cave shrine of Likhu Tamakoshi."),
    ("Nagdaha Ramechhap", "lakes", "Ramechhap", "Likhu Tamakoshi", 27.398, 86.148, "Lake of Likhu Tamakoshi with the historic Gidan Chaur."),
    ("Bijulikot", "villages", "Ramechhap", "Likhu Tamakoshi", 27.343, 86.052, "Historic settlement of Likhu Tamakoshi."),
    ("Jalapadevi", "temples", "Ramechhap", "Likhu Tamakoshi", 27.362, 86.082, "Goddess temple of Likhu Tamakoshi."),
    ("Niranjana Bhagawati", "temples", "Ramechhap", "Likhu Tamakoshi", 27.355, 86.092, "Goddess temple of Likhu Tamakoshi."),
    ("Mandira Devi", "temples", "Ramechhap", "Likhu Tamakoshi", 27.366, 86.112, "Temple of Likhu Tamakoshi."),
    ("Jhatteshwor Mahadev", "temples", "Ramechhap", "Likhu Tamakoshi", 27.372, 86.122, "Shiva temple of Likhu Tamakoshi."),
    ("Baase Kharka", "viewpoints", "Ramechhap", "Likhu Tamakoshi", 27.382, 86.142, "Highland pasture of Likhu Tamakoshi."),
    ("Nagigadhi", "heritage", "Ramechhap", "Likhu Tamakoshi", 27.392, 86.132, "Historic site of Likhu Tamakoshi."),
    ("Duragaun", "villages", "Ramechhap", "Likhu Tamakoshi", 27.422, 86.182, "Village of Likhu Tamakoshi."),
    ("Khimti Hydropower", "heritage", "Ramechhap", "Likhu Tamakoshi", 27.432, 86.098, "Hydropower project area of the Khimti river."),
    ("Khandadevi Temple", "temples", "Ramechhap", "Khandadevi", 27.472, 86.152, "Major goddess temple of Ramechhap."),
    ("Sithkha Temple", "temples", "Ramechhap", "Khandadevi", 27.483, 86.162, "Temple area of Khandadevi."),
    ("Sunapati Danda", "viewpoints", "Ramechhap", "Sunapati", 27.448, 86.252, "Hill viewpoint (Lahremane) of Sunapati."),
    ("Numbur", "mountains", "Ramechhap", "Umakunda", 27.478, 86.532, "Peak of the Numbur Himal at the head of the Numbur Cheese Circuit."),
    ("Numbur Cheese Circuit", "trekking", "Ramechhap", "Umakunda", 27.470, 86.500, "Trekking circuit through Sherpa villages famous for cheese-making."),
    ("Thodung Monastery", "buddhist-sites", "Ramechhap", "Umakunda", 27.497, 86.481, "Monastery on the Numbur Cheese Circuit."),
    ("Jatapokhari", "lakes", "Ramechhap", "Umakunda", 27.503, 86.503, "Highland lake of Umakunda."),
    ("Numburchuili", "mountains", "Ramechhap", "Umakunda", 27.487, 86.518, "Peak of the Numbur group."),
    # ================= SINDHULI DISTRICT =================
    ("Sindhuligadhi", "heritage", "Sindhuli", "Kamalamai", 27.268, 85.953, "Historic fort of the 1767 battle where Nepali forces defeated the British."),
    ("Sindhuligadhi Durbar Square", "heritage", "Sindhuli", "Kamalamai", 27.269, 85.954, "Historic durbar square of the Sindhuligadhi fort area."),
    ("Siddhababa Temple Kamalamai", "temples", "Sindhuli", "Kamalamai", 27.254, 85.948, "Temple on Chyaukot Danda with views of Sindhulimadhi."),
    ("Bhadrakali Temple Kamalamai", "temples", "Sindhuli", "Kamalamai", 27.278, 85.942, "Hill temple near Dhungre Bhanjyang."),
    ("Ranichuri Durbar", "heritage", "Sindhuli", "Kamalamai", 27.221, 85.922, "Historic durbar of Ranichuri."),
    ("Madhuganga Mahadev", "temples", "Sindhuli", "Dudhauli", 27.102, 85.852, "Major Shiva temple of Dudhauli attracting pilgrims during Shrawan."),
    ("Marin Drive", "scenic-routes", "Sindhuli", "Marin", 27.118, 85.903, "Scenic riverside road corridor of Marin."),
    ("Marin Khola", "rivers", "Sindhuli", "Marin", 27.122, 85.895, "River of the Marin valley."),
    ("Kusheshwar Mahadev", "temples", "Sindhuli", "Sunkoshi", 27.032, 85.782, "Shiva temple of Dumja, Sunkoshi."),
    ("Faparchuli", "viewpoints", "Sindhuli", "Ghyanglekh", 27.102, 85.723, "Highest point of Ghyanglekh (about 2,100 m) with a view tower."),
    ("BP Park", "parks-gardens", "Sindhuli", "Sunkoshi", 27.052, 85.772, "Park of Ramtar, Sunkoshi."),
    ("Devithan Satdobato", "temples", "Sindhuli", "Ghyanglekh", 27.132, 85.732, "Temple and gumba of Ghyanglekh Ward 3."),
    ("Marin Baraju Than", "temples", "Sindhuli", "Ghyanglekh", 27.142, 85.742, "Temple of Ghyanglekh Ward 5."),
    ("Fikkal Chuchuro", "viewpoints", "Sindhuli", "Fikkal", 27.132, 85.882, "Panoramic peak of Fikkal with Everest-to-Ganesh Himal views."),
    ("Fikkal View Tower", "viewpoints", "Sindhuli", "Fikkal", 27.131, 85.881, "View tower of Fikkal Ward 3."),
    ("Mahakali Temple Fikkal", "temples", "Sindhuli", "Fikkal", 27.133, 85.880, "Goddess temple of Fikkal Ward 3."),
    ("Hattidhunga Caves", "caves", "Sindhuli", "Fikkal", 27.134, 85.876, "Caves of Fikkal Ward 3."),
    ("Bagdwar Cave Fikkal", "caves", "Sindhuli", "Fikkal", 27.134, 85.878, "Cave of Fikkal Ward 3."),
    ("Rachanetham Danda", "viewpoints", "Sindhuli", "Fikkal", 27.142, 85.862, "Viewpoint of Mahadevdanda with views over eastern Nepal and the Terai."),
    ("Shahid Memorial Sunkoshi", "heritage", "Sindhuli", "Sunkoshi", 27.053, 85.774, "Martyrs' memorial of Ramtar, Sunkoshi."),
]


def main():
    created = 0
    skipped = 0
    fixed = 0
    for name, cslug, dist, city, lat, lon, short in PLACES:
        aliases = DISTRICT_ALIASES.get(dist, {dist})
        existing = Destination.objects.filter(name__iexact=name).filter(
            district__in=list(aliases) + [None]
        )
        if existing.exists():
            skipped += 1
            for d in existing:
                if not d.province:
                    d.province = "Bagmati"
                    d.save(update_fields=["province"])
                    fixed += 1
            continue
        base = (
            name.lower()
            .replace(" ", "-")
            .replace("(", "")
            .replace(")", "")
            .replace(",", "")
            .replace("'", "")
            .replace("/", "-")
            .replace("&", "and")
            .replace("\u2013", "-")
        )
        slug = base
        if Destination.objects.filter(slug=slug).exists():
            slug = f"{base}-{dist.lower()}"
            if Destination.objects.filter(slug=slug).exists():
                slug = f"{base}-{dist.lower()}-2"
        cat = cats.get(cslug) or cats.get("attraction")
        Destination.objects.create(
            name=name, slug=slug, category=cat, district=dist,
            province="Bagmati", city=city, city_english=city,
            latitude=lat, longitude=lon, short_description=short,
            description=short, country="Nepal", status="approved",
            is_active=True, source="round16-bagmati", views_count=0,
        )
        created += 1
    print(f"created: {created} | skipped (already exist): {skipped} | provinces fixed: {fixed}")


if __name__ == "__main__":
    main()
