# Generated by Django 5.0.6 on 2026-07-19 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destinationimage',
            options={'ordering': ['-is_cover', '-is_promoted', '-view_count', '-created_at']},
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='attribution',
            field=models.CharField(blank=True, help_text='Required for Unsplash/Wikimedia per their license terms', max_length=255),
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='external_url',
            field=models.URLField(blank=True, help_text='Used instead of `image` for externally-hosted photos (Unsplash/Wikimedia/etc.)'),
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='is_promoted',
            field=models.BooleanField(default=False, help_text='Auto-set true once a community upload crosses the popularity threshold'),
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='source',
            field=models.CharField(choices=[('admin', 'Admin Upload'), ('user_upload', 'Community Upload'), ('unsplash', 'Unsplash'), ('wikimedia', 'Wikimedia Commons'), ('google_places', 'Google Places'), ('foursquare', 'Foursquare')], default='admin', max_length=20),
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_photos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='destinationimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/gallery/'),
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('price_per_night', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('booking_status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('booking_url', models.URLField(blank=True, help_text='Link to book externally (e.g. Booking.com, Google)')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('source', models.CharField(choices=[('dataset', 'Imported Dataset'), ('google_places', 'Google Places'), ('foursquare', 'Foursquare'), ('manual', 'Manually Added')], default='dataset', max_length=20)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='tourist.destination')),
            ],
            options={
                'ordering': ['-rating', 'name'],
            },
        ),
    ]
