# Generated by Django 6.0.7 on 2026-07-24 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0001_initial'),
    ]

    operations = [
    ]
