# Generated by Django 5.0.6 on 2026-07-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0002_alter_destinationimage_options_and_more'),
    ]

    operations = []
