# Generated by Django 5.0.6 on 2026-07-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0003_alter_emergencycontact_options_and_more'),
    ]

    operations = []
