# Generated by Django 5.0.6 on 2026-07-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0003_alter_emergencycontact_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OSMEssentialService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('osm_id', models.CharField(help_text="OSM type/id, e.g. 'node/123456'", max_length=50, unique=True)),
                ('category', models.CharField(choices=[('hospital', 'Hospital'), ('clinic', 'Clinic'), ('pharmacy', 'Pharmacy'), ('police', 'Police'), ('armed_force', 'Armed Force'), ('fire_station', 'Fire Station'), ('bank', 'Bank'), ('ambulance', 'Ambulance'), ('municipality_office', 'Municipality Office'), ('tourism_office', 'Tourism Information Office')], max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('raw_tags', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='tourist_osm_latitud_b7c57a_idx'), models.Index(fields=['category'], name='tourist_osm_categor_ccb02d_idx')],
            },
        ),
        migrations.CreateModel(
            name='OSMTourismPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('osm_id', models.CharField(help_text="OSM type/id, e.g. 'way/123456'", max_length=50, unique=True)),
                ('category', models.CharField(choices=[('attraction', 'Attraction'), ('viewpoint', 'Viewpoint'), ('museum', 'Museum'), ('hotel', 'Hotel'), ('information', 'Information'), ('restaurant', 'Restaurant'), ('cafe', 'Cafe'), ('monument', 'Monument'), ('peak', 'Natural Peak'), ('waterfall', 'Waterfall'), ('hiking_path', 'Hiking Path'), ('hiking_route', 'Hiking Route')], max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('raw_tags', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='tourist_osm_latitud_d83de1_idx'), models.Index(fields=['category'], name='tourist_osm_categor_7ed135_idx')],
            },
        ),
    ]
