# Generated by Django 6.0.7 on 2026-07-23 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0004_osmessentialservice_osmtourismplace'),
    ]

    operations = []
