# Generated by Django 6.0.7 on 2026-07-23 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0004_osmessentialservice_osmtourismplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='external_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='destination',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destinations', to='tourist.category'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinations_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='entry_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='opening_hours',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='review_note',
            field=models.CharField(blank=True, help_text='Admin note, e.g. reason for rejection', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='short_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BudgetEstimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('transport_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('food_cost_per_day', models.DecimalField(decimal_places=2, max_digits=8)),
                ('accommodation_per_night', models.DecimalField(decimal_places=2, max_digits=8)),
                ('local_transport', models.DecimalField(decimal_places=2, max_digits=8)),
                ('entry_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('estimated_daily_budget', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estimated_trip_budget', models.DecimalField(decimal_places=2, max_digits=8)),
                ('destination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget_estimation', to='tourist.destination')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('district', models.CharField(max_length=100)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitals', to='tourist.destination')),
            ],
        ),
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='police_stations', to='tourist.destination')),
            ],
        ),
        migrations.CreateModel(
            name='RiskAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accidents', models.IntegerField(default=0)),
                ('landslide', models.IntegerField(default=0)),
                ('avalanche', models.IntegerField(default=0)),
                ('flood', models.IntegerField(default=0)),
                ('earthquake_damage', models.IntegerField(default=0)),
                ('hospital_count', models.IntegerField(default=0)),
                ('police_count', models.IntegerField(default=0)),
                ('fire_station_count', models.IntegerField(default=0)),
                ('emergency_risk', models.FloatField()),
                ('natural_disaster_risk', models.FloatField()),
                ('tourism_risk_index', models.FloatField()),
                ('risk_category', models.CharField(max_length=50)),
                ('destination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_analysis', to='tourist.destination')),
            ],
        ),
    ]
