# Generated by Django 5.0.6 on 2026-08-10 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0010_destination_municipality_destination_ward_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='aliases',
            field=models.CharField(blank=True, help_text='Alternative names, local spellings, e.g. Waling / Walling / Waling Bazaar', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='approx_travel_time',
            field=models.CharField(blank=True, help_text='e.g. 5h 30m by bus / 25m by flight', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='cultural_significance',
            field=models.TextField(blank=True, help_text='Cultural importance and local traditions', null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='distance_from_kathmandu_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='distance_from_nearest_airport_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='distance_from_nearest_city_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='food_cuisine_info',
            field=models.TextField(blank=True, help_text='Local cuisine, delicacies, and food experiences', null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='nearest_airport_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='nearest_major_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='recommended_days',
            field=models.PositiveSmallIntegerField(blank=True, default=2, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='religious_significance',
            field=models.TextField(blank=True, help_text='Religious history, temples, and sacred lore', null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='research_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('researching', 'Researching'), ('review_required', 'Review Required'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected')], default='published', max_length=30),
        ),
        migrations.AddField(
            model_name='destination',
            name='tourism_importance',
            field=models.TextField(blank=True, help_text='Why tourists visit this destination', null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='travel_safety_tips',
            field=models.TextField(blank=True, help_text='Practical safety tips and local advice', null=True),
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='copyright_status',
            field=models.CharField(default='verified_reusable', max_length=50),
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='image_category',
            field=models.CharField(default='attraction', max_length=50),
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='license_type',
            field=models.CharField(blank=True, default='Creative Commons CC BY-SA / Unsplash', max_length=100),
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='photographer',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='source_platform',
            field=models.CharField(blank=True, default='Wikimedia Commons', max_length=100),
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='source_url',
            field=models.URLField(blank=True, help_text='Original source page URL', max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='DestinationActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('difficulty_level', models.CharField(choices=[('Easy', 'Easy'), ('Moderate', 'Moderate'), ('Challenging', 'Challenging'), ('Strenuous', 'Strenuous')], default='Easy', max_length=50)),
                ('estimated_duration', models.CharField(blank=True, help_text='e.g. 2-3 hours / Half Day', max_length=50)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='tourist.destination')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DestinationAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('attraction_type', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('distance_from_center_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='tourist.destination')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DestinationNearbyPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('place_type', models.CharField(default='Viewpoint / Landmark', max_length=100)),
                ('distance_km', models.DecimalField(decimal_places=2, default=5.0, max_digits=6)),
                ('direction', models.CharField(blank=True, help_text='e.g. North-West / 15 mins hike', max_length=50)),
                ('short_info', models.TextField(blank=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nearby_places', to='tourist.destination')),
            ],
            options={
                'ordering': ['distance_km'],
            },
        ),
        migrations.CreateModel(
            name='DestinationSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('source_url', models.URLField(max_length=500)),
                ('source_type', models.CharField(default='Official Government / Tourism Portal', help_text='e.g. Nepal Tourism Board, Municipality Profile, Wikimedia Heritage Index, OpenStreetMap', max_length=100)),
                ('is_verified', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='tourist.destination')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DestinationTransitRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin', models.CharField(help_text='e.g. Kathmandu (Kalanki) / Pokhara / Nearest Airport', max_length=150)),
                ('transport_mode', models.CharField(default='Public Deluxe Bus', max_length=100)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('approx_duration', models.CharField(help_text='e.g. 5 hours 30 mins', max_length=100)),
                ('road_condition', models.CharField(blank=True, default='Paved Highway', max_length=150)),
                ('key_stops', models.TextField(blank=True, help_text='Major transit waypoints along the route')),
                ('estimated_fare_npr', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('route_source', models.CharField(blank=True, default='Nepal Highway Authority & Local Transit', max_length=200)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transit_routes', to='tourist.destination')),
            ],
            options={
                'ordering': ['distance_km'],
            },
        ),
    ]
