# Generated by Django 6.0.7 on 2026-08-10 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0008_attraction_culturalactivity_foodplace_sharedtrip_and_more'),
        ('tourist', '0010_destination_municipality_destination_ward_number'),
    ]

    operations = [
    ]
