# Generated by Django 5.0.6 on 2026-08-11 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0011_destination_aliases_destination_approx_travel_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('source_name', models.CharField(max_length=100)),
                ('target_province', models.CharField(blank=True, max_length=100)),
                ('target_district', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('paused', 'Paused')], db_index=True, default='pending', max_length=50)),
                ('records_scanned', models.IntegerField(default=0)),
                ('candidates_created', models.IntegerField(default=0)),
                ('duplicates_found', models.IntegerField(default=0)),
                ('verified_count', models.IntegerField(default=0)),
                ('errors_count', models.IntegerField(default=0)),
                ('log_summary', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DestinationSourceField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_name', models.CharField(db_index=True, help_text='e.g. altitude, history, routes, permits', max_length=100)),
                ('field_value', models.TextField()),
                ('source_name', models.CharField(max_length=150)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('source_id', models.CharField(blank=True, max_length=150)),
                ('confidence', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Estimated', 'Estimated'), ('Needs Review', 'Needs Review')], default='High', max_length=50)),
                ('verification_status', models.CharField(choices=[('Verified', 'Verified'), ('Estimated', 'Estimated'), ('Pending', 'Pending')], default='Verified', max_length=50)),
                ('last_verified', models.DateField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_sources', to='tourist.destination')),
            ],
            options={
                'ordering': ['field_name'],
            },
        ),
        migrations.CreateModel(
            name='DestinationCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('normalized_name', models.CharField(db_index=True, max_length=200)),
                ('alternate_names', models.JSONField(blank=True, default=list, help_text='List of aliases (Nepali, Devanagari, romanized)')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('altitude', models.CharField(blank=True, help_text='e.g. 2,175m / 7,135 ft', max_length=50)),
                ('province', models.CharField(blank=True, db_index=True, max_length=100)),
                ('district', models.CharField(blank=True, db_index=True, max_length=100)),
                ('municipality', models.CharField(blank=True, db_index=True, max_length=150)),
                ('ward_number', models.IntegerField(blank=True, null=True)),
                ('place_type', models.CharField(choices=[('mountain', 'Mountain Peak / Summit'), ('hill', 'Scenic Hill / Danda'), ('lake', 'Lake / Kund / Tal'), ('river', 'River / Stream / Rafting'), ('waterfall', 'Waterfall / Chhango'), ('temple', 'Temple / Mandir'), ('monastery', 'Monastery / Gompa'), ('stupa', 'Stupa / Chorten'), ('shrine', 'Sacred Shrine / Pilgrimage'), ('viewpoint', 'Panoramic Viewpoint'), ('trek_route', 'Trek Route / Alpine Pass'), ('national_park', 'National Park / Reserve'), ('conservation_area', 'Conservation Area'), ('cave', 'Cave / Gupha'), ('pass', 'Mountain Pass / La'), ('hot_spring', 'Natural Hot Spring / Tatopani'), ('historic_site', 'Historic Fort / Durbar'), ('village', 'Traditional Settlement / Homestay'), ('museum', 'Museum / Cultural Centre'), ('attraction', 'Tourism Attraction'), ('other', 'Other Geographic Feature')], db_index=True, default='attraction', max_length=50)),
                ('suggested_category_name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('source', models.CharField(db_index=True, help_text='e.g. OSM, Wikidata, Nepal_Govt_Gazetteer, Topo_Survey', max_length=100)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('source_id', models.CharField(blank=True, db_index=True, max_length=150)),
                ('evidence_data', models.JSONField(blank=True, default=dict, help_text='Raw source metadata, OSM tags, Wikidata claims, geocode proof')),
                ('confidence_score', models.FloatField(default=0.0, help_text='0.0 to 100.0 confidence rating')),
                ('quality_score', models.FloatField(default=0.0, help_text='0.0 to 100.0 completeness/quality score')),
                ('discovery_status', models.CharField(choices=[('discovered', 'Discovered'), ('candidate', 'Candidate'), ('verified', 'Verified'), ('enriched', 'Enriched'), ('needs_review', 'Needs Review'), ('published', 'Published to Destination'), ('rejected', 'Rejected'), ('merged_duplicate', 'Merged Duplicate')], db_index=True, default='discovered', max_length=50)),
                ('duplicate_status', models.CharField(choices=[('none', 'No Duplicate Found'), ('exact_match', 'Exact Name Match'), ('high_similarity', 'High Name & Location Similarity'), ('proximity_overlap', 'Spatial Proximity Overlap (< 500m)'), ('alias_of', 'Recognized Alias of Known Destination')], db_index=True, default='none', max_length=50)),
                ('duplicate_reason', models.TextField(blank=True, help_text='Human-readable explanation of why this was or was not considered a duplicate')),
                ('match_score', models.FloatField(default=0.0, help_text='Similarity percentage against best matched destination (0-100%)')),
                ('audit_trail', models.JSONField(blank=True, default=list, help_text='History of automated modifications, status changes, and promotions')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_places', to='tourist.category')),
                ('matched_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_matches', to='tourist.destination')),
            ],
            options={
                'ordering': ['-quality_score', '-confidence_score', 'name'],
                'indexes': [models.Index(fields=['normalized_name', 'district'], name='tourist_des_normali_006428_idx'), models.Index(fields=['discovery_status', 'quality_score'], name='tourist_des_discove_a10872_idx'), models.Index(fields=['source', 'source_id'], name='tourist_des_source_d35766_idx'), models.Index(fields=['place_type', 'province'], name='tourist_des_place_t_792239_idx')],
            },
        ),
    ]
