# Generated by Django 5.0.6 on 2026-08-13 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0012_discoveryjob_destinationsourcefield_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationimage',
            name='authenticity_score',
            field=models.FloatField(blank=True, help_text='Nepal authenticity', null=True),
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='destination_match_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='duplicate_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='generation_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='generation_prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='generation_provider',
            field=models.CharField(blank=True, help_text='openai / stability / google / flux', max_length=50),
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='generation_seed',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='negative_prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='overall_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='phash',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='quality_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='realism_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='Optimized thumbnail for fast web delivery'),
        ),
        migrations.AlterField(
            model_name='destinationimage',
            name='source',
            field=models.CharField(choices=[('admin', 'Admin Upload'), ('user_upload', 'Community Upload'), ('unsplash', 'Unsplash'), ('wikimedia', 'Wikimedia Commons'), ('google_places', 'Google Places'), ('foursquare', 'Foursquare'), ('ai_generated', 'AI Generated'), ('reference', 'Reference Image')], default='admin', max_length=20),
        ),
        migrations.AlterField(
            model_name='destinationimage',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Needs Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
        migrations.CreateModel(
            name='DestinationReferenceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(max_length=500)),
                ('source', models.CharField(blank=True, max_length=80)),
                ('license', models.CharField(blank=True, max_length=120)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('is_primary', models.BooleanField(default=False)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_images', to='tourist.destination')),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageGenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(default='openai', max_length=50)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('prompt', models.TextField()),
                ('negative_prompt', models.TextField(blank=True)),
                ('season', models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn'), ('winter', 'Winter')], default='autumn', max_length=10)),
                ('time_of_day', models.CharField(choices=[('sunrise', 'Sunrise'), ('day', 'Daytime'), ('sunset', 'Sunset'), ('night', 'Night')], default='day', max_length=10)),
                ('camera_style', models.CharField(choices=[('landscape', 'Landscape'), ('aerial', 'Aerial / Drone'), ('street', 'Street-level'), ('architectural', 'Architectural'), ('cultural', 'Cultural'), ('trekking', 'Trekking')], default='landscape', max_length=20)),
                ('num_images', models.PositiveSmallIntegerField(default=4)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to='tourist.destination')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='generation_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outputs', to='tourist.imagegenerationjob'),
        ),
        migrations.CreateModel(
            name='ImageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag', models.CharField(db_index=True, max_length=60)),
                ('confidence', models.FloatField(default=1.0)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='tourist.destinationimage')),
            ],
        ),
        migrations.CreateModel(
            name='ImageEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.CharField(choices=[('image', 'Image'), ('destination', 'Destination text')], max_length=12)),
                ('embedding_model', models.CharField(default='clip-ViT-B-32', max_length=60)),
                ('vector', models.JSONField(default=list)),
                ('dimensions', models.PositiveIntegerField(default=512)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='tourist.destination')),
                ('image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='tourist.destinationimage')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'embedding_model'], name='tourist_ima_content_29b08f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='imagegenerationjob',
            index=models.Index(fields=['status'], name='tourist_ima_status_e71949_idx'),
        ),
        migrations.AddIndex(
            model_name='imagegenerationjob',
            index=models.Index(fields=['destination', 'status'], name='tourist_ima_destina_8bf16d_idx'),
        ),
        migrations.AddIndex(
            model_name='imagetag',
            index=models.Index(fields=['tag'], name='tourist_ima_tag_5df031_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='imagetag',
            unique_together={('image', 'tag')},
        ),
    ]
