# Generated by Django 5.2.17 on 2026-08-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0014_userfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('tourist', 'Tourist'), ('guide', 'Local Guide'), ('admin', 'Admin'), ('super_admin', 'Super Admin'), ('tourism_admin', 'Tourism Admin'), ('content_moderator', 'Content Moderator'), ('district_manager', 'District Manager'), ('hotel_manager', 'Hotel Manager'), ('staff', 'Staff'), ('tourist_police', 'Tourist Police'), ('police', 'Police'), ('hospital_staff', 'Hospital Staff'), ('rescue_team', 'Rescue Team'), ('emergency_operator', 'Emergency Operator'), ('qa_tester', 'QA Tester')], default='tourist', max_length=20),
        ),
    ]
