# Generated by Django 5.0.6 on 2026-08-17 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0015_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destinationimage',
            options={'ordering': ['-is_cover', 'ordering', '-is_promoted', '-view_count', '-created_at']},
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Accessible alt text for the image', max_length=255),
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='image_path',
            field=models.CharField(blank=True, help_text='Relative path on the standalone image server, e.g. nepal/kathmandu/001.webp. When set, the full URL is IMAGE_BASE_URL + /images/ + image_path and the binary is served by the image server, never by Django.', max_length=500),
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='ordering',
            field=models.PositiveIntegerField(default=0, help_text='Display order within the destination gallery'),
        ),
        migrations.AlterField(
            model_name='destinationimage',
            name='source',
            field=models.CharField(choices=[('admin', 'Admin Upload'), ('user_upload', 'Community Upload'), ('unsplash', 'Unsplash'), ('wikimedia', 'Wikimedia Commons'), ('google_places', 'Google Places'), ('foursquare', 'Foursquare'), ('ai_generated', 'AI Generated'), ('reference', 'Reference Image'), ('image_server', 'Standalone Image Server')], default='admin', max_length=20),
        ),
        migrations.AddIndex(
            model_name='destinationimage',
            index=models.Index(fields=['destination', 'ordering'], name='destimg_dest_order_idx'),
        ),
        migrations.AddIndex(
            model_name='destinationimage',
            index=models.Index(fields=['image_path'], name='destimg_path_idx'),
        ),
    ]
