# Generated by Django 5.2.17 on 2026-08-18 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0018_familylink_familylink_unique_family_link_pair'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentHazard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hazard_type', models.CharField(choices=[('flood', 'Flood'), ('landslide', 'Landslide'), ('avalanche', 'Avalanche'), ('earthquake', 'Earthquake'), ('glof', 'Glacial lake outburst flood'), ('heavy_rain', 'Heavy rain'), ('snowstorm', 'Snowstorm'), ('forest_fire', 'Forest fire'), ('lightning', 'Lightning'), ('road_accident', 'Road accident'), ('health', 'Health / altitude'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], default='moderate', max_length=12)),
                ('source_type', models.CharField(choices=[('csv_import', 'CSV import'), ('admin', 'Admin verified'), ('official', 'Official authority'), ('news', 'News report'), ('api', 'External API'), ('user', 'Traveler report')], default='official', max_length=20)),
                ('source_name', models.CharField(max_length=160)),
                ('source_url', models.URLField(blank=True, max_length=600)),
                ('observed_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('station_name', models.CharField(blank=True, max_length=160)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('verified', models.BooleanField(default=False)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_hazards', to='tourist.destination')),
            ],
            options={
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['destination', 'is_active', 'observed_at'], name='tourist_cur_destina_68d7ec_idx')],
            },
        ),
        migrations.CreateModel(
            name='RiskIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hazard_type', models.CharField(choices=[('flood', 'Flood'), ('landslide', 'Landslide'), ('avalanche', 'Avalanche'), ('earthquake', 'Earthquake'), ('glof', 'Glacial lake outburst flood'), ('heavy_rain', 'Heavy rain'), ('snowstorm', 'Snowstorm'), ('forest_fire', 'Forest fire'), ('lightning', 'Lightning'), ('road_accident', 'Road accident'), ('health', 'Health / altitude'), ('other', 'Other')], max_length=30)),
                ('event_date', models.DateField()),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], default='moderate', max_length=12)),
                ('fatalities', models.PositiveIntegerField(default=0)),
                ('injuries', models.PositiveIntegerField(default=0)),
                ('source_type', models.CharField(choices=[('csv_import', 'CSV import'), ('admin', 'Admin verified'), ('official', 'Official authority'), ('news', 'News report'), ('api', 'External API'), ('user', 'Traveler report')], default='admin', max_length=20)),
                ('source_name', models.CharField(blank=True, max_length=160)),
                ('source_url', models.URLField(blank=True, max_length=600)),
                ('verified', models.BooleanField(default=False)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_incidents', to='tourist.destination')),
            ],
            options={
                'ordering': ['-event_date', '-created_at'],
                'indexes': [models.Index(fields=['destination', 'event_date'], name='tourist_ris_destina_6815ce_idx'), models.Index(fields=['hazard_type'], name='tourist_ris_hazard__4e00c8_idx')],
            },
        ),
    ]
