# Generated by Django 5.2.17 on 2026-08-18 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0019_currenthazard_riskincident'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/hospitals/'),
        ),
        migrations.AddField(
            model_name='osmessentialservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/essential/'),
        ),
        migrations.AddField(
            model_name='policestation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/police/'),
        ),
        migrations.AddField(
            model_name='travelriskfeedback',
            name='is_admin_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='travelriskfeedback',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelriskfeedback',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_risk_feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='InfrastructureSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('place_type', models.CharField(choices=[('destination', 'Tourism destination'), ('hotel', 'Hotel / homestay'), ('hospital', 'Hospital / clinic'), ('police', 'Police station'), ('bank', 'Bank / ATM'), ('fire_station', 'Fire station'), ('ambulance', 'Ambulance service'), ('tourism_office', 'Tourism office'), ('pharmacy', 'Pharmacy')], max_length=30)),
                ('name', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=60)),
                ('website', models.URLField(blank=True)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('municipality', models.CharField(blank=True, max_length=160)),
                ('municipality_type', models.CharField(blank=True, choices=[('metropolitan', 'Metropolitan'), ('sub_metropolitan', 'Sub-metropolitan'), ('municipality', 'Municipality'), ('rural_municipality', 'Rural municipality')], max_length=30)),
                ('ward_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('district', models.CharField(max_length=120)),
                ('province', models.CharField(max_length=120)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('transport_mode', models.CharField(blank=True, max_length=100)),
                ('route_origin', models.CharField(blank=True, max_length=160)),
                ('travel_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('road_condition', models.CharField(blank=True, max_length=160)),
                ('price_npr', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('opening_hours', models.CharField(blank=True, max_length=160)),
                ('image', models.ImageField(blank=True, null=True, upload_to='community/services/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='community/services/videos/')),
                ('source_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved and published'), ('rejected', 'Rejected'), ('needs_changes', 'Needs changes')], db_index=True, default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('published_model', models.CharField(blank=True, max_length=60)),
                ('published_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('csv_synced_at', models.DateTimeField(blank=True, null=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infrastructure_submissions', to='tourist.destination')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infrastructure_reviews', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infrastructure_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'place_type'], name='tourist_inf_status_5941c8_idx'), models.Index(fields=['latitude', 'longitude'], name='tourist_inf_latitud_f846ae_idx')],
            },
        ),
    ]
