# Generated by Django 5.2.17 on 2026-08-18 08:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0020_hospital_image_osmessentialservice_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='district',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='alert',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='municipality',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='alert',
            name='province',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='alert',
            name='radius_km',
            field=models.FloatField(default=4.0, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='alert',
            name='source_url',
            field=models.URLField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='alert',
            name='source',
            field=models.CharField(blank=True, help_text='e.g. DHM, BIPAD, Nepal Police, verified news desk', max_length=100),
        ),
    ]
