# Generated by Django 5.2.17 on 2026-08-18 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0021_alert_district_alert_is_verified_alert_municipality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currenthazard',
            name='affected_area',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='currenthazard',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='emergency_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hospital',
            name='opening_hours',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='hospital',
            name='source_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='hospital',
            name='source_url',
            field=models.URLField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='hospital',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='source_url',
            field=models.URLField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='hotel',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='osmessentialservice',
            name='emergency_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='osmessentialservice',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='osmessentialservice',
            name='opening_hours',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='osmessentialservice',
            name='source_name',
            field=models.CharField(blank=True, default='OpenStreetMap', max_length=160),
        ),
        migrations.AddField(
            model_name='osmessentialservice',
            name='source_url',
            field=models.URLField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='osmessentialservice',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policestation',
            name='emergency_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='policestation',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policestation',
            name='opening_hours',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='policestation',
            name='source_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='policestation',
            name='source_url',
            field=models.URLField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='policestation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='policestation',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskincident',
            name='affected_area',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='riskincident',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='riskincident',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='riskincident',
            name='municipality',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='riskincident',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='infrastructuresubmission',
            name='place_type',
            field=models.CharField(choices=[('destination', 'Tourism destination'), ('hotel', 'Hotel / homestay'), ('hospital', 'Hospital / clinic'), ('police', 'Police station'), ('bank', 'Bank'), ('atm', 'ATM'), ('blood_bank', 'Blood bank'), ('fire_station', 'Fire station'), ('ambulance', 'Ambulance service'), ('tourism_office', 'Tourism office'), ('pharmacy', 'Pharmacy')], max_length=30),
        ),
        migrations.AlterField(
            model_name='osmessentialservice',
            name='category',
            field=models.CharField(choices=[('hospital', 'Hospital'), ('clinic', 'Clinic'), ('pharmacy', 'Pharmacy'), ('police', 'Police'), ('armed_force', 'Armed Force'), ('fire_station', 'Fire Station'), ('bank', 'Bank'), ('blood_bank', 'Blood Bank'), ('atm', 'ATM'), ('ambulance', 'Ambulance'), ('municipality_office', 'Municipality Office'), ('tourism_office', 'Tourism Information Office')], max_length=30),
        ),
        migrations.CreateModel(
            name='InfrastructureMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('file', models.FileField(upload_to='community/services/media/')),
                ('caption', models.CharField(blank=True, max_length=220)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='tourist.infrastructuresubmission')),
            ],
            options={
                'ordering': ['-is_primary', 'created_at'],
            },
        ),
    ]
