# Generated by Django 5.2.17 on 2026-08-18 09:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0022_currenthazard_affected_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationFeatureProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('hard', 'Hard')], default='moderate', max_length=20)),
                ('duration_days', models.PositiveSmallIntegerField(default=2)),
                ('budget_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('nature_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('adventure_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('culture_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('spiritual_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('wildlife_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('photography_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('family_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('accessibility_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('source_type', models.CharField(default='admin', max_length=30)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('destination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feature_profile', to='tourist.destination')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeedbackEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('file', models.FileField(upload_to='feedback/evidence/')),
                ('caption', models.CharField(blank=True, max_length=220)),
                ('is_verified', models.BooleanField(default=False)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='tourist.userfeedback')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MLTrainingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_type', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('version', models.CharField(max_length=80)),
                ('previous_version', models.CharField(blank=True, max_length=80)),
                ('dataset_size', models.PositiveIntegerField(default=0)),
                ('newly_approved_records', models.PositiveIntegerField(default=0)),
                ('validation_metrics', models.JSONField(blank=True, default=dict)),
                ('output_log', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ml_training_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model_type', 'status', 'created_at'], name='tourist_mlt_model_t_cfb81f_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecommendationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('impression', 'Recommendation impression'), ('select', 'Recommendation selected'), ('search', 'Search'), ('view', 'Destination viewed'), ('save', 'Destination saved'), ('rating', 'Rating')], max_length=20)),
                ('session_key', models.CharField(blank=True, max_length=80)),
                ('query', models.CharField(blank=True, max_length=300)),
                ('score', models.FloatField(blank=True, null=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('consented', models.BooleanField(default=False)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_events', to='tourist.destination')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'event_type', 'created_at'], name='tourist_rec_user_id_a36dca_idx'), models.Index(fields=['destination', 'event_type'], name='tourist_rec_destina_a0eb49_idx')],
            },
        ),
        migrations.CreateModel(
            name='RiskNewsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=260)),
                ('summary', models.TextField(blank=True)),
                ('hazard_type', models.CharField(choices=[('flood', 'Flood'), ('landslide', 'Landslide'), ('avalanche', 'Avalanche'), ('earthquake', 'Earthquake'), ('glof', 'Glacial lake outburst flood'), ('heavy_rain', 'Heavy rain'), ('snowstorm', 'Snowstorm'), ('forest_fire', 'Forest fire'), ('lightning', 'Lightning'), ('road_accident', 'Road accident'), ('health', 'Health / altitude'), ('other', 'Other')], default='other', max_length=30)),
                ('source_name', models.CharField(max_length=180)),
                ('source_url', models.URLField(max_length=600, unique=True)),
                ('published_at', models.DateTimeField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('affected_area', models.CharField(blank=True, max_length=240)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('outdated', 'Outdated')], default='pending', max_length=20)),
                ('promoted_to_warning', models.BooleanField(default=False, help_text='Requires a separate verified Alert; news alone is never an official warning')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_news', to='tourist.destination')),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['destination', 'verification_status', 'published_at'], name='tourist_ris_destina_f42fc0_idx')],
            },
        ),
        migrations.CreateModel(
            name='RiskObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('observation_type', models.CharField(choices=[('rainfall', 'Rainfall'), ('river_level', 'River level'), ('temperature', 'Temperature'), ('wind', 'Wind'), ('snow', 'Snow'), ('warning_level', 'Warning level'), ('other', 'Other')], max_length=30)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=30)),
                ('trend', models.CharField(blank=True, choices=[('rising', 'Rising'), ('falling', 'Falling'), ('steady', 'Steady'), ('unknown', 'Unknown')], max_length=30)),
                ('station_name', models.CharField(max_length=180)),
                ('station_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('station_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('source_type', models.CharField(default='official', max_length=30)),
                ('source_name', models.CharField(max_length=180)),
                ('source_url', models.URLField(blank=True, max_length=600)),
                ('observed_at', models.DateTimeField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_observations', to='tourist.destination')),
            ],
            options={
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['destination', 'observation_type', 'observed_at'], name='tourist_ris_destina_edb56c_idx')],
            },
        ),
    ]
