# Generated by Django 5.0.6 on 2026-08-19 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0023_destinationfeatureprofile_feedbackevidence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffCapabilityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capabilities', models.JSONField(blank=True, default=dict, help_text='{"destinations":["view","change"],"images":["view","approve"]}')),
                ('managed_districts', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capability_profiles_assigned', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capability_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
