# Generated by Django 5.0.6 on 2026-08-20 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0026_seed_cms_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_feedback_threads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='last_staff_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='last_user_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('in_progress', 'In Progress'), ('waiting_user', 'Waiting for User'), ('replied', 'Replied'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('archived', 'Archived')], default='new', max_length=20),
        ),
    ]
