# Generated by Django 5.0.6 on 2026-08-20 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0027_userfeedback_assigned_to_userfeedback_closed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentsection',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentsection',
            name='scheduled_publish_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managedpage',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managedpage',
            name='scheduled_publish_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentsection',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published')], default='published', max_length=20),
        ),
        migrations.AlterField(
            model_name='managedpage',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published')], default='published', max_length=20),
        ),
        migrations.CreateModel(
            name='CMSRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(choices=[('pages', 'Pages'), ('sections', 'Sections'), ('navigation', 'Navigation'), ('settings', 'Settings')], max_length=20)),
                ('object_id', models.PositiveBigIntegerField()),
                ('revision_number', models.PositiveIntegerField()),
                ('snapshot', models.JSONField(default=dict)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('publish', 'Publish'), ('unpublish', 'Unpublish'), ('schedule', 'Schedule'), ('rollback', 'Rollback')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_revisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-revision_number'],
                'indexes': [models.Index(fields=['resource', 'object_id', '-revision_number'], name='tourist_cms_resourc_dddcd2_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='cmsrevision',
            constraint=models.UniqueConstraint(fields=('resource', 'object_id', 'revision_number'), name='unique_cms_object_revision'),
        ),
    ]
