# Generated by Django 5.0.6 on 2026-08-20 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0029_review_moderated_at_review_moderated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmsrevision',
            name='resource',
            field=models.CharField(choices=[('pages', 'Pages'), ('sections', 'Sections'), ('navigation', 'Navigation'), ('settings', 'Settings'), ('translations', 'Translations')], max_length=20),
        ),
        migrations.CreateModel(
            name='BrandingAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('logo', 'Logo'), ('favicon', 'Favicon')], max_length=20, unique=True)),
                ('file', models.ImageField(upload_to='branding/')),
                ('alt_text', models.CharField(blank=True, max_length=160)),
                ('mime_type', models.CharField(blank=True, max_length=80)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branding_assets_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CMSContentTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_resource', models.CharField(choices=[('pages', 'Page'), ('sections', 'Section'), ('navigation', 'Navigation')], max_length=20)),
                ('object_id', models.PositiveBigIntegerField()),
                ('language_code', models.CharField(max_length=10)),
                ('content', models.JSONField(default=dict)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_translations_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['target_resource', 'object_id', 'language_code'],
                'indexes': [models.Index(fields=['target_resource', 'object_id', 'language_code'], name='tourist_cms_target__6dd6a0_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='cmscontenttranslation',
            constraint=models.UniqueConstraint(fields=('target_resource', 'object_id', 'language_code'), name='unique_cms_content_translation'),
        ),
    ]
