# Generated by Django 5.0.6 on 2026-08-20 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_existing_delivery_state(apps, schema_editor):
    Notification = apps.get_model('tourist', 'Notification')
    for row in Notification.objects.all().iterator():
        if row.channel == 'in_app' or row.is_sent:
            row.delivery_status = 'sent'
            row.is_sent = True
            row.sent_at = row.created_at
            row.save(update_fields=['delivery_status', 'is_sent', 'sent_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0030_alter_cmsrevision_resource_brandingasset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('push_enabled', models.BooleanField(default=True)),
                ('safety_alerts', models.BooleanField(default=True)),
                ('booking_updates', models.BooleanField(default=True)),
                ('recommendations', models.BooleanField(default=True)),
                ('marketing', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='batch_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('safety', 'Safety'), ('booking', 'Booking'), ('recommendation', 'Recommendation'), ('marketing', 'Marketing'), ('feedback', 'Feedback')], db_index=True, default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='delivery_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='delivery_status',
            field=models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='queued', max_length=12),
        ),
        migrations.AddField(
            model_name='notification',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='notification',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='max_attempts',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notification',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['delivery_status', 'next_retry_at'], name='tourist_not_deliver_439686_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='tourist_not_user_id_ef3d34_idx'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(preserve_existing_delivery_state, migrations.RunPython.noop),
    ]
