# Generated by Django 5.0.6 on 2026-08-20 07:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0031_notificationpreference_notification_batch_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationtransitroute',
            name='booking_url',
            field=models.URLField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='destinationtransitroute',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='destinationtransitroute',
            name='departure_schedule',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='destinationtransitroute',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='destinationtransitroute',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='destinationtransitroute',
            name='operator_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='destinationtransitroute',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transit_routes_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=220)),
                ('cuisine_types', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('phone', models.CharField(blank=True, max_length=60)),
                ('website', models.URLField(blank=True)),
                ('opening_hours', models.CharField(blank=True, max_length=200)),
                ('price_range', models.CharField(choices=[('budget', 'Budget'), ('mid', 'Mid-range'), ('premium', 'Premium')], default='mid', max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('vegetarian_friendly', models.BooleanField(default=False)),
                ('image_url', models.URLField(blank=True, max_length=600)),
                ('source_name', models.CharField(blank=True, max_length=160)),
                ('source_url', models.URLField(blank=True, max_length=600)),
                ('is_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='pending', max_length=20)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='tourist.destination')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurants_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=220)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('travelers', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('budget_npr', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('itinerary_data', models.JSONField(blank=True, default=dict)),
                ('generation_source', models.CharField(choices=[('manual', 'Manual'), ('ml', 'ML assisted')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelPlanStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_number', models.PositiveSmallIntegerField(default=1)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travel_plan_stops', to='tourist.destination')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='tourist.travelplan')),
                ('transit_route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_stops', to='tourist.destinationtransitroute')),
            ],
            options={
                'ordering': ['day_number', 'display_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='restaurant',
            constraint=models.UniqueConstraint(fields=('destination', 'name'), name='unique_restaurant_destination_name'),
        ),
        migrations.AddConstraint(
            model_name='travelplanstop',
            constraint=models.UniqueConstraint(fields=('plan', 'day_number', 'display_order'), name='unique_plan_day_stop_order'),
        ),
    ]
