# Generated by Django 5.0.6 on 2026-08-20 08:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0032_destinationtransitroute_booking_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='riskincident',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskincident',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='riskobservation',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskobservation',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='familylink',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('revoked', 'Revoked')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='DataRetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='default', max_length=80, unique=True)),
                ('read_notification_days', models.PositiveIntegerField(default=365, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(3650)])),
                ('location_ping_days', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('recommendation_event_days', models.PositiveIntegerField(default=365, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(3650)])),
                ('resolved_sos_days', models.PositiveIntegerField(default=730, validators=[django.core.validators.MinValueValidator(365), django.core.validators.MaxValueValidator(3650)])),
                ('audit_log_days', models.PositiveIntegerField(default=2555, validators=[django.core.validators.MinValueValidator(365), django.core.validators.MaxValueValidator(7300)])),
                ('preserve_official_risk_records', models.BooleanField(default=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retention_policies_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
