# Generated by Django 5.0.6 on 2026-08-24 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0042_emergency_archive_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, help_text='Custom promotional title for the card. Blank defaults to destination name.', max_length=240)),
                ('short_description', models.TextField(blank=True, help_text='Custom promotional description. Blank defaults to destination description.')),
                ('featured_media_url', models.URLField(blank=True, help_text='Direct image URL override or fallback.', max_length=600)),
                ('cta_label', models.CharField(default='Explore Destination', help_text='Button text for call-to-action.', max_length=60)),
                ('cta_url', models.CharField(blank=True, help_text='Custom internal path override (e.g., /destinations/pokhara). Blank defaults to destination route.', max_length=240)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Ordering position in featured carousel/grid.')),
                ('is_published', models.BooleanField(db_index=True, default=True, help_text='Publishing status toggle.')),
                ('publish_start', models.DateTimeField(blank=True, help_text='Optional start time for scheduled publishing.', null=True)),
                ('publish_end', models.DateTimeField(blank=True, help_text='Optional end time for scheduled publishing.', null=True)),
            ],
            options={
                'ordering': ['display_order', '-updated_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='destination',
            new_name='tourist_des_is_feat_5828f1_idx',
            old_name='tourist_des_is_feat_8f1a2c_idx',
        ),
        migrations.RenameIndex(
            model_name='marketplacelisting',
            new_name='tourist_mar_status_e0eb7c_idx',
            old_name='tourist_mar_status_8a1c2d_idx',
        ),
        migrations.RenameIndex(
            model_name='marketplacelisting',
            new_name='tourist_mar_is_feat_8eb820_idx',
            old_name='tourist_mar_is_feat_9b3e4f_idx',
        ),
        migrations.RenameIndex(
            model_name='visitornotice',
            new_name='tourist_vis_is_publ_80a391_idx',
            old_name='tourist_vis_is_publ_4d9e1a_idx',
        ),
        migrations.RenameIndex(
            model_name='visitornotice',
            new_name='tourist_vis_kind_ec8541_idx',
            old_name='tourist_vis_kind_7c2b11_idx',
        ),
        migrations.AlterField(
            model_name='destinationvideo',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='featureddestination',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_destinations_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='featureddestination',
            name='destination',
            field=models.ForeignKey(help_text='The underlying destination record being promoted.', on_delete=django.db.models.deletion.CASCADE, related_name='featured_configurations', to='tourist.destination'),
        ),
        migrations.AddField(
            model_name='featureddestination',
            name='featured_media',
            field=models.ForeignKey(blank=True, help_text='Selected verified media record from destination gallery.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_promotions', to='tourist.destinationimage'),
        ),
        migrations.AddField(
            model_name='featureddestination',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_destinations_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='featureddestination',
            index=models.Index(fields=['is_published', 'display_order'], name='tourist_fea_is_publ_7accd5_idx'),
        ),
        migrations.AddIndex(
            model_name='featureddestination',
            index=models.Index(fields=['publish_start', 'publish_end'], name='tourist_fea_publish_335ed9_idx'),
        ),
        migrations.AddConstraint(
            model_name='featureddestination',
            constraint=models.UniqueConstraint(fields=('destination',), name='unique_featured_destination_ref'),
        ),
    ]
