# Generated by Django 5.0.6 on 2026-08-24 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0043_featureddestination_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destinationtransitroute',
            options={'ordering': ['distance_km', '-updated_at']},
        ),
        migrations.AddField(
            model_name='destination',
            name='coordinate_accuracy',
            field=models.CharField(blank=True, default='', help_text='Accuracy level (e.g. High / Exact, Moderate, District Center).', max_length=50),
        ),
        migrations.AddField(
            model_name='destination',
            name='coordinate_source',
            field=models.CharField(blank=True, default='', help_text='Origin source for GPS coordinates (e.g. Official Survey, OSM, Admin Verified).', max_length=100),
        ),
        migrations.AddField(
            model_name='destination',
            name='coordinate_status',
            field=models.CharField(choices=[('VERIFIED', 'Verified'), ('OFFICIAL', 'Official'), ('COMMUNITY_VERIFIED', 'Community Verified'), ('APPROXIMATE', 'Approximate'), ('UNVERIFIED', 'Unverified'), ('NOT_RECORDED', 'Not Recorded')], db_index=True, default='UNVERIFIED', max_length=30),
        ),
        migrations.AddField(
            model_name='destination',
            name='locality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='destination',
            name='location_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_destinations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='destinationtransitroute',
            name='confidence_level',
            field=models.CharField(choices=[('VERIFIED', 'Verified'), ('OFFICIAL', 'Official'), ('ADMIN_VERIFIED', 'Admin Verified'), ('PROVIDER_DATA', 'Provider Data'), ('CALCULATED', 'Calculated'), ('ESTIMATED', 'Estimated'), ('UNVERIFIED', 'Unverified'), ('UNKNOWN', 'Unknown')], db_index=True, default='CALCULATED', max_length=30),
        ),
        migrations.AddField(
            model_name='destinationtransitroute',
            name='destination_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='destinationtransitroute',
            name='destination_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='destinationtransitroute',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destinationtransitroute',
            name='fare_currency',
            field=models.CharField(default='NPR', max_length=10),
        ),
        migrations.AddField(
            model_name='destinationtransitroute',
            name='origin_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='destinationtransitroute',
            name='origin_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='destinationtransitroute',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='destinationtransitroute',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='destinationtransitroute',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='RouteSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('segment_order', models.PositiveSmallIntegerField(default=1)),
                ('from_location', models.CharField(max_length=200)),
                ('to_location', models.CharField(max_length=200)),
                ('transport_mode', models.CharField(default='Local Bus', max_length=100)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('duration_mins', models.PositiveIntegerField(blank=True, null=True)),
                ('fare_npr', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='tourist.destinationtransitroute')),
            ],
            options={
                'ordering': ['route', 'segment_order'],
            },
        ),
        migrations.CreateModel(
            name='DataReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('map_location', 'Wrong Map Location'), ('route', 'Wrong Route'), ('distance', 'Wrong Distance'), ('travel_time', 'Wrong Travel Time'), ('fare', 'Wrong Fare / Price'), ('opening_hours', 'Wrong Opening Hours'), ('photo', 'Wrong or Broken Photo'), ('description', 'Wrong Description'), ('moved', 'Destination Moved or Closed'), ('safety', 'Incorrect Safety Advice'), ('other', 'Other Data Correction')], db_index=True, default='other', max_length=30)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, default='medium', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New Report'), ('under_review', 'Under Review'), ('needs_verification', 'Needs Verification'), ('fixed', 'Fixed & Verified'), ('rejected', 'Rejected'), ('duplicate', 'Duplicate')], db_index=True, default='new', max_length=20)),
                ('page_url', models.CharField(blank=True, max_length=500)),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('displayed_value', models.TextField(blank=True)),
                ('suggested_value', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_reports', to='tourist.destination')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_reports_resolved', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_reports', to='tourist.destinationtransitroute')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'severity'], name='tourist_dat_status_fbf8ac_idx'), models.Index(fields=['report_type', 'status'], name='tourist_dat_report__9d00c5_idx')],
            },
        ),
    ]
