# Generated by Django 5.0.6 on 2026-08-25 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0044_alter_destinationtransitroute_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='budget_accuracy_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_feedbacks', to='tourist.destination'),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='itinerary_quality_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='recommendation_quality_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='route_quality_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UserPreferenceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('culture_weight', models.FloatField(default=0.5)),
                ('trekking_weight', models.FloatField(default=0.5)),
                ('nature_weight', models.FloatField(default=0.5)),
                ('adventure_weight', models.FloatField(default=0.5)),
                ('spiritual_weight', models.FloatField(default=0.5)),
                ('wildlife_weight', models.FloatField(default=0.5)),
                ('photography_weight', models.FloatField(default=0.5)),
                ('relaxation_weight', models.FloatField(default=0.5)),
                ('food_weight', models.FloatField(default=0.5)),
                ('family_weight', models.FloatField(default=0.5)),
                ('budget_sensitivity', models.FloatField(default=0.5)),
                ('pace_preference', models.CharField(default='balanced', max_length=20)),
                ('exploration_mode', models.CharField(default='balanced', max_length=20)),
                ('preferred_provinces', models.JSONField(blank=True, default=list)),
                ('visited_destination_ids', models.JSONField(blank=True, default=list)),
                ('avoid_destination_ids', models.JSONField(blank=True, default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
