# Generated by Django 5.0.6 on 2026-08-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0045_userfeedback_budget_accuracy_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='ai_override_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='ai_priority_level',
            field=models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='destination',
            name='ai_recommendation_status',
            field=models.CharField(choices=[('ALLOWED', 'Allowed'), ('BLOCKED', 'Blocked'), ('PRIORITY', 'Priority')], db_index=True, default='ALLOWED', max_length=20),
        ),
    ]
