# Generated by Django 5.2.17 on 2026-09-02 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0046_destination_ai_override_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentsection',
            name='section_type',
            field=models.CharField(choices=[('text', 'Text'), ('heading', 'Heading'), ('image', 'Image'), ('gallery', 'Gallery'), ('cards', 'Cards'), ('faq', 'FAQ'), ('cta', 'Call to action'), ('map', 'Map'), ('video', 'Video'), ('audio', 'Audio'), ('marquee', 'Marquee'), ('animation', 'Animation'), ('media', 'Media'), ('form', 'Form'), ('table', 'Table'), ('figure', 'Figure'), ('testimonials', 'Testimonials'), ('contact', 'Contact'), ('breadcrumbs', 'Breadcrumbs'), ('search', 'Search'), ('blocks', 'Block Container')], default='text', max_length=30),
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block_type', models.CharField(choices=[('heading', 'Heading'), ('subheading', 'Subheading'), ('rich_text', 'Rich Text'), ('image', 'Image'), ('gallery', 'Gallery'), ('button', 'Button'), ('table', 'Table'), ('video', 'Video / Iframe'), ('map', 'Map'), ('destination_grid', 'Destination Grid'), ('hotel_grid', 'Hotel Grid'), ('restaurant_grid', 'Restaurant Grid'), ('statistics', 'Statistics'), ('list', 'List'), ('quote', 'Quote'), ('alert', 'Alert / Callout'), ('divider', 'Divider'), ('html', 'Custom Safe HTML')], default='rich_text', max_length=50)),
                ('title', models.CharField(blank=True, max_length=240)),
                ('position', models.PositiveIntegerField(default=0)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_visible', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='tourist.contentsection')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_blocks_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
