# Generated by Django 5.0.6 on 2026-09-07 02:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0047_alter_contentsection_section_type_contentblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('kicker', models.CharField(blank=True, help_text='Small pill line, e.g. “Solukhumbu · 8,849 m”', max_length=140)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('link_slug', models.SlugField(blank=True, help_text='Destination slug for the primary Explore button', max_length=140)),
                ('image', models.ImageField(blank=True, help_text='Uploaded photo (served from /media/).', upload_to='hero/')),
                ('image_url', models.URLField(blank=True, help_text='Absolute CDN / Wikimedia URL, used if no upload.', max_length=600)),
                ('local_image', models.CharField(blank=True, help_text='Bundled asset path e.g. /images/destinations/everest/base-camp.jpg', max_length=300)),
                ('overlay_strength', models.PositiveSmallIntegerField(default=60, help_text='Legibility scrim intensity in percent. Higher = darker, more readable text.', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(92)])),
                ('focal_point', models.CharField(choices=[('center', 'Center'), ('top', 'Top (sky / peaks)'), ('bottom', 'Bottom (valley / foreground)')], default='center', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('duration_seconds', models.PositiveSmallIntegerField(default=7, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(20)])),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_slides_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
