# Generated by Django 5.0.6 on 2026-09-03 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0047_alter_contentsection_section_type_contentblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150)),
                ('relation_tag', models.CharField(choices=[('self', 'Self'), ('relative', 'Relative')], default='self', max_length=10)),
                ('relation', models.CharField(blank=True, help_text="e.g. 'Spouse', 'Father'", max_length=60)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('id_type', models.CharField(blank=True, help_text='Passport / Citizenship / License', max_length=50)),
                ('id_number', models.CharField(blank=True, max_length=100)),
                ('nationality', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['relation_tag', '-created_at'],
                'indexes': [models.Index(fields=['user', 'relation_tag'], name='tourist_per_user_id_6fd98a_idx')],
            },
        ),
    ]
