# Generated by Django 5.0.6 on 2026-09-07 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0051_rebrand_nepal_yatra'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200)),
                ('relation_tag', models.CharField(choices=[('self', 'Myself'), ('relative', 'Relative / companion')], default='self', max_length=10)),
                ('relation', models.CharField(blank=True, help_text='e.g. Spouse, Child, Friend', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('id_type', models.CharField(choices=[('passport', 'Passport'), ('national_id', 'National ID'), ('driving_license', 'Driving License'), ('citizenship', 'Citizenship Certificate'), ('other', 'Other')], default='passport', max_length=20)),
                ('id_number', models.CharField(blank=True, max_length=100)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Allergies, medical info, etc.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traveler_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Traveler document',
                'ordering': ['-created_at'],
            },
        ),
    ]
