# Generated by Django 5.0.6 on 2026-09-08 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0055_cleanup_junk_destination_anchors'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedirectRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_path', models.CharField(help_text='Path to redirect from, e.g. /destinations/everest-old', max_length=240, unique=True)),
                ('new_path', models.CharField(help_text='Path (or https:// URL) to redirect to', max_length=240)),
                ('is_permanent', models.BooleanField(default=True, help_text='Permanent (301-style) vs temporary redirect')),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redirect_rules_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', 'id'],
            },
        ),
    ]
