# Generated by Django 5.2.17 on 2026-09-08 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0057_newslettersignup'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin_name', models.CharField(blank=True, max_length=200)),
                ('origin_latitude', models.FloatField(blank=True, null=True)),
                ('origin_longitude', models.FloatField(blank=True, null=True)),
                ('destination_name', models.CharField(max_length=200)),
                ('destination_latitude', models.FloatField(blank=True, null=True)),
                ('destination_longitude', models.FloatField(blank=True, null=True)),
                ('transport_mode', models.CharField(blank=True, max_length=60)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('duration_min', models.IntegerField(blank=True, null=True)),
                ('duration_source', models.CharField(blank=True, help_text='routing_engine | estimated | unavailable', max_length=20)),
                ('label', models.CharField(blank=True, help_text="Optional traveller label, e.g. 'Home → Work'", max_length=200)),
                ('is_saved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_saved'], name='tourist_use_user_id_2587bc_idx')],
            },
        ),
    ]
