# Generated by Django 5.2.17 on 2026-09-09 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0058_userroute'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='escalation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='is_escalated',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
