# Generated by Django 5.2.17 on 2026-09-09 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0059_userfeedback_escalation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='submitted_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who created/submitted this entry for review.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='destination',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for Review'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='approved', max_length=20),
        ),
    ]
