# Generated by Django 5.2.17 on 2026-09-09 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0060_destination_submitted_by_alter_destination_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('headline', models.CharField(blank=True, help_text='One-line professional headline', max_length=160)),
                ('bio', models.TextField(blank=True)),
                ('years_experience', models.PositiveSmallIntegerField(default=0)),
                ('languages', models.JSONField(blank=True, default=list, help_text='["Nepali","English","Japanese"]')),
                ('specializations', models.JSONField(blank=True, default=list, help_text='trekking, cultural, wildlife, city, adventure…')),
                ('certifications', models.JSONField(blank=True, default=list, help_text='[{"name":"…","issuer":"…","year":2024}]')),
                ('license_number', models.CharField(blank=True, help_text='Government guide license where applicable', max_length=120)),
                ('regions', models.JSONField(blank=True, default=list, help_text='Districts/regions covered')),
                ('base_city', models.CharField(blank=True, max_length=120)),
                ('daily_rate_npr', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('availability', models.JSONField(blank=True, default=dict, help_text='{"mon":true,…} or {"from":"2026-10-01","to":"2026-11-15"}')),
                ('portfolio_urls', models.JSONField(blank=True, default=list)),
                ('services', models.JSONField(blank=True, default=list, help_text='Offered services with optional pricing')),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], db_index=True, default='unverified', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_note', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True, help_text='Show in the public guide directory when verified')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guide_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guides_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GuideApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('base_city', models.CharField(blank=True, max_length=120)),
                ('experience_summary', models.TextField(help_text='Guiding/tourism experience')),
                ('languages', models.JSONField(blank=True, default=list)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('destinations_covered', models.JSONField(blank=True, default=list)),
                ('certifications', models.JSONField(blank=True, default=list)),
                ('license_info', models.CharField(blank=True, help_text='Government/license information', max_length=240)),
                ('document_urls', models.JSONField(blank=True, default=list, help_text='Citizenship, license, training certificates…')),
                ('references', models.JSONField(blank=True, default=list)),
                ('expected_daily_rate_npr', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('availability', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('under_review', 'Under Review'), ('document_verification', 'Document Verification'), ('needs_info', 'Additional Info Requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='applied', max_length=24)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True, help_text='Latest review note / requested information')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guide_applications_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='tourist_gui_status_6f3e17_idx')],
            },
        ),
    ]
