# Generated by Django 5.2.17 on 2026-09-09 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0061_guideprofile_guideapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourismJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('role_type', models.CharField(choices=[('guide', 'Tour Guide'), ('trek_assistant', 'Trek Assistant'), ('photographer', 'Photographer'), ('content_creator', 'Content Creator'), ('translator', 'Translator'), ('customer_support', 'Customer Support'), ('hotel_staff', 'Hotel Staff'), ('travel_coordinator', 'Travel Coordinator'), ('experience_host', 'Local Experience Host'), ('event_staff', 'Event Staff'), ('data_contributor', 'Data / Content Contributor'), ('other', 'Other')], db_index=True, default='other', max_length=24)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full time'), ('part_time', 'Part time'), ('seasonal', 'Seasonal'), ('contract', 'Contract / gig'), ('volunteer', 'Volunteer')], default='contract', max_length=16)),
                ('compensation', models.CharField(blank=True, help_text='e.g. NPR 2,500/day or stipend', max_length=160)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('paused', 'Paused'), ('filled', 'Filled'), ('closed', 'Closed')], db_index=True, default='open', max_length=12)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tourism_jobs_posted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourismJobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover_letter', models.TextField()),
                ('experience_summary', models.TextField(blank=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('cv_url', models.URLField(blank=True, max_length=600)),
                ('portfolio_url', models.URLField(blank=True, max_length=600)),
                ('availability', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('hired', 'Hired'), ('rejected', 'Rejected')], db_index=True, default='applied', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='tourist.tourismjob')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_applications_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tourismjob',
            index=models.Index(fields=['status', 'role_type'], name='tourist_tou_status_b5fdea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tourismjobapplication',
            unique_together={('job', 'user')},
        ),
    ]
