# Generated by Django 5.0.6 on 2026-09-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0063_guidebookingrequest_guidereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentsection',
            name='published_snapshot',
            field=models.JSONField(blank=True, help_text='Frozen content the public site serves. Edits write the live (draft) fields; Publish copies them here so drafts never leak.', null=True),
        ),
    ]
