# Generated by Django 5.0.6 on 2026-09-13 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0067_support_navigation_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='correction_reason',
            field=models.TextField(blank=True, help_text='Reason recorded with the latest admin correction, if any.'),
        ),
        migrations.AddField(
            model_name='destination',
            name='imported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='imported_data',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot of the values from the most recent external import (field -> value). Admin-edited fields are never overwritten; differing incoming values become ImportConflict rows instead.'),
        ),
        migrations.AddField(
            model_name='destination',
            name='provenance',
            field=models.CharField(choices=[('manual', 'Created/edited by staff'), ('imported', 'Imported from external source'), ('user_suggested', 'Suggested by a user')], db_index=True, default='imported', help_text="Where this record came from. Admin corrections make it 'manual'.", max_length=20),
        ),
        migrations.AddField(
            model_name='destinationauditlog',
            name='field_changes',
            field=models.JSONField(blank=True, default=list, help_text='Field-level before/after: [{"field":"name","old":"...","new":"..."}]'),
        ),
        migrations.AddField(
            model_name='destinationauditlog',
            name='reason',
            field=models.TextField(blank=True, help_text='Admin-supplied reason for this action, when required.'),
        ),
        migrations.CreateModel(
            name='ContentProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposed_fields', models.JSONField(default=dict, help_text='field -> proposed new value (scalars only)')),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved & applied'), ('rejected', 'Rejected'), ('sent_back', 'Sent back for editing')], db_index=True, default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='tourist.destination')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_proposals', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DuplicateDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verdict', models.CharField(choices=[('not_duplicate', 'Not a duplicate'), ('merged', 'Merged')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('surviving_id', models.PositiveIntegerField(blank=True, help_text='For merges: id of the record that survived.', null=True)),
                ('merged_snapshot', models.JSONField(blank=True, default=dict, help_text='Pre-merge snapshot of the absorbed record (undo aid).')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_decisions', to=settings.AUTH_USER_MODEL)),
                ('destination_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_pairs_a', to='tourist.destination')),
                ('destination_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_pairs_b', to='tourist.destination')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.CharField(max_length=60)),
                ('current_value', models.TextField(blank=True)),
                ('incoming_value', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, help_text='Where the incoming value came from (e.g. osm/csv).', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('accepted', 'Incoming value accepted'), ('kept', 'Current value kept'), ('edited', 'Admin wrote a manual value')], db_index=True, default='pending', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_conflicts', to='tourist.destination')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_import_conflicts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='duplicatedecision',
            constraint=models.UniqueConstraint(fields=('destination_a', 'destination_b', 'verdict'), name='unique_duplicate_verdict'),
        ),
        migrations.AddConstraint(
            model_name='importconflict',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('destination', 'field'), name='unique_pending_conflict_per_field'),
        ),
    ]
