# Generated by Django 5.0.6 on 2026-09-10 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0068_seed_routing_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('capital', models.CharField(blank=True, max_length=150)),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('region_type', models.CharField(blank=True, help_text="Geographic character note from the seed dataset (e.g. 'Hill/Libang (Rolpa Bazar)').", max_length=150)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('elevation_m', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text="Curated/verified text. Left blank until verified — the API renders 'Information unavailable', never fabricated copy.")),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='districts', to='tourist.province')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
