# Generated by Django 5.0.6 on 2026-09-13 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0069_backfill_provenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmsrevision',
            name='resource',
            field=models.CharField(choices=[('pages', 'Pages'), ('sections', 'Sections'), ('navigation', 'Navigation'), ('settings', 'Settings'), ('translations', 'Translations'), ('destinations', 'Destinations')], max_length=20),
        ),
    ]
