# Generated by Django 5.0.6 on 2026-09-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0070_alter_cmsrevision_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='external_id',
            field=models.BigIntegerField(blank=True, help_text='External source id (e.g. OSM node id). OSM ids exceed int4 range, so this must stay BigIntegerField on PostgreSQL.', null=True, unique=True),
        ),
    ]
