# Generated by Django 5.0.6 on 2026-09-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0071_alter_destination_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='meta_description',
            field=models.CharField(blank=True, default='', help_text='Optional search-result description. Blank derives from the real description.', max_length=320),
        ),
        migrations.AddField(
            model_name='destination',
            name='meta_robots',
            field=models.CharField(blank=True, choices=[('', 'Default (index)'), ('noindex', 'No index')], default='', help_text='Set to noindex to keep this destination out of search engines.', max_length=20),
        ),
        migrations.AddField(
            model_name='destination',
            name='og_image_url',
            field=models.URLField(blank=True, default='', help_text='Optional social-share image URL. Blank uses the cover image.', max_length=600),
        ),
        migrations.AddField(
            model_name='destination',
            name='search_visible',
            field=models.BooleanField(default=True, help_text='Uncheck to exclude this destination from the public sitemap.'),
        ),
        migrations.AddField(
            model_name='destination',
            name='seo_title',
            field=models.CharField(blank=True, default='', help_text='Optional search-result title. Blank uses the destination name.', max_length=70),
        ),
    ]
