# Generated by Django 5.0.6 on 2026-09-11 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0072_final_page_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentsection',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('changes_requested', 'Changes Requested'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('published', 'Published')], default='published', max_length=20),
        ),
        migrations.AlterField(
            model_name='managedpage',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('changes_requested', 'Changes Requested'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('published', 'Published')], default='published', max_length=20),
        ),
    ]
