# Generated by Django 5.0.6 on 2026-09-12 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0073_alter_contentsection_status_alter_managedpage_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MunicipalityMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180, unique=True)),
                ('district', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=60)),
                ('source', models.CharField(choices=[('csv_import', 'Admin CSV import'), ('admin', 'Admin manual'), ('coordinate_derived', 'Coordinate-derived candidate')], default='admin', max_length=30)),
                ('verified', models.BooleanField(default=False)),
                ('matched_destination_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
