# Generated by Django 5.0.6 on 2026-09-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0074_municipalitymapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osmessentialservice',
            name='category',
            field=models.CharField(choices=[('hospital', 'Hospital'), ('clinic', 'Clinic'), ('pharmacy', 'Pharmacy'), ('police', 'Police'), ('armed_force', 'Armed Force'), ('fire_station', 'Fire Station'), ('bank', 'Bank'), ('blood_bank', 'Blood Bank'), ('atm', 'ATM'), ('ambulance', 'Ambulance'), ('municipality_office', 'Municipality Office'), ('tourism_office', 'Tourism Information Office'), ('restaurant', 'Restaurant'), ('cafe', 'Cafe'), ('fast_food', 'Fast Food'), ('bakery', 'Bakery'), ('bar', 'Bar / Pub'), ('doctors', 'Doctors'), ('dentist', 'Dentist'), ('fuel', 'Fuel Station'), ('bus_station', 'Bus Station'), ('taxi', 'Taxi'), ('supermarket', 'Supermarket'), ('marketplace', 'Marketplace'), ('charging_station', 'EV Charging Station'), ('guest_house', 'Guest House / Hostel')], max_length=30),
        ),
    ]
