# Generated by Django 5.0.6 on 2026-09-28
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tourist", "0075_fieldverificationreport_fieldverificationphoto_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="website",
            field=models.URLField(blank=True, default=""),
        ),
    ]
