# Generated by Django 5.0.6 on 2026-09-12 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0075_alter_osmessentialservice_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrekkingRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('region', models.CharField(blank=True, help_text='e.g. Annapurna, Everest, Langtang, Kanchenjunga, Far West.', max_length=120)),
                ('district', models.CharField(blank=True, max_length=120)),
                ('start_point', models.CharField(blank=True, max_length=180)),
                ('end_point', models.CharField(blank=True, max_length=180)),
                ('total_distance_km', models.FloatField(blank=True, null=True)),
                ('total_duration_days', models.IntegerField(blank=True, null=True)),
                ('max_elevation_m', models.IntegerField(blank=True, null=True)),
                ('difficulty', models.CharField(blank=True, choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('strenuous', 'Strenuous'), ('expedition', 'Expedition grade')], max_length=20)),
                ('best_season', models.CharField(blank=True, help_text="e.g. 'Mar-May, Sep-Nov'. Blank until verified.", max_length=120)),
                ('permits', models.JSONField(blank=True, default=list, help_text='List of {name, issuer, cost_note}. Empty until verified.')),
                ('accommodation', models.TextField(blank=True)),
                ('safety_notes', models.TextField(blank=True)),
                ('description', models.TextField(blank=True, help_text="Verified text only. Blank renders 'Information unavailable', never fabricated copy.")),
                ('source_name', models.CharField(blank=True, max_length=180)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('source_imported_at', models.DateTimeField(blank=True, null=True)),
                ('verification_state', models.CharField(choices=[('unverified', 'Unverified import'), ('pending', 'Pending admin review'), ('verified', 'Verified against authoritative source'), ('rejected', 'Rejected / stale')], default='unverified', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verified_by', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrekkingStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('name', models.CharField(blank=True, help_text="e.g. 'Jomsom to Kalopani'. Blank until verified.", max_length=180)),
                ('from_place', models.CharField(blank=True, max_length=180)),
                ('to_place', models.CharField(blank=True, max_length=180)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('elevation_gain_m', models.IntegerField(blank=True, null=True)),
                ('elevation_loss_m', models.IntegerField(blank=True, null=True)),
                ('duration_hours', models.FloatField(blank=True, null=True)),
                ('verification_state', models.CharField(choices=[('unverified', 'Unverified import'), ('pending', 'Pending admin review'), ('verified', 'Verified against authoritative source'), ('rejected', 'Rejected / stale')], default='unverified', max_length=20)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='tourist.trekkingroute')),
            ],
            options={
                'ordering': ['route', 'day_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='trekkingstage',
            constraint=models.UniqueConstraint(fields=('route', 'day_number'), name='uniq_trek_stage_day'),
        ),
    ]
