# Generated by Django 5.0.6 on 2026-09-23 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0073_alter_contentsection_status_alter_managedpage_status'),
        ('tourist', '0076_passwordresetotp'),
    ]

    operations = [
    ]
