# Generated by Django 5.0.6 on 2026-09-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0076_trekkingroute_trekkingstage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='osmessentialservice',
            name='last_enriched_at',
            field=models.DateTimeField(blank=True, help_text='When OSM tags were last re-read into this row.', null=True),
        ),
        migrations.AddField(
            model_name='osmessentialservice',
            name='name_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='osmessentialservice',
            name='name_ne',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='osmessentialservice',
            name='operator',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='osmessentialservice',
            name='verification_state',
            field=models.CharField(choices=[('imported', 'Imported from OSM (unverified)'), ('source_verified', 'Cross-checked against source extract'), ('admin_review', 'Queued for admin review'), ('verified', 'Admin verified (authoritative)'), ('rejected', 'Rejected / stale')], db_index=True, default='imported', help_text='Only admin action may set VERIFIED/REJECTED; imports stay IMPORTED.', max_length=20),
        ),
        migrations.AddField(
            model_name='osmessentialservice',
            name='website',
            field=models.URLField(blank=True, max_length=600),
        ),
    ]
