# Generated by Django 5.0.6 on 2026-09-12 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0077_osmessentialservice_last_enriched_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config_key', models.CharField(max_length=120, unique=True)),
                ('kind', models.CharField(choices=[('municipality_hub', 'Municipality / administrative hub'), ('landmark', 'Nepal landmark')], max_length=30)),
                ('name', models.CharField(max_length=180)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('district', models.CharField(blank=True, max_length=80)),
                ('province', models.CharField(blank=True, max_length=60)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('category_name', models.CharField(blank=True, max_length=120)),
                ('provenance', models.CharField(blank=True, help_text='Where these coordinates originally came from (config file + migration date).', max_length=300)),
                ('linked_destination', models.ForeignKey(blank=True, help_text='Existing canonical destination this config entry duplicates, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_place_aliases', to='tourist.destination')),
            ],
            options={
                'ordering': ['kind', 'name'],
            },
        ),
    ]
