# Generated by Django 6.0.7 on 2026-09-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0077_merge_20260923_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='emergency_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='policestation',
            name='emergency_available',
            field=models.BooleanField(default=False),
        ),
    ]
