# Generated by Django 5.0.6 on 2026-09-12 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tourist', '0078_configplace'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='places/gallery/')),
                ('external_url', models.URLField(blank=True, help_text='Used instead of `image` for externally-hosted photos.')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary/cover image for the place.')),
                ('source', models.CharField(choices=[('admin_upload', 'Admin upload'), ('admin_link', 'Admin-provided external URL')], default='admin_upload', max_length=20)),
                ('source_url', models.URLField(blank=True, help_text='Provenance page for externally-hosted images.', max_length=500)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place_images_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', 'ordering', 'id'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='tourist_pla_content_61e585_idx')],
            },
        ),
    ]
