# Generated by Django 6.0.7 on 2026-09-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0078_honest_emergency_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='managedpage',
            name='published_snapshot',
            field=models.JSONField(blank=True, help_text='Frozen public page metadata. Draft edits never alter this snapshot until Publish.', null=True),
        ),
    ]
