# Generated by Django 5.0.6 on 2026-09-13 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0079_placeimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminFieldOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_label', models.CharField(db_index=True, max_length=80)),
                ('object_id', models.PositiveIntegerField(db_index=True)),
                ('field', models.CharField(max_length=80)),
                ('value', models.TextField(blank=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('overridden_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('model_label', 'object_id', 'field')},
            },
        ),
        migrations.CreateModel(
            name='ImportConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.CharField(max_length=80)),
                ('current_value', models.TextField(blank=True)),
                ('proposed_value', models.TextField(blank=True)),
                ('source', models.CharField(default='osm_csv', max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('kept', 'Kept Current'), ('accepted', 'Accepted New')], db_index=True, default='pending', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.CharField(blank=True, max_length=255)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_conflicts', to='tourist.destination')),
                ('resolved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_import_conflicts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['destination', 'field', 'status'], name='tourist_imp_destina_78114b_idx')],
            },
        ),
    ]
