# Generated by Django 5.0.6 on 2026-09-13 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0080_adminfieldoverride_importconflict'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicateDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_a', models.PositiveIntegerField()),
                ('id_b', models.PositiveIntegerField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('decided_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('id_a', 'id_b')},
            },
        ),
    ]
