# Generated by Django 6.0.7 on 2026-09-26 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0081_unpublish_seeded_cms_placeholders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destinationimage',
            options={'ordering': ['-is_cover', 'ordering', '-is_promoted', '-view_count', '-created_at'], 'permissions': [('review_destinationimage', 'Can review destination media'), ('assign_destinationimage_authenticity', 'Can assign destination media authenticity score'), ('assign_destinationimage_destination_match', 'Can assign destination media destination-match score'), ('approve_destinationimage_review', 'Can approve or reject a destination media review')]},
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='authenticity_score_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='authenticity_score_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authenticity_scores_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='destination_match_score_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='destination_match_score_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_match_scores_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='media_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='media_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_reviews_performed', to=settings.AUTH_USER_MODEL),
        ),
    ]
