# Generated by Django 5.0.6 on 2026-09-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0081_unpublish_seeded_cms_placeholders'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForexRateSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_date', models.DateField(unique=True)),
                ('published_on', models.CharField(blank=True, default='', max_length=40)),
                ('rates', models.JSONField(default=dict)),
                ('source_name', models.CharField(default='Nepal Rastra Bank', max_length=120)),
                ('source_url', models.URLField(max_length=300)),
                ('fetched_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-rate_date'],
            },
        ),
        migrations.AddField(
            model_name='destination',
            name='elevation_m',
            field=models.IntegerField(blank=True, help_text='Elevation in metres from a cited source; empty = not recorded', null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='elevation_retrieved_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='elevation_source',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
    ]
