# Generated by Django 6.0.7 on 2026-09-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0082_destinationimage_review_provenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gps_accuracy_m',
            field=models.FloatField(blank=True, help_text='Device-reported accuracy in metres', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gps_recorded_at',
            field=models.DateTimeField(blank=True, help_text='When the device took the fix', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gps_validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gps_validation_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='gps_validation_state',
            field=models.CharField(blank=True, help_text='precise / approximate / unusable', max_length=20),
        ),
    ]
