# Generated by Django 5.0.6 on 2026-09-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0086_superuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelplan',
            name='share_token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='shared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
