# Generated by Django 6.0.7 on 2026-09-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0087_user_gps_fix_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='coordinate_retrieved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='coordinate_source',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='hospital',
            name='coordinate_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='policestation',
            name='coordinate_retrieved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policestation',
            name='coordinate_source',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='policestation',
            name='coordinate_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
