# Generated by Django 6.0.7 on 2026-09-28 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0088_service_coordinate_provenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationimage',
            name='review_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
