# Generated by Django 5.2.17 on 2026-09-29 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0087_hotel_website'),
        ('tourist', '0089_destination_image_review_note'),
        ('tourist', '0093_archive_duplicate_baidam_police_station'),
    ]

    operations = [
    ]
