# Generated by Django 5.1.15 on 2026-09-30 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0083_user_gps_fix_quality'),
        ('tourist', '0087_hotel_website'),
        ('tourist', '0089_destination_image_review_note'),
        ('tourist', '0093_archive_duplicate_baidam_police_station'),
    ]

    operations = [
    ]
