# Generated by Django 5.2.17 on 2026-09-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0094_merge_20260929_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='website',
            field=models.URLField(blank=True, max_length=600),
        ),
    ]
