# Generated by Django 6.0.7 on 2026-09-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tourist", "0096_gps_columns_and_hotel_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destinationimage",
            name="external_url",
            field=models.URLField(
                blank=True,
                help_text="Used instead of `image` for externally-hosted photos (Unsplash/Wikimedia/etc.)",
                max_length=700,
            ),
        ),
    ]
