# Generated by Django 5.1.15 on 2026-10-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0097_alter_destinationimage_external_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='policestation',
            name='district',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='destinationimage',
            name='source',
            field=models.CharField(choices=[('admin', 'Admin Upload'), ('user_upload', 'Community Upload'), ('unsplash', 'Unsplash'), ('pexels', 'Pexels'), ('pixabay', 'Pixabay'), ('flickr', 'Flickr'), ('openverse', 'Openverse'), ('wikimedia', 'Wikimedia Commons'), ('google_places', 'Google Places'), ('foursquare', 'Foursquare'), ('ai_generated', 'AI Generated'), ('reference', 'Reference Image'), ('image_server', 'Standalone Image Server')], default='admin', max_length=20),
        ),
    ]
