# Generated by Django 5.2.17 on 2026-10-02 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0096_seed_cms_global_sections_and_content'),
        ('tourist', '0097_alter_destinationimage_external_url'),
    ]

    operations = [
    ]
