# Generated by Django 5.2.17 on 2026-10-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0098_merge_20261002_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='coordinate_retrieved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='coordinate_source',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='hotel',
            name='coordinate_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='destination',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='destinationimage',
            name='external_url',
            field=models.URLField(blank=True, help_text='Used instead of `image` for externally-hosted photos (Unsplash/Wikimedia/etc.)'),
        ),
    ]
