# Generated by Django 5.2.17 on 2026-10-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0098_merge_20261002_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='coordinate_retrieved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='coordinate_source',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='hotel',
            name='coordinate_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='destination',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='destinationimage',
            name='external_url',
            # Widen to 1000 rather than URLField's default 200. Real
            # Wikimedia/Unsplash URLs in this catalogue reach ~697 characters and
            # 738 rows exceeded 200, so the default made Postgres abort the whole
            # migration with `value too long for type character varying(200)` --
            # which failed every Render deploy at migrate time. Widening keeps every
            # existing URL intact instead of truncating it.
            field=models.URLField(
                blank=True, max_length=1000,
                help_text='Used instead of `image` for externally-hosted photos (Unsplash/Wikimedia/etc.)',
            ),
        ),
    ]
