# Generated by Django 6.0.7 on 2026-10-02 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0098_policestation_district'),
        ('tourist', '0099_hotel_coordinate_retrieved_at_and_more'),
    ]

    operations = [
    ]
