# Generated by Django 6.0.7 on 2026-10-03 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0100_merge_0098_policestation_0099_hotel'),
        ('tourist', '0100_merge_20261002_2142'),
    ]

    operations = [
    ]
