# Generated by Django 6.0.7 on 2026-10-03 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0101_merge_20261003_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='UITranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=200)),
                ('language', models.CharField(db_index=True, max_length=10)),
                ('value', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ui_translations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['key'],
                'indexes': [models.Index(fields=['language', 'key'], name='tourist_uit_languag_d13c80_idx')],
                'constraints': [models.UniqueConstraint(fields=('key', 'language'), name='unique_ui_translation_key_lang')],
            },
        ),
    ]
