# Generated by Django 6.0.7 on 2026-10-03 08:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0102_ui_translations'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationBudgetProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget_daily_npr', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('standard_daily_npr', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('premium_daily_npr', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('transport_intercity_npr', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('transport_local_npr', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('accommodation_npr', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('food_npr', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('entry_fees_npr', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('guide_porter_npr', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('permits_npr', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('misc_npr', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('usd_rate_used', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('budget_daily_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('standard_daily_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('premium_daily_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('last_computed', models.DateTimeField(auto_now=True)),
                ('computation_version', models.PositiveIntegerField(default=1)),
                ('components_used', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['destination__name'],
            },
        ),
        migrations.CreateModel(
            name='PriceComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('province', models.CharField(blank=True, help_text='Leave blank for national default', max_length=100)),
                ('district', models.CharField(blank=True, help_text='Leave blank for province-wide', max_length=100)),
                ('category', models.CharField(choices=[('transport_intercity', 'Intercity Transport (per km)'), ('transport_local', 'Local Transport (per km)'), ('transport_flight', 'Domestic Flight (per route)'), ('accommodation_budget', 'Budget Accommodation (per night)'), ('accommodation_standard', 'Standard Accommodation (per night)'), ('accommodation_luxury', 'Luxury Accommodation (per night)'), ('food_budget', 'Budget Meals (per day)'), ('food_standard', 'Standard Meals (per day)'), ('food_premium', 'Premium Meals (per day)'), ('entry_fee_park', 'National Park/Protected Area Entry'), ('entry_fee_heritage', 'Heritage Site Entry'), ('entry_fee_museum', 'Museum Entry'), ('entry_fee_other', 'Other Entry Fees'), ('guide_porter', 'Guide/Porter (per day)'), ('permit_trek', 'Trekking Permit'), ('permit_other', 'Other Permits'), ('misc', 'Miscellaneous')], max_length=30)),
                ('name', models.CharField(help_text="e.g., 'Kathmandu-Pokhara Tourist Bus', 'Chitwan Park Entry Foreigner'", max_length=200)),
                ('unit', models.CharField(help_text="e.g., 'per km', 'per night', 'per person', 'per day'", max_length=50)),
                ('base_price_npr', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NPR', max_length=10)),
                ('effective_from', models.DateField(default=django.utils.timezone.now)),
                ('effective_until', models.DateField(blank=True, help_text='Null = ongoing', null=True)),
                ('source_type', models.CharField(choices=[('government_gazette', 'Government Gazette / Official Notification'), ('tourism_board', 'Nepal Tourism Board'), ('national_park', 'National Park Authority'), ('dotm', 'Department of Transport Management'), ('airline', 'Airline Official'), ('hotel_association', 'Hotel Association'), ('restaurant_association', 'Restaurant Association'), ('guide_association', 'Guide Association'), ('user_feedback', 'Verified User Feedback (aggregated)'), ('admin_manual', 'Admin Manual Entry'), ('ml_estimated', 'ML Estimated')], default='admin_manual', max_length=30)),
                ('source_reference', models.CharField(blank=True, help_text='Gazette number, URL, document reference', max_length=500)),
                ('source_document', models.FileField(blank=True, null=True, upload_to='price_sources/')),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-effective_from', 'category', 'district'],
            },
        ),
        migrations.CreateModel(
            name='PriceComponentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_price_npr', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_price_npr', models.DecimalField(decimal_places=2, max_digits=12)),
                ('old_effective_until', models.DateField(blank=True, null=True)),
                ('new_effective_until', models.DateField(blank=True, null=True)),
                ('change_reason', models.CharField(max_length=500)),
                ('change_source', models.CharField(choices=[('government_gazette', 'Government Gazette / Official Notification'), ('tourism_board', 'Nepal Tourism Board'), ('national_park', 'National Park Authority'), ('dotm', 'Department of Transport Management'), ('airline', 'Airline Official'), ('hotel_association', 'Hotel Association'), ('restaurant_association', 'Restaurant Association'), ('guide_association', 'Guide Association'), ('user_feedback', 'Verified User Feedback (aggregated)'), ('admin_manual', 'Admin Manual Entry'), ('ml_estimated', 'ML Estimated')], max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='travelexpensefeedback',
            name='extra_cost',
        ),
        migrations.RemoveField(
            model_name='travelexpensefeedback',
            name='travel_cost',
        ),
        migrations.AddField(
            model_name='travelexpensefeedback',
            name='accommodation_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='travelexpensefeedback',
            name='aggregated_to_components',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='travelexpensefeedback',
            name='aggregation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='travelexpensefeedback',
            name='guide_porter_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='travelexpensefeedback',
            name='local_transport_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='travelexpensefeedback',
            name='misc_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='travelexpensefeedback',
            name='permit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='travelexpensefeedback',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='travelexpensefeedback',
            name='transport_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='travelexpensefeedback',
            name='transport_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='travelexpensefeedback',
            name='travel_dates',
            field=models.JSONField(default=dict, help_text="{start: '2024-10-01', end: '2024-10-05'}"),
        ),
        migrations.AddField(
            model_name='travelexpensefeedback',
            name='travel_style',
            field=models.CharField(choices=[('budget', 'Budget'), ('standard', 'Standard'), ('premium', 'Premium')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='travelexpensefeedback',
            name='verification_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='travelexpensefeedback',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified & Aggregated'), ('rejected', 'Rejected'), ('flagged', 'Flagged for Review')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='travelexpensefeedback',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelexpensefeedback',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_expense_feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='travelexpensefeedback',
            name='route_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='travelexpensefeedback',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddIndex(
            model_name='travelexpensefeedback',
            index=models.Index(fields=['destination', 'verification_status'], name='tourist_tra_destina_d1db43_idx'),
        ),
        migrations.AddIndex(
            model_name='travelexpensefeedback',
            index=models.Index(fields=['verification_status', 'created_at'], name='tourist_tra_verific_7cedf0_idx'),
        ),
        migrations.AddField(
            model_name='destinationbudgetprofile',
            name='destination',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget_profile', to='tourist.destination'),
        ),
        migrations.AddField(
            model_name='pricecomponent',
            name='destination',
            field=models.ForeignKey(blank=True, help_text='Specific destination override', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_components', to='tourist.destination'),
        ),
        migrations.AddField(
            model_name='pricecomponent',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_price_components', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricecomponenthistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricecomponenthistory',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tourist.pricecomponent'),
        ),
        migrations.AddIndex(
            model_name='pricecomponent',
            index=models.Index(fields=['category', 'province', 'district', 'destination', 'is_active', 'effective_from'], name='tourist_pri_categor_5d7c3b_idx'),
        ),
        migrations.AddIndex(
            model_name='pricecomponent',
            index=models.Index(fields=['effective_from', 'effective_until'], name='tourist_pri_effecti_f207d5_idx'),
        ),
    ]
