# Generated by Django 6.0.7 on 2026-10-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0103_destinationbudgetprofile_pricecomponent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmsrevision',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Extra context: e.g., which fields changed, comparison data'),
        ),
        migrations.AlterField(
            model_name='cmsrevision',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('publish', 'Publish'), ('unpublish', 'Unpublish'), ('schedule', 'Schedule'), ('rollback', 'Rollback'), ('duplicate', 'Duplicate'), ('reorder', 'Reorder'), ('import', 'Import'), ('export', 'Export'), ('revert', 'Revert'), ('restore', 'Restore')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cmsrevision',
            name='resource',
            field=models.CharField(choices=[('pages', 'Pages'), ('sections', 'Sections'), ('navigation', 'Navigation'), ('settings', 'Settings'), ('translations', 'Translations'), ('destinations', 'Destinations'), ('components', 'Components'), ('banners', 'Banners'), ('widgets', 'Widgets'), ('navigation_items', 'Navigation Items'), ('themes', 'Themes'), ('global_settings', 'Global Settings'), ('page_templates', 'Page Templates'), ('widget_instances', 'Widget Instances'), ('media_library', 'Media Library'), ('themes', 'Themes'), ('global_settings', 'Global Settings'), ('navbar', 'Navbar'), ('toolbar', 'Toolbar'), ('footer', 'Footer'), ('notifications', 'Notifications'), ('notices', 'Notices'), ('media_library', 'Media Library'), ('page_templates', 'Page Templates')], max_length=30),
        ),
    ]
