# Generated by Django 6.0.7 on 2026-10-04 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0104_cmsrevision_metadata_alter_cmsrevision_action_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=400)),
                ('days_count', models.PositiveIntegerField(default=1)),
                ('pace', models.CharField(default='Relaxed', max_length=50)),
                ('best_for', models.CharField(blank=True, max_length=300)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='travel_guides/')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_guides', to='tourist.destination')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelGuideDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('route', models.CharField(blank=True, max_length=400)),
                ('travel_distance', models.CharField(blank=True, max_length=100)),
                ('travel_time', models.CharField(blank=True, max_length=100)),
                ('overnight_stay', models.CharField(blank=True, max_length=300)),
                ('morning', models.TextField(blank=True)),
                ('afternoon', models.TextField(blank=True)),
                ('evening', models.TextField(blank=True)),
                ('practical_notes', models.TextField(blank=True)),
                ('attractions', models.ManyToManyField(blank=True, related_name='travel_guide_days_attractions', to='tourist.destination')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='tourist.travelguide')),
                ('hospitals', models.ManyToManyField(blank=True, related_name='travel_guide_days', to='tourist.hospital')),
                ('hotels', models.ManyToManyField(blank=True, related_name='travel_guide_days', to='tourist.hotel')),
                ('primary_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_guide_days_primary', to='tourist.destination')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('guide', 'day_number')},
            },
        ),
    ]
