# Generated by Django 6.0.7 on 2026-10-05 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0088_relax_local_review_note'),
        ('tourist', '0105_travel_guides'),
    ]

    operations = [
    ]
