# Generated by Django 6.0.7 on 2026-10-05 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0106_merge_0088_relax_local_review_note_0105_travel_guides'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskanalysis',
            name='accident_trend',
            field=models.CharField(choices=[('improving', 'Improving'), ('stable', 'Stable'), ('worsening', 'Worsening')], default='stable', max_length=20),
        ),
        migrations.AddField(
            model_name='riskanalysis',
            name='accidents_last_5y',
            field=models.PositiveIntegerField(default=0, help_text='Recorded accidents over the last 5 years'),
        ),
        migrations.AddField(
            model_name='riskanalysis',
            name='accidents_last_year',
            field=models.PositiveIntegerField(default=0, help_text='Recorded accidents in the last 12 months'),
        ),
        migrations.AddField(
            model_name='riskanalysis',
            name='emergency_response_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Typical emergency response time in minutes', null=True),
        ),
        migrations.AddField(
            model_name='riskanalysis',
            name='family_safety',
            field=models.CharField(choices=[('very_safe', 'Very Safe'), ('safe', 'Safe'), ('moderate', 'Moderate'), ('risky', 'Risky'), ('unsafe', 'Unsafe')], default='moderate', max_length=20),
        ),
        migrations.AddField(
            model_name='riskanalysis',
            name='fatal_accidents_last_year',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='riskanalysis',
            name='female_traveler_safety',
            field=models.CharField(choices=[('very_safe', 'Very Safe'), ('safe', 'Safe'), ('moderate', 'Moderate'), ('risky', 'Risky'), ('unsafe', 'Unsafe')], default='moderate', max_length=20),
        ),
        migrations.AddField(
            model_name='riskanalysis',
            name='high_altitude_risk',
            field=models.CharField(choices=[('very_safe', 'Very Safe'), ('safe', 'Safe'), ('moderate', 'Moderate'), ('risky', 'Risky'), ('unsafe', 'Unsafe')], default='moderate', max_length=20),
        ),
        migrations.AddField(
            model_name='riskanalysis',
            name='hospital_coverage',
            field=models.CharField(choices=[('none', 'None nearby'), ('poor', 'Poor'), ('fair', 'Fair'), ('good', 'Good'), ('excellent', 'Excellent')], default='fair', max_length=20),
        ),
        migrations.AddField(
            model_name='riskanalysis',
            name='last_major_incident_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskanalysis',
            name='last_reviewed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskanalysis',
            name='lightning_risk',
            field=models.CharField(choices=[('very_safe', 'Very Safe'), ('safe', 'Safe'), ('moderate', 'Moderate'), ('risky', 'Risky'), ('unsafe', 'Unsafe')], default='moderate', max_length=20),
        ),
        migrations.AddField(
            model_name='riskanalysis',
            name='medical_facility_level',
            field=models.CharField(choices=[('none', 'None nearby'), ('poor', 'Poor'), ('fair', 'Fair'), ('good', 'Good'), ('excellent', 'Excellent')], default='fair', max_length=20),
        ),
        migrations.AddField(
            model_name='riskanalysis',
            name='mobile_network_coverage',
            field=models.CharField(choices=[('none', 'None nearby'), ('poor', 'Poor'), ('fair', 'Fair'), ('good', 'Good'), ('excellent', 'Excellent')], default='fair', max_length=20),
        ),
        migrations.AddField(
            model_name='riskanalysis',
            name='monsoon_risk',
            field=models.CharField(choices=[('very_safe', 'Very Safe'), ('safe', 'Safe'), ('moderate', 'Moderate'), ('risky', 'Risky'), ('unsafe', 'Unsafe')], default='moderate', max_length=20),
        ),
        migrations.AddField(
            model_name='riskanalysis',
            name='night_safety',
            field=models.CharField(choices=[('very_safe', 'Very Safe'), ('safe', 'Safe'), ('moderate', 'Moderate'), ('risky', 'Risky'), ('unsafe', 'Unsafe')], default='moderate', max_length=20),
        ),
        migrations.AddField(
            model_name='riskanalysis',
            name='overall_safety_score',
            field=models.FloatField(blank=True, help_text='0-100 composite safety score', null=True),
        ),
        migrations.AddField(
            model_name='riskanalysis',
            name='police_presence',
            field=models.CharField(choices=[('none', 'None nearby'), ('poor', 'Poor'), ('fair', 'Fair'), ('good', 'Good'), ('excellent', 'Excellent')], default='fair', max_length=20),
        ),
        migrations.AddField(
            model_name='riskanalysis',
            name='rescue_availability',
            field=models.CharField(choices=[('none', 'None nearby'), ('poor', 'Poor'), ('fair', 'Fair'), ('good', 'Good'), ('excellent', 'Excellent')], default='fair', max_length=20),
        ),
        migrations.AddField(
            model_name='riskanalysis',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riskanalysis',
            name='risk_causes',
            field=models.JSONField(blank=True, default=list, help_text='List of {cause, category, severity, frequency, note}'),
        ),
        migrations.AddField(
            model_name='riskanalysis',
            name='road_quality',
            field=models.CharField(choices=[('none', 'None nearby'), ('poor', 'Poor'), ('fair', 'Fair'), ('good', 'Good'), ('excellent', 'Excellent')], default='fair', max_length=20),
        ),
        migrations.AddField(
            model_name='riskanalysis',
            name='safety_summary',
            field=models.TextField(blank=True, help_text='Plain-language safety summary for travellers'),
        ),
        migrations.AddField(
            model_name='riskanalysis',
            name='solo_travel_safety',
            field=models.CharField(choices=[('very_safe', 'Very Safe'), ('safe', 'Safe'), ('moderate', 'Moderate'), ('risky', 'Risky'), ('unsafe', 'Unsafe')], default='moderate', max_length=20),
        ),
        migrations.AddField(
            model_name='riskanalysis',
            name='summer_heat_risk',
            field=models.CharField(choices=[('very_safe', 'Very Safe'), ('safe', 'Safe'), ('moderate', 'Moderate'), ('risky', 'Risky'), ('unsafe', 'Unsafe')], default='moderate', max_length=20),
        ),
        migrations.AddField(
            model_name='riskanalysis',
            name='trail_marking',
            field=models.CharField(choices=[('none', 'None nearby'), ('poor', 'Poor'), ('fair', 'Fair'), ('good', 'Good'), ('excellent', 'Excellent')], default='fair', max_length=20),
        ),
        migrations.AddField(
            model_name='riskanalysis',
            name='travel_safety_rating',
            field=models.CharField(choices=[('very_safe', 'Very Safe'), ('safe', 'Safe'), ('moderate', 'Moderate'), ('risky', 'Risky'), ('unsafe', 'Unsafe')], default='moderate', max_length=20),
        ),
        migrations.AddField(
            model_name='riskanalysis',
            name='travel_safety_score',
            field=models.FloatField(blank=True, help_text='0-100, higher = safer', null=True),
        ),
        migrations.AddField(
            model_name='riskanalysis',
            name='uv_exposure',
            field=models.CharField(choices=[('very_safe', 'Very Safe'), ('safe', 'Safe'), ('moderate', 'Moderate'), ('risky', 'Risky'), ('unsafe', 'Unsafe')], default='moderate', max_length=20),
        ),
        migrations.AddField(
            model_name='riskanalysis',
            name='winter_snow_risk',
            field=models.CharField(choices=[('very_safe', 'Very Safe'), ('safe', 'Safe'), ('moderate', 'Moderate'), ('risky', 'Risky'), ('unsafe', 'Unsafe')], default='moderate', max_length=20),
        ),
        migrations.AddIndex(
            model_name='riskanalysis',
            index=models.Index(fields=['destination'], name='tourist_ris_destina_c4269d_idx'),
        ),
        migrations.AddIndex(
            model_name='riskanalysis',
            index=models.Index(fields=['risk_category'], name='tourist_ris_risk_ca_0da1de_idx'),
        ),
    ]
