# Generated by Django 5.1.15 on 2026-10-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0107_riskanalysis_accident_trend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currenthazard',
            name='hazard_type',
            field=models.CharField(choices=[('flood', 'Flood'), ('landslide', 'Landslide'), ('avalanche', 'Avalanche'), ('earthquake', 'Earthquake'), ('glof', 'Glacial lake outburst flood'), ('heavy_rain', 'Heavy rain'), ('snowstorm', 'Snowstorm'), ('forest_fire', 'Forest fire'), ('lightning', 'Lightning'), ('extreme_weather', 'Extreme weather'), ('road_accident', 'Road accident'), ('health', 'Health / altitude'), ('civil_unrest', 'Civil unrest / protest / strike'), ('crime', 'Crime / theft / security incident'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='riskincident',
            name='hazard_type',
            field=models.CharField(choices=[('flood', 'Flood'), ('landslide', 'Landslide'), ('avalanche', 'Avalanche'), ('earthquake', 'Earthquake'), ('glof', 'Glacial lake outburst flood'), ('heavy_rain', 'Heavy rain'), ('snowstorm', 'Snowstorm'), ('forest_fire', 'Forest fire'), ('lightning', 'Lightning'), ('extreme_weather', 'Extreme weather'), ('road_accident', 'Road accident'), ('health', 'Health / altitude'), ('civil_unrest', 'Civil unrest / protest / strike'), ('crime', 'Crime / theft / security incident'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='risknewsreport',
            name='hazard_type',
            field=models.CharField(choices=[('flood', 'Flood'), ('landslide', 'Landslide'), ('avalanche', 'Avalanche'), ('earthquake', 'Earthquake'), ('glof', 'Glacial lake outburst flood'), ('heavy_rain', 'Heavy rain'), ('snowstorm', 'Snowstorm'), ('forest_fire', 'Forest fire'), ('lightning', 'Lightning'), ('extreme_weather', 'Extreme weather'), ('road_accident', 'Road accident'), ('health', 'Health / altitude'), ('civil_unrest', 'Civil unrest / protest / strike'), ('crime', 'Crime / theft / security incident'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
