# Generated by Django 5.1.15 on 2026-10-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0110_destination_is_unreadable_import'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationimage',
            name='external_url',
            field=models.URLField(blank=True, help_text="Used instead of `image` for externally-hosted photos (Unsplash/Wikimedia/etc.). Sized at 1000, not URLField's default 200: real Wikimedia/Unsplash URLs in the catalogue reach ~700 characters, and the default truncated 738 rows (and made Postgres refuse migration 0099 with 'value too long for character varying(200)').", max_length=1000),
        ),
    ]
