# Generated by Django 6.0.7 on 2026-10-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0111_alter_destinationimage_external_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='managednavigationitem',
            name='target',
            field=models.CharField(choices=[('_self', 'Same tab'), ('_blank', 'New tab')], default='_self', help_text='Where the navigation link opens', max_length=10),
        ),
    ]
