# Generated by Django 5.0.6 on 2026-09-20 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouteDiagnostics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, max_length=32)),
                ('mode', models.CharField(max_length=16)),
                ('distance_m', models.FloatField(blank=True, null=True)),
                ('duration_s', models.FloatField(blank=True, null=True)),
                ('fallback', models.BooleanField(db_index=True, default=False)),
                ('route_time_ms', models.IntegerField(default=0)),
                ('alternatives', models.IntegerField(default=0)),
                ('start_lat', models.FloatField(blank=True, null=True)),
                ('start_lng', models.FloatField(blank=True, null=True)),
                ('dest_lat', models.FloatField(blank=True, null=True)),
                ('dest_lng', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name_plural': 'route diagnostics',
                'ordering': ['-created_at'],
            },
        ),
    ]
