# Generated by Django 5.0.6 on 2026-09-20 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('mode', models.CharField(default='driving', max_length=16)),
                ('status', models.CharField(choices=[('NAVIGATING', 'navigating'), ('OFF_ROUTE', 'off route'), ('REROUTING', 'rerouting'), ('ARRIVED', 'arrived'), ('ENDED', 'ended'), ('FAILED', 'failed')], db_index=True, default='NAVIGATING', max_length=16)),
                ('source', models.CharField(blank=True, max_length=32)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_latitude', models.FloatField(blank=True, null=True)),
                ('last_longitude', models.FloatField(blank=True, null=True)),
                ('distance_remaining_m', models.FloatField(blank=True, null=True)),
                ('progress', models.FloatField(default=0.0)),
                ('off_route_count', models.IntegerField(default=0)),
                ('fix_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
